### ISSUE TITLE
Seeders cannot be refilled

### ISSUE THREAD

**Issue by 37cee** [loki79uk/FS22_UniversalAutoload#1]
So i tested the mod for a bit and in general it works. The game loads with most mods, except "Manual Attach". (nothing that conerns me at this early stage) 

One problem persisted with no mods, though. When i try to fill a seeder and pull up to any pallet (or bigbag) and i hit the refill button, nothing happens. When i disable the mod, i can hit "r" and the seeder starts refilling.

I'll test other fill triggers in a bit and see what happens.

______

Edit: so for me this is a problem for anything that fills from a trigger, i'll check the keybindings, if that will solve the issue.

______

Edit 2: Switched the Keybinds to see , if it is just a conflict here. But the game still did not find any trigger, that uses the "r" key

**Comment by jtsage** [comment]
A bit more info, from my little testing - this applies to buy stations too.  However, if you have AI doing the filling (aka AutoDrive in my case), it will fill just fine.  I did try removing the "start loading" key binding to see if it was a simple overlap, that didn't do it.

**Comment by loki79uk** [comment]
It could still be something to do with the key bindings - I had a lot of problems with keybinding issues/conficts during development.  I'm away for this week (kids half term), but will look at all the bugs when I get back.

**Comment by loki79uk** [comment]
Actually, I think I've fixed this..  I have updated the release with the new version so I can keep the same link.

**Comment by jtsage** [comment]
That did it for me. (tested buy station and big bag with vanilla big deere planter.

**Comment by 37cee** [comment]
Works for me , as well. 

Hope you enjoy the week with your kids!

**Comment by loki79uk** [comment]
Awesome! I'll close this issue for housekeeping, but of course please let me know on here if you find anything else.  :)
