### ISSUE TITLE
Using Sleep breaks autoload

### ISSUE THREAD

**Issue by MrTiepie** [loki79uk/FS22_UniversalAutoload#10]
Loading / Unloading not possible after using Sleep. F1 prompt menu shows R when initialy approaching trailer. When used, nothing happens and the pompt dissapears. Also when using R and being near loading area player character seems to be pulled in a bit. Almost as if the game wants to load the character into the trailer.
No other autoload mods are installed.

Sidenote: this is on MP have not tried it on SP

**Comment by loki79uk** [comment]
I'm thinking of changing the default key away from R. Maybe shift-R.  Just because it is causing me endless problems and conflicts.

The lag during loading could be explained by all the loading calculations being done server side, so it could depend on the server hardware how responsive it is.  I'll pay attention to this when I'm testing MP though.

**Comment by MrTiepie** [comment]
Maybe that would be the option. For that one in so many times you need to load/unload a trailer using one extra button is no hassle.

The lag is a bit weird but not a deal breaker. Love what you have made and it trumps most of the other implementations of autoload easily. Thank you

**Comment by loki79uk** [comment]
MP working again in: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-004

I have not tested the sleep trigger in MP yet, but if you get around to it first please let me know either way.

**Comment by MrTiepie** [comment]
Thanks for the updates. Sleep Trigger still breaks mod, though switching to Shift - R has made loading more stable its seems. Saw in update log that tension belts were disabled. Is it on purpose that also manual activation is disabled? Thank you for your efforts. Hope Giants will fix the tension belts soon and that you'll find the sleep trigger issue. Keep it up. It is really apreciated.

**Comment by loki79uk** [comment]
Yes, I disabled manual activation of the tension belts on purpose (i.e. the key binding is never set).  The default game keybindings are still active, but I have disabled the function to actually do the strapping.  That way they are never strapped duing the game loading process and so pallets that were strapped before the save can still be used in the game.  Other non-autoloading vehicles still have straps active, so you still need to be careful with using those.

I'm slowly working through the bug list.  I will look to see what is going on with the sleep trigger now.

**Comment by loki79uk** [comment]
I found it!  the sleep trigger causes g_gui:getIsGuiVisible() to always return true on a server, even after the game is resumed.  I'm not even sure why I put that there, I think just to stop debugging screen graphics from showing up behind the menu..

Anyway, this should be working now:  https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-009

**Comment by MrTiepie** [comment]
Nice! Thanks for the fix! I'll wait with installing a new version untill the tension belt issue is resolved, either by you or Giants..or both haha. Thanks a lot!

**Comment by loki79uk** [comment]
The current workaround of disabling tension belts is probably the best I can do until GIANTS fix properly. I did look at the properties of pallets before and after strapping, but I couldn't see anything obvious. I've still got other things too work on, and messing around with that will just be wasted time once it is resolved.
