### ISSUE TITLE
Enabling UA breaks CP Open/Close Course Generator

### ISSUE THREAD

**Issue by daFreeMan** [loki79uk/FS22_UniversalAutoload#101]
With UA 1.2.2.5 (and an earlier version, I can get that number if needed) and CP 7.1.0.4, CoursePlay does not present the "Open/Close Course Generator" menu option.

Enable UA 1.2.2.5 in the map:
![image](https://user-images.githubusercontent.com/11889733/192295099-3d32d630-460e-4c2b-9542-ad83085e6aa1.png)

Select a field in CoursePlay 7.1.0.4:
![image](https://user-images.githubusercontent.com/11889733/192295235-b7891249-fa1f-47ec-a0d8-23949b0ae65b.png)
The "Open/Close Course Generator" option is missing.

Disable the UA mod:
![image](https://user-images.githubusercontent.com/11889733/192295359-0b8834bc-1999-40dd-ba79-32b400481abd.png)

CoursePlay presents the "Open/Close" option:
![image](https://user-images.githubusercontent.com/11889733/192295429-139fc31d-c815-47b6-8144-ae5a06a67b48.png)

There is a bug noted in CP [#1925](https://github.com/Courseplay/Courseplay_FS22/issues/1925) about this, and it seems they've got  a fix in the works, but it does also seem to be impacted by UA, as well.

This does seem to be equipment specific. The CP bug indicates an issue with CustomModding mods. I do _not_ have the issue when using a base-game tractor & slurry spreader, but do have the issue with a Siid Modding John Deere X9 combine and the Custom Modding 60' Honey Bee header.

**Comment by loki79uk** [comment]
I can reproduce this exactly as you said with the `Siid Modding John Deere X9`.  There is nothing different in the log vs base game harvesters that do work, and it still happens with an old version of UAL (1.2.1.0 from before CP compatibility was a thing).  It seems like maybe CP thinks these vehicles have UAL installed when they don't, but I will wait for the next release of CP before investigating any further.

**Comment by loki79uk** [comment]
As mentioned on Discord - I have pushed v1.2.2.6 without really testing it.  It seems fine in SP, but I'm pretty sure I have just broken the synchronisation in MP.  If anyone has time to test it in MP that would be great!

**Comment by loki79uk** [comment]
Okay, it is a bit of a mess, but I think this latest commit should be compatible with either CP v7.1.0.4 or v7.1.0.5 - but now I need to do a load of MP testing to check that I have not broken anything else.  I won't make an actual release to save any further confusion, but if anyone can do some MP testing then please contact me on Discord!

**Comment by loki79uk** [comment]
This is fixed in CP after [v7.1.1.0](https://github.com/Courseplay/Courseplay_FS22/releases/tag/7.1.1.0) anyway, but next release of UAL is tested as working with either.  Thanks for your help in reporting this, and also for all the help with testing!
