### ISSUE TITLE
Missing l10n tr xml

### ISSUE THREAD

**Issue by RedBeard54** [loki79uk/FS22_UniversalAutoload#106]
I am playing with Turkish language but there arent any text on the hub. I did try some thing for fix this status but ı couldnt can you fix this

**Comment by loki79uk** [comment]
Hi, if you could add the Turkish language to the Moddesc, then I will include it in the next version.  https://github.com/loki79uk/FS22_UniversalAutoload/blob/main/modDesc.xml

One day I will split the languages out in to separate files, but I find it easier to maintain with all the languages grouped together, instead of needing to add new entries into a lot of different files.

**Comment by talhaonogul** [comment]
I aggre with you about maintain with all the languages look good and understandable . By the way maybe you can pick a main languages. For example you dont have Turkish but also it can be English in every unsupported language. Other side still  ı am going to try add Turkish Language.

**Comment by talhaonogul** [comment]
ı already translated everyting and add xml file but it is on my pc . How can ı share with you ? Can ı add myself with you gived to me link

**Comment by RedBeard54** [comment]
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<modDesc descVersion="67">

    <author>loki_79</author>
    <version>1.2.2.16</version>
	
    <title>
        <en>Universal Autoload</en>
		
		<fr>Autoload Universel</fr>
		<ru>Универсальная Автозагрузка</ru>
		<nl>Universele Autoload</nl>
		<cz>Univerzální Autoload</cz>
		<pl>Universalne Autoładowanie</pl>
		<es>Autoload Universal</es>
		<br>Carregamento Automático Universal</br>
		<cs>通用自动装载</cs>
                <tr>Evrensel Otomatik Yükleme</tr>

    </title>

**Comment by RedBeard54** [comment]
ı forget add this. ı am sorry about it . This is my first translation

**Comment by loki79uk** [comment]
> ı already translated everyting and add xml file but it is on my pc . How can ı share with you ? Can ı add myself with you gived to me link

Are you allowed to attach files to messages here?  If not, you can use any file sharing platform that you prefer, or send to me on Discord.  Loki_79#2864

**Comment by RedBeard54** [comment]
I dont know . I have never use here before so ı will send on discord

**Comment by loki79uk** [comment]
Turkish translations are now included in the [latest release](https://github.com/loki79uk/FS22_UniversalAutoload/releases).  Confirmed working via Discord, so closing now.
