### ISSUE TITLE
cutting

### ISSUE THREAD

**Issue by xXDorfkindXx** [loki79uk/FS22_UniversalAutoload#107]
Hi loki79uk
There is a problem with your mod when the mod is activated
If no cutting units are fixed on the cutting unit wagon, the mod is deactivated again, all cutting units are fixed again.

sry for my english.

**Comment by loki79uk** [comment]
I think this may be fixed with the latest release: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.2.17

Can you please test and let me know.  If not, please give steps to reproduce, i.e. exactly which vehicles to purchase.

**Comment by xXDorfkindXx** [comment]
Ok I'll test it and let you know if everything works again or not.

**Comment by xXDorfkindXx** [comment]
> I think this may be fixed with the latest release: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.2.17
> 
> Can you please test and let me know. If not, please give steps to reproduce, i.e. exactly which vehicles to purchase.

Hi loki79uk
everything works again, but I only tested the standard cutting units + trailer.

**Comment by loki79uk** [comment]
Okay great - I will close this issue, but please don't hesitate to re-open or start a new issue if you find any problems.

**Comment by loki79uk** [comment]
I had to partially revert this fix, as it caused another issue.  Could you please let me know if the cutter issue is still fixed with the new version: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.3.3

**Comment by xXDorfkindXx** [comment]
> I had to partially revert this fix, as it caused another issue. Could you please let me know if the cutter issue is still fixed with the new version: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.3.3

Hi
everything still works.

**Comment by loki79uk** [comment]
> Hi everything still works.

Great news - thank you for testing again!
