### ISSUE TITLE
Question: visibility of unloading zone

### ISSUE THREAD

**Issue by meda22** [loki79uk/FS22_UniversalAutoload#109]
First, thanks for a great mod!

But I am wondering if it is possible to make visible an unloading zone in some way? So I could see where precisely is cargo to be placed when unloaded. And if it is not possible now, is there any plan to add this feature?

**Comment by loki79uk** [comment]
There is already an unloading display if you press 'shift-F12' it will show an outline of where the items will unload:
![image](https://user-images.githubusercontent.com/76516343/196005587-e6f18cf5-5af9-4d48-99b2-05b523014eb9.png)

**Comment by meda22** [comment]
Great, thanks for info! I totally missed that :)
