### ISSUE TITLE
I10_da translation

### ISSUE THREAD

**Issue by Michaelbjerg21978** [loki79uk/FS22_UniversalAutoload#113]
I have translated it to danish, hope you will use it. best regards Michael
[l10n_da.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/9854845/l10n_da.zip)

**Comment by loki79uk** [comment]
Hi, thank you for this.  I have added it to the main repository in [this commit](https://github.com/loki79uk/FS22_UniversalAutoload/commit/e977736673f25776fcba9621cbf7dd070f71e56b).  It will be included in the next release!
