### ISSUE TITLE
bales physics connect two bales

### ISSUE THREAD

**Issue by DrewCZ** [loki79uk/FS22_UniversalAutoload#114]
Typically when trying to load round bales, UAL picks up a bale from clamps and moves it onto the trailer. As expected. Then I can pick up the second bale from the ground and move with the loader next to the trailer. But when I enter the area of UAL pick up, that first bale on the trailer is "connected" with the second bale. From this moment, it moves together and I'm unable to drop the second bale. 
Observed also on game v. 1.7.1, after the update to 1.8.1 remains the same
UAL v. 1.2.3.6 (maybe also on 1.2.3.4 used before? not sure)

![obrazek](https://user-images.githubusercontent.com/26751314/198984086-32dc1495-1864-4199-8edf-f8ecb5f015d6.png)

thank you. ticho / drewCZ

**Comment by loki79uk** [comment]
UAL shouldn't load bales if they are alredy mounted to another vehicle.  The reason is that the same kind of weird things happen if bales are loaded directly from the autostackers, packers, etc (e.g. Arcusin).  Maybe these bales are mounted in a different way?

Are you able to reproduce the issue with the first default telehandler (Schaffer 4670T) and Magsi bale handler?

![image](https://user-images.githubusercontent.com/76516343/199081966-562e40da-2ca5-4a97-8c1a-f9fc0b2bc1ae.png)

**Comment by loki79uk** [comment]
Can you write clear steps to reproduce this?  Maybe I have misunderstood, but I can't reproduce it (at least not with the vehicles in my screenshot).

**Comment by DrewCZ** [comment]
Hi, of course: 
custom map FS22_Upper_Bavaria_SP
custom skid loader by BlackSheep MF711
ingame graple Palladin for skidsteers
on farm I have few bales, different kinds
trailer D83 Tipper from pack FS22_lizardTrailerPack.zip; configuration 8
bale area definition custom in ...\My Games\FarmingSimulator2022\modSettings\UniversalAutoload.xml
``        <vehicleConfiguration configFileName="FS22_lizardTrailerPack/lizardD83K.xml" selectedConfigs="7,8">
            <loadingArea offset="0 1.68 0" width="3" height="2.20" length="6.2" baleHeight="3.50"/>
            <options enableSideLoading="true" horizontalLoading="true"/>
        </vehicleConfiguration>
``
here we go> 
bale collect mode turn on
1st bale with loader moved near to trailer, bale collected; ok
![obrazek](https://user-images.githubusercontent.com/26751314/200042174-5f0c91d9-cc8b-4c07-a5e7-3abc548fb524.png)

2nd round, when bale is in touch with grapples, whole loader wobble and physics is weird; anyway is loaded onto the trailer
![obrazek](https://user-images.githubusercontent.com/26751314/200042116-77eba4ee-451c-4e5c-8b31-c43c83e9fc97.png)


then trailer moved near to rest of bales, all loaded
not enough, few bales added using console; all possible bales loaded; trailer is reporting full plate
manual remove back two strapes for manual load bales on the back of trailer
![obrazek](https://user-images.githubusercontent.com/26751314/200042016-24dbd515-b0c4-4025-b70b-407df1d7acce.png)


when bale near trailer (right back behind the trailer, but without touch) is taken by loader, then physics is "connected" visible to the trailer
![obrazek](https://user-images.githubusercontent.com/26751314/200041692-980e5f46-aeca-4cae-8aef-f1811bbf8efa.png)

then is possible to "tow" loader. 
![obrazek](https://user-images.githubusercontent.com/26751314/200040665-8e07c555-f6ca-45f7-990e-ebb3a8759b58.png)


same, if trailer is not fully loaded and empty space for a bale remains; in this case is bale on the ground "coupled" with one or two bales on the trailer.

In the log file an error appears, but I don't analyse it. The log is attached here. 
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/9940913/log.txt)

**Comment by loki79uk** [comment]
Okay, thanks, I'll look now.  I think that bale collection mode is the thing I was missing!

**Comment by loki79uk** [comment]
I've got it working!  Fix incoming.  (give me about 30 minutes)
![image](https://user-images.githubusercontent.com/76516343/200068171-d8b8e5c2-281c-4087-9b46-ef9c3b157679.png)

**Comment by loki79uk** [comment]
Should be working now in: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.3.8

Thank you for the thorough bug report - it is very much appreciated!

**Comment by DrewCZ** [comment]
I love this mod and be glad to small help with improving :) 
Thank you very much for your work and very quick response!
