### ISSUE TITLE
Adding a new bale type

### ISSUE THREAD

**Issue by cwhandersen** [loki79uk/FS22_UniversalAutoload#116]
I tried adding a new bale type to the mod. And it mostly works. But it seems to want to make a weird gap of bales.
So how would I go about and do this correctly?

Reference photo attached.

![2022-11-03 15_48_05-Window](https://user-images.githubusercontent.com/92727147/199754223-4687f06c-c186-4d78-b455-0b3dfca84e61.png)

**Comment by loki79uk** [comment]
Hi - if you press `shift-F12` then you should see green boxes around the bales (when they are in range of an active UAL trailer).  You need to adjust the dimensions until the boxes are just bigger than the bales.  You can use the console command `ualImportUserConfigurations` to update the box size without reloading the game.

**Comment by cwhandersen** [comment]
I tried it. But the green box doesn't seem to change size no matter what i set it to. 
The console command doesn't work for me. So I just reloaded the game and changed the values.
I even tried making the values much larger just to see a difference.

The bale is 1.20 - 1.30 - 2.40 and the attached photo is with the values set to 1.30 - 1.40 - 2.40
The green box just stays where it is.


![Untitled](https://user-images.githubusercontent.com/92727147/199931381-01815f80-a52c-4753-afe2-09aff08d3759.png)

**Comment by loki79uk** [comment]
What do you mean that the bale is 1.20 - 1.30 - 2.40?  If those are the values in the xml, they are most probably wrong.  But by default UAL will use the values from the xml anyway.

However, if you are changing the values and it is not reloading, then you are not setting th values correctly.  Can you please attach your local mod settings file, and a log file.

**Comment by cwhandersen** [comment]
From what I could see from the baler, those are the values the bale has.

[files.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/9937229/files.zip)

**Comment by cwhandersen** [comment]
Absolutely fantastic mod btw. It is truly the best possible autoload mod for the game. 
Thanks for the great work.

**Comment by loki79uk** [comment]
You need to add the mod that the bale is from as well, in the format `FS22_mod:objectName`.

I can't see where the game is actually loading "bigsquarebale240", but you are using e.g. "squarebaleHesston240"
so you need to use e.g.:
```
    <containerConfigurations>
		<containerConfiguration containerType="BALE" name="FS22_Hesston4900:squarebaleHesston180" sizeX="1.210" sizeY="1.310" sizeZ="1.80"/>
		<containerConfiguration containerType="BALE" name="FS22_Hesston4900:squarebaleHesston220" sizeX="1.210" sizeY="1.310" sizeZ="2.20"/>
		<containerConfiguration containerType="BALE" name="FS22_Hesston4900:squarebaleHesston240" sizeX="1.210" sizeY="1.310" sizeZ="2.40"/>
    </containerConfigurations>
```

**Comment by cwhandersen** [comment]
Ahh okay. Thanks for the help
