### ISSUE TITLE
Turkish language

### ISSUE THREAD

**Issue by RedBeard54** [loki79uk/FS22_UniversalAutoload#117]
Turkish language gone  after last update

**Comment by loki79uk** [comment]
That is weird?  The file is still there unchanged:
https://github.com/loki79uk/FS22_UniversalAutoload/blob/main/language/l10n_tr.xml

**Comment by RedBeard54** [comment]
ı checked again the files but there is no language file

**Comment by RedBeard54** [comment]
<version>1.2.1.0</version> ı dont wyh ı have old version after update

**Comment by loki79uk** [comment]
It sounds like the game downgraded your version to 1.2.1.0.   The game will suggest to "update", even when the installed version is newer than the ModHub version.

**Comment by loki79uk** [comment]
Did updating to the latest UAL version again fix this?

**Comment by loki79uk** [comment]
I think this is probably due to a mistaken "update" the old version from the in game ModHub.
