### ISSUE TITLE
Price Per Pallet

### ISSUE THREAD

**Issue by Jayshua83** [loki79uk/FS22_UniversalAutoload#118]
Couple things...

Can we get multiple options like PricePerPallet and PricePerBale?

Also is it possible to have it show up as an alert to money change like most other mods do when changing money? I ma NOt seeing it say like MISC -$50 or whatever.

**Comment by loki79uk** [comment]
I could definitely add a price per log and price per bale.  Maybe do logs proportional to the mass?

The tricky bit with displaying the cost, is how often should it display?  The amount you have spent every minute, every item, every 10 seconds?  It could end up being too long or too short depending how fast you are loading, and it could get annoying if it is spamming a message for every pallet?  I'm open to suggestions as I don't even use that feature! :D

**Comment by loki79uk** [comment]
I just chekced quickly before work, and there is an option to display a message per transaction:
![image](https://user-images.githubusercontent.com/76516343/200522842-daa7c35a-bf7b-4629-8ce9-fdd445d64e4c.png)

**Comment by ddewar** [comment]
My personal vote is for one per pallet so you can see the price difference between bale and pallet. But that's just my gut reaction. 😉

**Comment by loki79uk** [comment]
I went with the display per pallet/bale/log because it was easier!  Try it and see what you think: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.3.9

**Comment by loki79uk** [comment]
I think this can be closed now - I've added the three options, and tested as working in SP and on dedi.  Re-open or message me on discord if you have any issues with it at all.
