### ISSUE TITLE
L10n missing

### ISSUE THREAD

**Issue by Menno58** [loki79uk/FS22_UniversalAutoload#12]
In the F1 menu I don't see what any of the buttons do I only see missing UniversalAutoload_loadingFilter in l10n_nl.xml: Missing UniversalAutoload_enabled in (it stops here, likely says l10n_nl.xml as well). 
I think it has something to do with language settings since I am Dutch I have my language set to Dutch and I get the missing text, when I change my language to English it goes away and the text is normal. 
I think because some of the text is taken from the ingame files (example when outside using L for all the tension belts)  it expects that the rest of the text is also in Dutch (I don't think it is just the dutch language btw just any language that is not in the moddesc)
I understand that you don't want to translate the text into every laguage but isn't there a way to make it English if the translation isn't available?

PS: it still is a  fantastic mod

**Comment by loki79uk** [comment]
Hi, yes this is my fault for not doing a complete set of translations.  If you can do the Dutch translations for all of the entries in the moddesc, I can certainly add them.

**Comment by Menno58** [comment]
Hi, I have just finished translating the l10n into Dutch. Because of github it is a .txt file but you should be able to copy it into a .xml file
[modDesc.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/8147006/modDesc.txt)

**Comment by Menno58** [comment]
Hi, I have just finished translating the l10n into Dutch. Because of github it is a .txt file but you should be able to copy it into a .xml file
[modDesc.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/8147032/modDesc.txt)

**Comment by loki79uk** [comment]
I have added this to the latest release (005), please check that everything works in game - as I copied and pasted your text rather than risk a merge commit.

**Comment by Menno58** [comment]
Perfect!!! everything seems to be working as it should 👍
