### ISSUE TITLE
Typo in README.txt

### ISSUE THREAD

**Issue by LonelyHowl** [loki79uk/FS22_UniversalAutoload#121]
@ Supported ~~Vehciles~~: Vehicles

**Comment by loki79uk** [comment]
Thanks - this is one of the words that I ALWAYS mistype!  Maybe because it is in capitals, NP++ did not highlight it with the spell check: 
![image](https://user-images.githubusercontent.com/76516343/201541469-37431c5e-de18-4fa1-ba67-a4953cfa590a.png)

**Comment by loki79uk** [comment]
https://github.com/loki79uk/FS22_UniversalAutoload/commit/01adf151145f236a0ab92212e7ad1ea726a52708
