### ISSUE TITLE
add information

### ISSUE THREAD

**Issue by sofr-oleg** [loki79uk/FS22_UniversalAutoload#122]
add information about the length of the log in the description
![fsScreen](https://user-images.githubusercontent.com/118161574/201607613-6a291f95-1122-4490-a2ae-59d195344021.png)

**Comment by loki79uk** [comment]
Good idea - I will look at adding this before the next ModHub release.

**Comment by loki79uk** [comment]
Hi, I have added this in the latest version - thanks for the idea!
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.4.1
