### ISSUE TITLE
Platinum DLC logs are only loaded on a single raw

### ISSUE THREAD

**Issue by romelec** [loki79uk/FS22_UniversalAutoload#125]
The new trees added in the platinum DLC are loaded in a single raw, as if their height was not recognized. There is no error/useful informations in the log after activating the 3 _local debug..._ flags.

It is tested on the main branch with 6 meters lodgepole pines (did not test the other ones yet) on the small Schwarzmuller trailer and Fliegl timber runner

![log_single_raw](https://user-images.githubusercontent.com/20406897/201909224-9f448a14-7d9f-4e9f-88cc-cba4bcb451b9.png)

Let me know if I can help, I have the remote debugger but I'm not sure where to look/put breakpoints or print.

**Comment by sofr-oleg** [comment]
how to download 4m * 3 ? loading just like that 4m*2
![2022-11-16_00-06-36](https://user-images.githubusercontent.com/118161574/202025020-acde72d9-9836-4079-a7b2-1689b6a7c66a.png)

**Comment by loki79uk** [comment]
You need a 0.25m gap between each bunk, so for 3x 4m you actually need 12.5m of space, plus a bit of extra room for movement.

I'm just looking at the first one now.

**Comment by loki79uk** [comment]
I'm not sure which version you are on, but my latest one works for me with 6m lodgepole pines on both.  I'll release it soon:
![image](https://user-images.githubusercontent.com/76516343/202042504-08d5caac-9ac6-49bb-8264-5f5c130130f5.png)

**Comment by romelec** [comment]
Its fine with the v1.2.4.0 release
