### ISSUE TITLE
Forwarder, Container issue

### ISSUE THREAD

**Issue by jufcar** [loki79uk/FS22_UniversalAutoload#126]
With the new DLC i switched from achii's autoload to yours, simply because it works fantastic with vanilla equipment, trains and logs without the need to change something on the modell itself, thats some great work you did there.

Going into forestry i noticed two things:
1. the forwarder (Komatsu 875, Ponse Bison, Rottne F20D) seem to load the logs to low. I fiddled around with your values a bit and it worked well enough for me, when i moved the "loading cube" above the horizontal bars. My guess is, you changed the loading behavior from center loading, where the first logs would fall into the center gap on these types of vehicles, to loading from one side to the other. This way the logs land on the wheels and will be strapped there.

These are my current values, be arware, i changed the length to around 6m to match the small container size: 
```
	<vehicleConfiguration configFileName="data/vehicles/komatsu/forwarder875/forwarder875.xml">  
		<loadingArea offset="0.0 1.9 -4.2" width="2.6" height="2.0" length="6.2"/>
		<options isLogTrailer="true"/>
	</vehicleConfiguration>
	<vehicleConfiguration configFileName="data/vehicles/ponsse/bison/bison.xml">  
		<loadingArea offset="0.0 1.955 -3.7" width="2.5" height="2.0" length="6.2"/>
		<options isLogTrailer="true"/>
	</vehicleConfiguration>
	<vehicleConfiguration configFileName="data/vehicles/rottne/f20D/f20D.xml">  
		<loadingArea offset="0.0 2.2 -4.5" width="4.2" height="1.5" length="6.2"/>
		<options isLogTrailer="true" noLoadingIfFolded="true"/>
	</vehicleConfiguration>
```

2. the feature to load and unload containers seems to have conflict with the "fixating feature" of the Schwarzmüller Tieflader 3A. Most of the times i tried to unload the 2 6m containers (20ft container) only one will be unloaded, while the others sits fixed on the trailer and i have to use the wheelloader to get it loose.

**Comment by loki79uk** [comment]
I've been working on the "snap-to" conflict today.  I'm not quite ready to release it yet, but I think I've mostly fixed that issue now.

I will check the other trailers with your settings and the new ones too.  I did most of the news ones by eye and not tested them much yet!  Thanks for the help, obvious now that you mention it - you are right, I forgot to test the original ones now that it starts loading lower down.  Originally it was only from the top, but then on tall trailers the logs were bouncing all over the place when they landed!

I'm out this evening, but I'll have some time to look at it later.

**Comment by loki79uk** [comment]
I ran out of time yesterday to test these.  I will look properly this evening, but I just pushed out my latest dev version anyway because of another issue.  I may still tweak them after testing, but currently using your values from above.
