### ISSUE TITLE
Gamebreaking lua Error

### ISSUE THREAD

**Issue by JukeStuff** [loki79uk/FS22_UniversalAutoload#127]
Hey i've been really liking the implementation of the log autoload with this mod, but when i tried to autoload a log pile on Silverrun with the Old Volvo FH and the Long swarzmuller trailer the game fully froze and i got this Error 
![image](https://user-images.githubusercontent.com/113805245/202876897-7ed6e8c4-f66f-47a0-9b6f-e99027ac34d3.png)

**Comment by loki79uk** [comment]
Hi, could please try the latest release and see if this has fixed it: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.4.4

**Comment by loki79uk** [comment]
I did some debugging and pretty sure this is fixed now.  The issue should have only happened when buying a vehicle, not for any alreday existing.   This has caught me out before, `onLoad()` is called every time, but `onPostLoad()` is only called when loading from a savegame!

**Comment by JukeStuff** [comment]
Just got to trying it on the same save and yeah did things the same way and now it works perfectly fine :) Thank you for the quick help.
