### ISSUE TITLE
UAL logging

### ISSUE THREAD

**Issue by judg393** [loki79uk/FS22_UniversalAutoload#131]
Hey Loki I've just added UAL to a mod I'm tweaking following your amazingingly easy guide using cubes ect. How do I then add UAL trees? 

Hope that makes sense

**Comment by loki79uk** [comment]
You just need to use the option: `<options isLogTrailer="true"/>`
Have a look at any of the base game logging trailers for examples.

**Comment by judg393** [comment]
Thank you I'll take a look
