### ISSUE TITLE
Pfanzelt P13 4272

### ISSUE THREAD

**Issue by N820RS** [loki79uk/FS22_UniversalAutoload#135]
Cannot load logs when configured for the crane or just the standalone trailer.  When unfolded or not.  
Love the mod, btw.

**Comment by loki79uk** [comment]
How long are the logs that you are trying to load?  They need to be under 4.5m.  Aim for 4m if you can to be safe.

I had missed that there is a log trailer config though, I will add the two different configs for the next version.

![image](https://user-images.githubusercontent.com/76516343/205002380-e4958edb-a8a6-4d08-b043-608f91baba04.png)

**Comment by N820RS** [comment]
The log length was the problem!  I missed that completely, ha.  

Thank you for the reply!

**Comment by loki79uk** [comment]
I have fixed the gap when there is no crane, and now both loading zones extend with the trailer:
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.0.1

**Comment by N820RS** [comment]
![Untitled](https://user-images.githubusercontent.com/119560172/205220299-f2872d23-ebf2-4147-aaa8-55b2b5dea6b7.png)

Works beautifully.  Perfect for 6m logs.  

Appreciate your work!
