### ISSUE TITLE
Traile wont load big bags

### ISSUE THREAD

**Issue by bojanh66** [loki79uk/FS22_UniversalAutoload#136]
Hello, i hope to get your help.
I posted this issue:
https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/issues/47

I dont know what could went wrong.
I have tried older versions of UA and UA Addon from Modhub, but still doesnt work.
My game is updated to the latest version.

This trailer can load pallets, bales, but suddenly wont load big bags.
Log txt doesnt show any error.

If i could help somehow with more info, pls let me know.

**Comment by loki79uk** [comment]
I know you have the workaround with the local settings, but you should be able to go back to the standard configuration using this new release: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.0.3
