### ISSUE TITLE
[Help] Make mods compatible with Universal Autoload

### ISSUE THREAD

**Issue by Myiamoto86** [loki79uk/FS22_UniversalAutoload#137]
[Help] Loki, good night. How long has it been... Buddy, I need your help. I tried to insert the code you provided to make a mod I use compatible with your mod, but it turned out really weird. Note: The mod I'm referring to is Randon LS.

https://farming-simulator.com/mod.php?lang=en&country=pt&mod_id=252488&title=fs2022

I don't know what I did wrong. I couldn't get it to work in automatic loading only in plancha or bale loader modes, and not activate when configured for bulk trailer.
Would you be able to help me?

**Comment by loki79uk** [comment]
By automatic, do you mean manual loading (from the forklift)?  For that you need to add the flags: `enableRearLoading="true"` and/or `enableSideLoading="true"`.  And to prevent the bulk trailer then you need to select the configs for the bale trailer (1, 2, 3)

I created some settings for you here:
```xml
		<vehicleConfiguration configFileName="FS22_RandonLS/4eixo.xml" selectedConfigs="1,2,3">
			<loadingArea offset="0 1.220 1.00" width="2.3" height="2.25" length="13.0" baleHeight="2.8"/>
			<options enableRearLoading="true" enableSideLoading="true"/>
		</vehicleConfiguration>
		<vehicleConfiguration configFileName="FS22_RandonLS/Vanderleia.xml" selectedConfigs="1,2,3">
			<loadingArea offset="0 1.212 1.00" width="2.3" height="2.25" length="13.0" baleHeight="2.8"/>
			<options enableRearLoading="true" enableSideLoading="true"/>
		</vehicleConfiguration>
```

**Comment by Myiamoto86** [comment]
Loki, good morning.

You are the best. Lol... Thank you.
