### ISSUE TITLE
Problems with the new version of Autodrive 2.0.0.9 - Routes with automatic loading route.

### ISSUE THREAD

**Issue by Myiamoto86** [loki79uk/FS22_UniversalAutoload#139]
Loki, good afternoon.

Today the new version of autodrive came out and when I set it up for automatic collection and delivery by autodrive, I can't select the product that will be collected. Wheat is marked, when FS22 is in Portuguese - BR. In version 2.0.0.7 it was working.

Hugs.

**Comment by loki79uk** [comment]
I certainly need to spend some time on Autodrive compatability.  I could use some help with someone who can set up some test games to identify issues and test solutions.   I have not really used AD since FS19 because I am always doing mods and not actually playing the game!

For this issue, it may be helpful to zip up your savegame so that I can reproduce it here.

**Comment by Myiamoto86** [comment]
Loki, good night...

I use autodrive a lot and I can help with testing... I end up spending more time testing and translating mods than playing.

The map that I detected this problem was Bacuri 2k22. (Mod BR). This game has several mods downloaded via an external link and may be a problem for you. I'm going to create a new game with mods from modhub so I don't have a headache... For some reason, my saves are too big. I may have to provide access via the cloud. (google drive, one drive and etc.). If this is really the case, send your e-mail so I can release access just for you to access.
About the map, do you have any preference? Or could it be some of my usage?

Obs.: Mods such as autodrive itself, course play, better contracts and its UAL, I always update through an external link on Github or links provided by the developer itself.

**Comment by loki79uk** [comment]
Maybe easiest to coordinate via Discord - Loki_79#2864
The minimum required mods to reproduce would be best for me, on a standard map if possible.  I think the thing I need most is the same autodrive route, and a vehicle in the right position where it works in 2.0.0.7, but not 2.0.0.9.  Share however is easiest for you - google drive, dropbox, etc

**Comment by Myiamoto86** [comment]
Loki,

I already added you on discord. I'm going to set up a test game and simulate with both versions of the auto drive... once everything is finished, I'll send you the files.

**Comment by Myiamoto86** [comment]
Loki,

Good afternoon.

Pardon. But the problem I reported in the open call for you, may have occurred due to some very crazy bug on my PC, because the Autodrive team reported that there was never any compatibility with your mod.

Obs. At two different times, first on July 22 and the other after the Volvo DLC came out, I used your mod along with the aPalletAutoLoader mod. There was probably a problem when I made simultaneous use of both mods, making it possible to select the types of loading in the auto drive collection and delivery function in trailers that did not have the autoloader function.

However, someday it would be very interesting to see your mod working with Autodrive. If you want one of the game's default maps, I have the routes configured and the points of sale mapped. I can find a way to extract that information to send it to you. This will speed up this job.

If there's any map you prefer, let me know. I make the autodrive routes and send them to you.

Hugs and sorry for the inconvenience.

**Comment by loki79uk** [comment]
Not inconvenient at all, thanks for the help.  I have been planning to add AutoDrive support for quite a while, but there is always some more pressing issue with autoload that needs attention first.  It would be great if you can help me set up a test map and to give advice on how it should work.

**Comment by Myiamoto86** [comment]
Hello Loki.

Leave it alone... I'll configure routes in a standard map of the game to serve as a base... I'll send you the file saved by autodrive only, and I'll pass on the details of how to configure it. This way, I can send a very small file. About the language, I'll have to insert some markers. Prefer that I insert these markers in which language? If I put it in my native, it will waste a little time.

About the map, do you have a preference for any? I can configure the routes in what I think is best for the tests.

**Comment by loki79uk** [comment]
UAL should now be compatible with the next release of AD. You can try it out with the latest dev version already:
https://github.com/Stephan-S/FS22_AutoDrive/tree/dev_axel32019
