### ISSUE TITLE
Metal pallets only autoload when 'loading filter any' is applied.

### ISSUE THREAD

**Issue by MFxSE7EN** [loki79uk/FS22_UniversalAutoload#140]
The metal pallets from the Iron Furnace seem like they are not registering as 'full' by autoload. I have tried it with a few different trailers with the same result. Using modhub version 1.3.0.0.

**Comment by loki79uk** [comment]
That is odd, maybe a rounding error.  Metal pallets that are spawned with the console commands can be loaded with the 'full' filter active.  I'll have to make a savegame using the real production to check.

**Comment by loki79uk** [comment]
I can't reproduce this - I built an iron furnace, created some pallets, and they load with either "full only" or "any".  What is your timescale set to?
![image](https://user-images.githubusercontent.com/76516343/208506351-2c4c3720-53bf-44b0-bd18-71abd5226280.png)
If you look at the pallets do they say "1000 pieces"
![image](https://user-images.githubusercontent.com/76516343/208506417-67a4d762-2779-431c-835a-4fdd0707ff64.png)

**Comment by MFxSE7EN** [comment]
I did some digging around, the problem is caused by using the vanilla game option of 'trailer weight limit' (where trailers have a maximum fill weight in addition to volume). This seems to affect some other things also, including the metal pallets. They have a count of 160 instead of 1000 with this option enabled. Disabling it gave me correct pallet size of 1000. I don't know if this is something that can be fixed so a metal pallet with exactly 160 pieces would be considered full or something but thank you for taking the time to check the issue.

**Comment by loki79uk** [comment]
Okay, I confirmed that.  Set `Trailer Fill Limit = ON` in the menu and new pallets spawn with 160 pieces:
![image](https://user-images.githubusercontent.com/76516343/208606864-63cd38e0-ba06-4ed0-b05a-a2e9ea298c22.png)

I had a quick look to see if there is anything obviously different in the pallet compared to a 1000 one (apart from the fill amount), but couldn't see anything in the LUA tables (printed out to the first depth only).  Can you check if they sell for the same amount, or is it actually just a partially full pallet?

**Comment by MFxSE7EN** [comment]
They sell for significantly less when Trailer Fill Limit is on. For a pack of 8 I got about 4000, and about 5 times that much when it is disabled.

**Comment by loki79uk** [comment]
In that case, it seems like either a bug or actual intended behaviour from GIANTS.  Do you agree that the setting just makes those heavy pallets "less" full when they are produced?

**Comment by MFxSE7EN** [comment]
Yeah, it is probably because they consider metal to be heavy compared to something like wood, etc. as I haven't noticed it with other products. I only have the barrel and wood turner though so there might be more.
