### ISSUE TITLE
Wont load 150cm bales from MultiBaler M+ mod

### ISSUE THREAD

**Issue by bojanh66** [loki79uk/FS22_UniversalAutoload#143]
I use this baler for Maize Plus TMR bales and trailers wont load bales from this baler.
https://cdn.discordapp.com/attachments/874208329818329129/1024593157939281980/FS22_Poettinger_200VCProMultiBaler_Mplus.zip

This is the error i get:
2022-12-16 11:09 *** UNIVERSAL AUTOLOAD - importUnknownSpecFromExisting: FS22_Poettinger_200VCProMultiBaler_Mplus:CM_roundbale150 ***
2022-12-16 11:09 *** UNIVERSAL AUTOLOAD - UNKNOWN OBJECT TYPE: FS22_Poettinger_200VCProMultiBaler_Mplus:CM_roundbale150 ***

**Comment by loki79uk** [comment]
Have you tried to add a configuration for that mod?

The `importUnknownSpecFromExisting` function only works if the bale i3d name already exists in the base game, but I could improve the search to see if it exists for other mods as well.   I had not anticipated this situation where a mod uses it's own version of the containers from another mod.

You can try adding these settings to your local settings file:
```xml
    <containerConfigurations>
        <containerConfiguration containerType="BALE" name="FS22_Poettinger_200VCProMultiBaler_Mplus:CM_roundbale125" sizeX="1.300" sizeY="1.20" sizeZ="1.300" isRoundbale="true" flipYZ="true"/>
        <containerConfiguration containerType="BALE" name="FS22_Poettinger_200VCProMultiBaler_Mplus:CM_roundbale150" sizeX="1.560" sizeY="1.20" sizeZ="1.560" isRoundbale="true" flipYZ="true"/>
    </containerConfigurations>
```
And depending on how the objects are defined, you may also need to add
```xml
    <objectTypes>
        <objectType name="FS22_Poettinger_200VCProMultiBaler_Mplus:CM_rroundbale125"/>
        <objectType name="FS22_Poettinger_200VCProMultiBaler_Mplus:CM_roundbale150"/>
    </objectTypes>
```

**Comment by loki79uk** [comment]
Did this configuration work for you?

**Comment by bojanh66** [comment]
Sorry for late reply, i have totally forgot.
Yes, it did work :), thanks for your help.
