### ISSUE TITLE
Furniture Pallets Glitching

### ISSUE THREAD

**Issue by Jayshua83** [loki79uk/FS22_UniversalAutoload#144]
We are having an odd issue with Furniture Pallets. 

The first layer load fine but when it starts to load a second layer it just throws them in between existing pallets and makes a jumble mess of everything!

**Comment by Jayshua83** [comment]
This happens with layers turn on it seems but NOT stacking.

**Comment by loki79uk** [comment]
Thanks - it seems that something similar happens for all pallets, but furniture pallets are worse.  Looks like it was introduced between `1.3.0.0` and `1.3.0.3', I'll compare them and see what I broke!

**Comment by loki79uk** [comment]
It looks like it was the change in `1.3.0.3` to allow loading any height objects on the first layer.  I would go back to using `1.3.0.2` until the next release.

**Comment by loki79uk** [comment]
Actually, there are two issues here - I fixed the problem with the other pallets but there is still the problem with the furniture pallets.  It seems like furniture pallets are not detected by the overlapBox collision detection function.

**Comment by loki79uk** [comment]
So furniture pallets don't have a specific collision mask for the boxes:
![image](https://user-images.githubusercontent.com/76516343/208300384-32e20800-aa57-499d-b554-838a68131af3.png)

I can use any of these flags I think, but may be weird for partially full pallets:
![image](https://user-images.githubusercontent.com/76516343/208300437-e4abc007-ec59-4ec1-aba6-7be4a784351a.png)

**Comment by loki79uk** [comment]
Hopefully fixed now: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.0.4
