### ISSUE TITLE
After v1.3.0.3, a column appeared with the name of the supported trailer repeated ~100500 times

### ISSUE THREAD

**Issue by vitalii2011** [loki79uk/FS22_UniversalAutoload#145]
… when loading the game if the previous save was near the trailer so that its name is displayed in F1:
![0011](https://user-images.githubusercontent.com/41552153/208437380-3c458050-f7f4-4f4f-87ca-63f5c1c2e255.gif)

**Comment by vitalii2011** [comment]
- This calls InfoMessageHUD https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=225114&title=fs2022
(I did not manage to contact the author either with FS19, neither with me and Achimobil with FS22. Not responding: https://github.com/sperrgebiet)
- Recording in F1 from UA
![fsScreen_2022_12_19_21_29_36](https://user-images.githubusercontent.com/41552153/208496779-27007ebc-d425-4c0f-b23b-d08a0d8836af.png)
[FS22_InfoMessageHUD.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/10261860/FS22_InfoMessageHUD.zip)

**Comment by vitalii2011** [comment]
Sorry, let me once again draw your attention to the fact that before ~1.3.0.3 this was not the case.

**Comment by loki79uk** [comment]
Okay, that makes more sense, but it is still strange that it happens for you - I often use `info messge hud` as well, and I cannot reproduce it.

I stood here:
![image](https://user-images.githubusercontent.com/76516343/208507158-3c80d067-81e2-4931-9a7d-0deb3f083f1c.png)
Saved game and reloaded, and it works as expected after reloading:
![image](https://user-images.githubusercontent.com/76516343/208507775-79aa41d5-2d62-44c8-a2f6-5ed680f67fa1.png)

**Comment by loki79uk** [comment]
Acutally, I see now you need the save position mod as well, or put a trailer near the spawn point

**Comment by loki79uk** [comment]
I just rolled back to UAL `v1.3.0.0` and `v1.2.1.0` and it still happens for both, so I don't think this was introduced recently.  It seems like it is probably just the first time that you had a savegame with the F1 menu closed and also standing near a trailer and you were looking.  For me it flashes on the screen for less than half a second.

**Comment by vitalii2011** [comment]
So do I need to deprecate FS22_PlayerPositionSaver?

**Comment by loki79uk** [comment]
I wouldn't worry about it, just don't look at the screen immediately after loading.  I tried a few things to stop it happening, but none of them worked.  I'll let you know if I find anything that works too stop it.

**Comment by loki79uk** [comment]
This should work how you expect now: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.0.5

**Comment by vitalii2011** [comment]
There's nothing superfluous right now. Thanks.

**Comment by vitalii2011** [comment]
If I'm not mistaken, you wrote somewhere that there are problems with the mod that saves the player's position. Or am I confusing something?

**Comment by loki79uk** [comment]
Not a conflict, just that spawning near a trailer was required to see the text appear, so it could only happen with a trailer near the spawn point or when using that mod.

**Comment by vitalii2011** [comment]
No-no, it's not about what was decided in this issue. Something about tables in fashion to save position. Maybe you wrote about it in Discord. Or maybe not you. )
I just remembered that in addition to the FS22_PlayerPositionSaver I use, I have FS22_savePlayerPosition and maybe it does not create such problems as PlayerPositionSaver. 
[FS22_PlayerPositionSaver.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/10271360/FS22_PlayerPositionSaver.zip)
[FS22_savePlayerPosition.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/10271361/FS22_savePlayerPosition.zip)

**Comment by loki79uk** [comment]
Ah okay, I don't think that was me.  I don't remember it anyway.
