### ISSUE TITLE
 Multiple zones for timber on timber trailer

### ISSUE THREAD

**Issue by PellaR** [loki79uk/FS22_UniversalAutoload#146]
Hi. I’m trying to sett up multible zones for timber on a trailer, so i can load 2 stacks of 5/6 meter logs. But i can only fill the zones halfway ful,l before i get the message that the trailer is full. Any suggiestions on how to get this to work?

**Comment by loki79uk** [comment]
As long as you make a single zone greater than 2x a length +0.25, then it will stack both together.  E.g. 12.25m will allow two bunks of 6m logs.  This has the advantage of also loading 12m logs.

If you really want two separate zones, try separating them further apart.  Send me the settings you are using and I'll see if I can figure it out.

**Comment by PellaR** [comment]
here is my settings:
<vehicleConfiguration configFileName="FS22_Timber_Runner_Pack/xml/timberRunner.xml" modHubId="258564">     
			<loadingArea offset="0 1.666 3.15" width="2.37" height="3.75" length="5.1"/>
			<loadingArea offset="0 1.666 -3.15" width="2.37" height="3.75" length="5.1"/>
			      <options isLogTrailer="true" zonesOverlap="true"/>
        </vehicleConfiguration>

**Comment by PellaR** [comment]
but i will try your with one large zone also:)

**Comment by loki79uk** [comment]
I can't test anything right now as away from my pc, but for log trailers you can't have overlapping zones.  The `zonesOverlap = "true"` is intended to force the collision detection check when loading pallets.

Having said that, it seems like they don't overlap.  The total length is 10.2m and the spacing between centres is 6.3m.  It could be a collision with the trailer?  I'll check tomorrow.

**Comment by ddewar** [comment]
@loki79uk, just a heads up. I did try overlapping zones with logging trailers and it really seemed to not like it. I remember it only treating the last zone as the loading zone or something like that. I did include the overlap true as well. Not sure if logging trailers were ever intended to use it, but just wanted to let you know I was seeing this as well.

**Comment by loki79uk** [comment]
I found the issue - it was resetting the "layer height" between layers, so when returning to the first zone then it had forgotten all of the previous heights.  I think I have just never tested this, but I guess we need to watch out for issues with loading pallets on multiple zone trailers.

I've also added a new feature that will use the `zonesOverlap = "true"` for log trailers to always drop from full height.  I'll release it later today.

It works with the following settings together with the new version:
```xml
	<vehicleConfiguration configFileName="FS22_Timber_Runner_Pack/xml/timberRunner.xml" modHubId="258564">
		<loadingArea offset="0 1.685 2.95" width="2.27" height="2.35" length="6.1"/>
		<loadingArea offset="0 1.685 -3.25" width="2.27" height="2.35" length="6.1"/>
		<options isLogTrailer="true" zonesOverlap="true"/>
	</vehicleConfiguration> 
```
![image](https://user-images.githubusercontent.com/76516343/209821014-dbbce985-be7b-42c3-8869-dd7d6285abde.png)

**Comment by PellaR** [comment]
Thanks:)

**Comment by loki79uk** [comment]
Sorry, I ran out of time today, but I'll try to get a new version released tomorrow including this fix.

**Comment by loki79uk** [comment]
Sorry, I only just got around to this - has been a crazy fgew days IRL!
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.0.6

**Comment by PellaR** [comment]
thank you:)

**Comment by PellaR** [comment]
hi, just a quick question. is it possible to set a minimum lenght of the log?

**Comment by loki79uk** [comment]
> hi, just a quick question. is it possible to set a minimum lenght of the log?

No, there is no minimum length.  Mostly because it would require another display and more keys to be bound.

It will already load starting with the longest first, so you can just use the load key again to stop loading when all the logs you want are loaded.
