### ISSUE TITLE
Selling loaded bales directly from the trailer to a sellpoint will not reset the loading state

### ISSUE THREAD

**Issue by MrMarcel5** [loki79uk/FS22_UniversalAutoload#148]
Selling a fully loaded trailer with bales directly into a sellpoint will not reset the bale loading state for autoload.
This will cause the "loading area is full" message to appear when the user tries to load more bales onto it; while the trailer itself appears visually empty.

Issue occurs with manualLoading forced & as a client on a dedicated server.
Re-Joining the server will not fix the issue, so it seems that the state on server side is being broken; not the client messing up anything.
Resetting the trailer itself will likely fix this issue temporary, until the next selling.
Untested with Pallets; only tested & reproduced with bales.
![2023-01-11 12_55_56-Farming Simulator 22](https://user-images.githubusercontent.com/47321339/211800354-ba3429aa-82a0-4078-918e-eeed763a676b.jpg)

**Comment by loki79uk** [comment]
Thank you for reporting this - I don't use forced manual loading, so I would have never found it!

I had a dedi server for testing (very kindly donated to me), but it expired recently, so I will have to arrange something.  I will update this bug when I have a savegame configured to reproduce it.

**Comment by loki79uk** [comment]
I tested this last night, and it seemed to work.  I was going to test it fully today after work - BUT my son is playing Fortite on his PC (and I need it to host the dedi server).

If anyone can test this bug for me in MP that would be great, but otherwise I will do it when I can!

https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.0.7

**Comment by loki79uk** [comment]
I think this is working as expected now: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.0.8

**Comment by loki79uk** [comment]
I have not heard any further reports of this problem, so closing for now.  Please re-open if not fixed for you.
