### ISSUE TITLE
Add the posibility of different loading area in function of the configuration options

### ISSUE THREAD

**Issue by rarandab** [loki79uk/FS22_UniversalAutoload#149]
Would it possible to add a config parameter to select a loading area or other in function of the configuration options of the vehicule? as example the TLX3500_XL_Prospector attachment has an option for standard width or extra width and that does that the loading area available changes.

Best regards

**Comment by loki79uk** [comment]
Yes it should be possible already.  I don't know that mod, but you need to find the name of the configuration option in the xml, and set that as the `useConfigName` option for each configuration.  The index is still defined with `selectedConfigs`, but in combination with the config name it then applies to the specified configuration, not the default "configuration sets".

See this example from the UAL Add-on mod:
```xml
        <vehicleConfiguration configFileName="FS22_LizardLightTrailer650/FS22_LightTrailer650.xml" useConfigName="fillUnit" selectedConfigs="1" modHubId="243955">  
            <loadingArea offset="0.000 1.01 0.0" width="2.30" height="2.00" length="4.30" baleHeight="2.5"/>
            <options enableRearLoading="true" enableSideLoading="true"/>
        </vehicleConfiguration>
        <vehicleConfiguration configFileName="FS22_LizardLightTrailer650/FS22_LightTrailer650.xml" useConfigName="fillUnit" selectedConfigs="2" modHubId="243955">  
            <loadingArea offset="0.000 1.01 0.0" width="2.65" height="2.00" length="4.30" baleHeight="2.85"/>
            <options enableSideLoading="true" isBaleTrailer="true"/>
        </vehicleConfiguration>
        <vehicleConfiguration configFileName="FS22_LizardLightTrailer650/FS22_LightTrailer650.xml" useConfigName="fillUnit" selectedConfigs="3" modHubId="243955">  
            <loadingArea offset="0.000 1.01 0.0" width="2.30" height="1.40" length="4.30"/>
            <options enableRearLoading="true" isLogTrailer="true"/>
        </vehicleConfiguration>
```

**Comment by ddewar** [comment]
Hey @rarandab if you need any help with this feel free to open an issue on the Modhub Addon Mod. I can take a look at it when I get some time. This attachment should be included in that mod and I have been meaning to fix this issue.

**Comment by rarandab** [comment]
Hi,

Thanks @loki79uk in my previous attemps didn't understand how to use useConfigName together with selectedConfigs, with the example that you provided I have been able to configure in function of one configuration option

This attachement has more that one config option that modifies the surface available for load, is there any way to take into account two configuration options? By now I have configured in this way:
`		
                <vehicleConfiguration configFileName="FS22_TLX3500_Series/attachments/xl_prospector3500.xml" useConfigName="tensionBelts" selectedConfigs="2">  
			<loadingArea offset="0.000 1.900 -0.050" width="2.30" height="2.25" length="3.1"/>
			<options enableRearLoading="true" enableSideLoading="true" showDebug="false"/>
		</vehicleConfiguration>
`

I didn't know the AddOns mod, sorry, @ddewar, I just downloaded it and see that it has included the TLX3500 attachments, but without taking into account the option about the width, but comparing the options between the AddOn and mine it only differs in 0.20 that propably don't make any additional capacity.

Best regards

**Comment by loki79uk** [comment]
Closing as this seems resolved, but please open again if you are still having any issues.
