### ISSUE TITLE
Unloading issues since 1.3 on dedicated server.

### ISSUE THREAD

**Issue by NOLA-CML** [loki79uk/FS22_UniversalAutoload#15]
Before the 1.3 update everything ran great. After the update the items don't update when unloading.

Steps to reproduce:
1. Load a trailer with pallets on a dedicated server.
2. Try to unload it.

Actual Result: The trailer seems to unload as the weight comes off and the trailer rises. Logging out and back in places the items on the ground.

Expected Result: Items should unload as they do in single player.

Reproducible: Always.

This also does not happen when hosting a multiplayer game from my pc, only when connecting to our dedicated server.

The only thing I see in the log is:
`C://SERVICES//ni6964974_1_local//lws22//profile/mods/FS22_UniversalAutoload/UniversalAutoload.lua:1828: attempt to index local 'thisLoadPlace' (a nil value)`

Don't know if it helps, but the same thing also happens with Achimobil's autoload script.

**Comment by loki79uk** [comment]
I'm pretty sure I've already fixed/prevented this error (in my working verison), but I was getting it for a different reason (after loading a save game with incorrect loading length).  I'll try to get the new version released asap - hopefully tomorrow.

**Comment by loki79uk** [comment]
I still get the problem though with invisible pallets on dedi servers - so I guess the error was probably not related..  Working on it now.

**Comment by loki79uk** [comment]
This is now a big problem.. :(  It is not just dedicated servers, also happens for clients on player hosted MP games.

I think that this is actually related to a long standing bug that used to affect any MP objects (e.g. chairs, hammers, tools, etc) even in FS19 - where the visible position of the object is updated on the server, but never the client.  However, the hitbox **is** updated on the client, so you end up with an invisible object blocking player movement.  You can even pick up the invisible object as a client and move it around on the server. Anyway, now it seems to apply to pallets as well..

Hopefully GIANTS will comment and resolve soon.

**Comment by loki79uk** [comment]
I think this is 'fixed' as much as possible now: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-004

I could spend more time looking at trying to do a proper fix of the base game code instead of a workaround, but I think I will wait for some comment from GIANTS rather than waste too much time on something they are likely to fix anyway.

**Comment by NOLA-CML** [comment]
Confirmed working, just have to make sure you close the trailer before moving. 😂
