### ISSUE TITLE
Unable to change the dropside

### ISSUE THREAD

**Issue by AN-Vyper007** [loki79uk/FS22_UniversalAutoload#151]
Hello loki,
thanks for your mod! Today a new baletrailer was released at modhub: Wiegert BWZ 760 Baleloader, modID: 261704

i added to my UniversalAutoload.xml at .\modSettings\ the following line:
```
	<vehicleConfiguration configFileName="FS22_wiegertBWZ760/wiegertBWZ760.xml">  
		<loadingArea offset="0.60 1.100 -1.300" width="1.21" height="2.8" length="7.55" baleHeight="2.80"/>
		<loadingArea offset="-0.60 1.100 -1.300" width="1.21" height="2.8" length="7.55" baleHeight="2.80"/>		
		<options isBaleTrailer="true" disableAutoStrap="true"/>
	</vehicleConfiguration>
```

nearly everything work as exspected but i am unable to change the dropside. i crosstestet with the brantner baletrailer, there i can change the side, so its not key-binding-related.

i can not see anything with debug enabled. can you please have a look, if its a problem with the trailer or the UAL-mod?

thank you very much, keep up the good work!

**Comment by loki79uk** [comment]
Hi, sorry I have not looked at this yet. My internet is down and they will not even begin digging up the road until Monday, so could be a few more days until I get a chance.  Maybe @ddewar can help before then?

**Comment by ddewar** [comment]
I can definitely take a look at this a little bit later today. Did you turn on the setting to make the keybindings show at the top of the F1 menu?

**Comment by AN-Vyper007** [comment]
@loki79uk no problem, just no stress.

@ddewar where do I find the setting to show it in the f1 menu at the top?
I only tested it on another trailer to rule out key binding.

**Comment by loki79uk** [comment]
I added a new global flag, but I have not publicised it too much yet as it is kind of experimental.  It adds an extra priority level to all UAL items in the F1 menu, so using it may push other keybindings from other mods off the bottom instead.

Try adding `highPriority="true"` in the local settings `..\FarmingSimulator2022\modSettings\UniversalAutoload.xml`: 
```xml
<universalAutoload highPriority="true" showDebug="false" manualLoadingOnly="false" disableAutoStrap="false" pricePerLog="0" pricePerBale="0" pricePerPallet="0">
```

**Comment by loki79uk** [comment]
Is this working now?  I wondered about making "high priority" the default, but also I don't want UAL to get blamed for booting other menu items from the F1 menu..

**Comment by loki79uk** [comment]
Closing as assume fixed.  Please reopen if needed.
