### ISSUE TITLE
Roundbale width problem version 1.3.1.0

### ISSUE THREAD

**Issue by meisterjk** [loki79uk/FS22_UniversalAutoload#154]
Hi, i have a problem with loading Bales. 

i think the width of the roundbales are wrong calculated.
For 1 row of 1.50m roundbales in need at last an 1.6m loadingarea width.
For 2 rows i need 3.2m loadingarea width.

	<vehicleConfiguration configFileName="data/vehicles/farmtech/dpw1800/dpw1800.xml">
		<loadingArea offset="0.0 1.185 -0.838" width="2.65" height="2.80" length="9.650"/>
		
		<options isBaleTrailer="true" showDebug="true" zonesOverlap="false" horizontalLoading="false"/>
	</vehicleConfiguration>

![Unbenannt](https://user-images.githubusercontent.com/17692819/216050907-41e7973a-7e8f-452b-9c25-bbf1b7d9fa7d.png)

**Comment by loki79uk** [comment]
Round bales are defined as:
```
        <containerConfiguration containerType="BALE" name="roundbale125" sizeX="1.300" sizeY="1.20" sizeZ="1.300" isRoundbale="true" flipYZ="true"/>
        <containerConfiguration containerType="BALE" name="roundbale150" sizeX="1.560" sizeY="1.20" sizeZ="1.560" isRoundbale="true" flipYZ="true"/>
        <containerConfiguration containerType="BALE" name="roundbale180" sizeX="1.835" sizeY="1.20" sizeZ="1.835" isRoundbale="true" flipYZ="true"/>
```

So the 'width' of a 150 bale is 1.560m, as you can also see in the debugging log.

You can try defining narrower bales in your local settings if you want to, but I found that they needed that extra bit of space to load properly.  It is possible that GIANTS have tweaked the collision boxes for bales since I first tested it though.

**Comment by loki79uk** [comment]
Ahh, or do you mean that it is supposed to be 1.2m when rotated on their sides?  This could be a bug for sure - I'll check when I can, but it will probably be in a couple of weeks time.

**Comment by TenroNamikaze** [comment]
If I might add to this, I was also looking at the DPW1800 and could not get 2 round bales side by side. I tried editing the width of the loading area to 3.0 and even though the bounding boxes show enough room, they still would not stack 2 wide. No alterations to the bale size and I was using 150cm wrapped bales.

**Comment by TenroNamikaze** [comment]
Just changed the width to 3.2 and the bales are now 2 wide (See Image) believe it is reading the bale width and length reversed. hope that helps.
![FS22 Autoload Width 3 2](https://user-images.githubusercontent.com/14202783/218489626-95159945-9e7e-4473-991a-0f1e54da81b6.png)

**Comment by discord5000** [comment]
They now stack properly but width still needs to be set at >=3.15 or it complains there is not enough space. You can see the loading area is much wider than it needs to be to fit the bales, like it needs the space to stack them vertically.
![fsScreen_2023_02_28_11_48_59](https://user-images.githubusercontent.com/46521730/221723484-efa8171e-e881-46f0-b2ca-ff221be16d14.png)

**Comment by loki79uk** [comment]
Okay, thanks for testing - it is also off centre, so definitley something screwy going on!  I'll update here when I make some progress.

**Comment by loki79uk** [comment]
I did a bit more work on this - it needs cleaning up, BUT it seems to be working better now at least..
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.1.2

**Comment by discord5000** [comment]
Didn't fix for me, I set loading area width to 3.0M and it still only did a single row of bales.

**Comment by discord5000** [comment]
Also, with the width set to 3.15M, I'm getting behaviour like the previous versions, with a big gap between the rows.

**Comment by loki79uk** [comment]
Okay, thanks - I think I just went around in a big circle and now back where I started. I forgot to check the double rows.  I'll try again this evening.

**Comment by loki79uk** [comment]
Okay, I think (hope) this may be fixed now.. https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.1.3

I actually have a screenshot of it working this time:
![image](https://user-images.githubusercontent.com/76516343/222285870-d79b5040-73da-462d-b28a-37e0fef052bc.png)

**Comment by discord5000** [comment]
Tested and looks to be working great, love your work!

**Comment by loki79uk** [comment]
I had to speed up the loading to stop the bales rolling.  I noticed that there is an offset centre of mass so they do eventually settle.  I will see if I can roatate them into the stable position during placement..
