### ISSUE TITLE
[Enhancement] Keep autoload on/off

### ISSUE THREAD

**Issue by Myiamoto86** [loki79uk/FS22_UniversalAutoload#157]
good night loki,

How much time. Friend, a suggestion that makes a difference in the game and will be very useful with the question of your mod working together with Autodrive... Instead of activating it every time you want to load a pallet, bale, among other items, why not change to enable/disable autoloading? Keep the issue of loading only stationary, but if you make this change, it will help a lot during matches and will further reduce the player's direct performance. this gives us freedom to automate various processes. I do this practice of automation constantly, especially on large maps.

Here's the tip.

Good to talk to you again. Hugs and see you soon.

**Comment by loki79uk** [comment]
So you mean like the bale mode, but for normal pallet collection?  There are certainly some ideas around this that could work with AD, but maybe specific solutions only available to the AD interface rather than adding a new collection mode for normal use.

**Comment by Myiamoto86** [comment]
Hello Loki,

How are you?

So, the first suggestion was to integrate your mod with autodrive. The second was to have the automatic collection option turned on or off... For example: If I leave a trailer parked next to a factory pallet generator and/or a sheep pen, without the driver inside and with automatic picking of bales and pallets. With this, players similar to me do not need to spend all the time going to the vehicle to collect the pallets.
