### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Bandesss** [loki79uk/FS22_UniversalAutoload#159]
Why can't he load seedlings trees and foil and twine? There is no compatible load coming

?

**Comment by FarmerMike87** [comment]
Quite simply because the pallets probably have different dimensions than the standard pallets and are probably not registered.

**Comment by loki79uk** [comment]
Hi, sorry I've been away for the last couple of weeks.  @FarmerMike87 is most probably correct.  By default only base game items are supported.  Mod pallets/items must be added to your local settings file.  Can you post a log file from a game where you are getting this issue.

**Comment by loki79uk** [comment]
Closing as seems like trying to load unsupported mods (seedlings, foil and twine) without adding UAL definitions to local settings file.
