### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by kolya83** [loki79uk/FS22_UniversalAutoload#162]
Здраствуйте после обновления [v1.3.1.4] проподает топливо с транспортных средств где пропицана  [УниверсальнаяАвтозагрузка]

**Comment by loki79uk** [comment]
> Hello after the update [v1.3.1.4] sells fuel from vehicles where [Universal Autoload] is saturated

Hi, thank you for spotting this!  It should be working again in: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.1.5

Some functions added in #153 were responsible.  I don't have time to do a proper fix now, but I have disabled them all and will work on the full AD integration as my next task.

**Comment by kolya83** [comment]
Спасибо всё нормально
