### ISSUE TITLE
Sugar pallets aren't detected

### ISSUE THREAD

**Issue by Andreiva13** [loki79uk/FS22_UniversalAutoload#163]
Hi! 
I can't get the autoload feature to work for sugar pallets while it works for other types of pallets.
I am playing on the Frankenmuth map. not sure if it has custom pallets or not.
![Works](https://user-images.githubusercontent.com/43719525/224351264-029749a8-e0e4-48cb-be37-8e8d093bc156.png)
![Doesn't work](https://user-images.githubusercontent.com/43719525/224351285-5c0e3fc7-3fb1-4b29-b630-d8471564c1d2.png)

**Comment by Andreiva13** [comment]
Here's the log.txt
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/10944306/log.txt)

**Comment by loki79uk** [comment]
There is certainly something going on with `FS22_lizard_rumblerVan_crossplay` which has its own copy of a load of standard pallets.  But that doesn't explain why it isn't working though.

I don't recognise that trailer though?  Where is the config loaded from?  Do the sugar pallets load with any base game trailers, and/or does that trailer work with standads pallets on a standard map.

**Comment by Andreiva13** [comment]
Trailer is from [here](https://www.farming-simulator.com/mod.php?lang=en&mod_id=262385&title=fs2022) with the autoload stuff added by me in it's .xml files. Also not working with the vanilla Krone trailer but I haven't tried a standard map

**Comment by loki79uk** [comment]
If other trailers don't work with the sugar bags, and other pallets do load on that trailer then it does point to the pallets being the problem.  What happens if you load the game without `FS22_lizard_rumblerVan_crossplay`?

**Comment by loki79uk** [comment]
Could it be this actually?  Do both mods add their own pallets?
```
2023-03-10 16:45   Load mod: FS22_lizard_rumblerVan
2023-03-10 16:45   Load mod: FS22_lizard_rumblerVan_crossplay
```

**Comment by Andreiva13** [comment]
Removing FS22_lizard_rumblerVan_crossplay seems to make it work. Seems that mod replaces the original pallets the sugar mill produces for some reason.
Thanks for the help!

**Comment by loki79uk** [comment]
Glad you got it working - but it should work even with replaced pallets.  I will try to reproduce with that mod on another map.

**Comment by loki79uk** [comment]
If you still want to use that rumbler mod then for now you just need to add the following line inside the `objectTypes` tags in your local settings file:

`<objectType name="FS22_lizard_rumblerVan_crossplay:palletAttachable"/>`


_Note: settings file is usually here `%HOMEPATH%\Documents\My Games\FarmingSimulator2022\modSettings\UniversalAutoload.xml`_
