### ISSUE TITLE
Advances on AutoDrive support

### ISSUE THREAD

**Issue by regs1980** [loki79uk/FS22_UniversalAutoload#168]
What else needs to be done to be able to use UniversalAutoload in AutoDrive?
Is it the interface between AutoDrive and UniversalAutoload or does Axel32019 only have to adapt AutoDrive with regard to the unloading side, opening the plane, loading and unloading?

**Comment by loki79uk** [comment]
I think that most of the required functions are done, but I'm waiting to see what else is required.

The only tricky one that I know about is to select fill types, because UAL can load any fill type or container, so usually it will only display whatever is near by.  When creating an AD route, you cannot know what is at the destination, so I think it makes the most sense to offer all possible fill types and containers from the map, but then that is a big list!

**Comment by regs1980** [comment]
Why not just the categories e.g. seed bags, round bales 125 - 180 or pallets.
People already know what they are produced there.
Very important is then the option to take everything from the loading point. 
This makes your mod so interesting and practical, I can load IBC containers and seed bags at the same time and bring to the field.

**Comment by loki79uk** [comment]
> Hi, I have encountered a problem with your mod working with AutoDrive. I can't buy any car from store (pickup, mahindra, JD, etc.). When I deactivate one of the modes it is possible again. So I buy the car, saved the game and restart with both of them activated. Game do not load :(.
> 
> I love your mod and I hope you could help me with that issue.

Can you send me a log file from a game where this happens.  I will investigate this evening!

**Comment by ikarus-22** [comment]
Hi Loki,
Here is the log file (I hope, I've done it ok) .

[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/11214376/log.txt)

**Comment by loki79uk** [comment]
There is something going on with AD:
```
Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.
C:/Users/arkno/Documents/My Games/FarmingSimulator2022/mods/NG_FS22_AutoDrive/scripts/Specialization.lua:1566: attempt to index field 'ad' (a nil value)
```

Does this happen with the latest version of AD? https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0

I can buy any car with no errors on my savegame.

**Comment by regs1980** [comment]
@ikarus-22 Bring both versions up to date https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.1.14 and https://github.com/Stephan-S/FS22_AutoDrive/releases/tag/2.0.1.0

**Comment by ikarus-22** [comment]
Hi again,
I have installed the latest versions of the mods, and now everything works.
Thanks for your help and sorry for the trouble. I didn't thought it could be related to the mods version.

**Comment by loki79uk** [comment]
Going back to the original question, I think that @Axel32019 is getting close to finalising the AD/UAL interface.  I don't know the schedule for release, but they are now working together quite smoothly in dev versions.

**Comment by regs1980** [comment]
@loki79uk Has he already https://github.com/Stephan-S/FS22_AutoDrive/commit/140a7d66dc59befc45b8bbb3e7a20d66019b74a5
