### ISSUE TITLE
Only load one object 

### ISSUE THREAD

**Issue by gborges-l** [loki79uk/FS22_UniversalAutoload#169]
recently update UA to last version and went try tu use in external trailer mods adds xml ways, they only load 1 object, any kind of them, pallets, bigbags, round bales, but only one.
i try to reload, reset, do a fresh installation of game, change mods, but keep the problem.
the in-game trailers don't have problems, only with added trailers mod in my game / modsettings/xml document

I rolled back to previous version and this problem it's presented since 1.3.1.1 version

the 1.3.1.0 it works fine

I have FS22 updated to 1.9.0.0

any solutions for that?
thanks

**Comment by loki79uk** [comment]
Can you send me a log file from when it is happening please, and also your local modsettings xml file.

**Comment by gborges-l** [comment]
[UniversalAutoload.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/11238110/UniversalAutoload.txt)
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/11238111/log.txt)

i try new mod and some of them work
- great Dane FLT
- reisch trailer pack reisch 160
- flieglTrailers
- MAN_TGX_26640_Platform
but some else don't
- orkelTX130
- Maz_938662

**Comment by loki79uk** [comment]
Howhave you determined the settings for these mods?  I don't have time to configure them now, but suggest removing your settings file for now and using the latest version of the ModHub Add-on: https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/latest   This at least has 'FS22_orkelTX130' and `FS22_orkelTX130` so you could compare your settings.  Any collisions of the loading zone with part of the model will move the loaded items and prevent any further items from loading.

also note that you do not need to use the console command to load the settings, that is only for testing new modified settings without re-loading the game.

**Comment by gborges-l** [comment]
Hi, 
I see a YouTube video time ago about configuration of own mods in UA
I did it and work fine until i updated mi base game and mani of the used mods.
I test the FS22_UniversalAutoloadModhubAddon with orkelTX130 trailer, and have the same problem, event without any other mods, and without modification of UniversalAutoload.xml file. 
now i used last version 1.3.1.16 UA
last vs of UA modhub add-on 1.2.0.0
(by the why: it said its that number but it's show a 1.1.0.0)
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/11243073/log.txt)

**Comment by loki79uk** [comment]
Try with the Orkel TX 130 "Bale Trailer" configuration, that one works fine for me.

I tested with the "Capacity 8500" and that did only load one pallet for me as well.  I don't have time to look now, but it seems something strange about that configuration, maybe because it is also has a fill volume.

**Comment by loki79uk** [comment]
I have also tested with 1.3.1.0, and can confirm that this one works so there must be something added in the recent developments that affects some trailers and not others.  I will try to find it this evening!

**Comment by loki79uk** [comment]
Should be fixed now in the latest release:
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.1.17

It was actually a very easy fix - affecting only the trailers with existing fill types was the key information to identify it!

**Comment by loki79uk** [comment]
Great!  Thank you for reporting the bug.
