### ISSUE TITLE
Hof Bergmann wool bales

### ISSUE THREAD

**Issue by DanL58** [loki79uk/FS22_UniversalAutoload#170]
Loki, the small wool bales on Hof Bergmann will only autoload 1 layer on any trailer that I have tried. Is there a way to allow them to load 2 or 3 layers? Thanks

**Comment by loki79uk** [comment]
What configuration are you using for them?  The Add-on?

**Comment by DanL58** [comment]
Sorry, I don't know what you mean. Not on computer now but I can send you a screenshot later if you want

**Comment by DanL58** [comment]
Oh, sorry. I am using the Add-on that you made a few months ago for the small Hof Bergmann pallets

**Comment by loki79uk** [comment]
Okay, I'd forgotten about that - have wool pallets never worked, or did they work previously and recently stopped?

Is the Hof Bergmann map version still the same?  Could it have different pallet sizes, or new pallets added?

**Comment by loki79uk** [comment]
Try changing the pallet dimensions to:
`<containerConfiguration name="FS22_HofBergmann:woolBundle" containerType="ALL" sizeX="0.600" sizeY="0.575" sizeZ="0.800"/>`

I could reproduce the single layer loading with the old values, and that change fixed it for me.

**Comment by DanL58** [comment]
I'll make these changes and try it later, got some real life things going on now. Thanks for the help Loki

**Comment by loki79uk** [comment]
Closing now, as it was fixed for me, but please reopen if any issues.
