### ISSUE TITLE
Help adding support to non-ModHub vehicle

### ISSUE THREAD

**Issue by BurcoGames** [loki79uk/FS22_UniversalAutoload#173]
So I've downloaded a URAL pack from a 3rd party site (https://zagruzkamods.com/20277-ural-pack-trucks-v11-for-fs22.html) and have been trying to add support for UAL to it, but it doesn't seem to work. I have the latest version of the mod, I've tried using the modSettings file to add the config (and also tried adding it to both the vehicle xml and the UAL supported vehicles xml) and it hasn't worked yet.

Not sure what else to do, so I figured I'd ask here.

**Comment by BurcoGames** [comment]
> ich kann mir das gerne mal ansehen wen du es willst.
> 
> MFG Mannie313

Okay, I'm thinking my issue is because the pack uses a custom vehicle type, and it's not being recognized by the script. That's all I can think of.

**Comment by loki79uk** [comment]
Can you please post your log file on here so I can see what is happening?

**Comment by BurcoGames** [comment]
Sure, here it is. I looked through it and don't see anything out of the ordinary, but maybe you might see something that I don't.
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/11264778/log.txt)

**Comment by loki79uk** [comment]
Don't know if it is the cause, but this doesn't look ideal:
```
2023-04-18 12:31 D:/FS22_ModFolder/FS22_Gnadenthal/FS22_Ural_Pack_SJ/i3d/URAL_Manipulator2.i3d (260.48 ms)
2023-04-18 12:31 Error: Missing dds file 'D:/GAMES/FS 22/_MODDING/URAL_PACK/FS22_URAL_Farmer_SJ/wheels/O-184_n.dds'
2023-04-18 12:31 Error: Can't load resource 'D:/GAMES/FS 22/_MODDING/URAL_PACK/FS22_URAL_Farmer_SJ/wheels/O-184_n.dds'.
2023-04-18 12:31 Error: Missing dds file 'D:/GAMES/FS 22/_MODDING/URAL_PACK/FS22_URAL_Farmer_SJ/wheels/O-184_s.dds'
2023-04-18 12:31 Error: Can't load resource 'D:/GAMES/FS 22/_MODDING/URAL_PACK/FS22_URAL_Farmer_SJ/wheels/O-184_s.dds'.
```

Did you try to buy the vehicle in that save game (that produced the log)?  And does the vehicle load correctly without any other mods active?

**Comment by BurcoGames** [comment]
> Don't know if it is the cause, but this doesn't look ideal:
> ```
> 2023-04-18 12:31 D:/FS22_ModFolder/FS22_Gnadenthal/FS22_Ural_Pack_SJ/i3d/URAL_Manipulator2.i3d (260.48 ms)
> 2023-04-18 12:31 Error: Missing dds file 'D:/GAMES/FS 22/_MODDING/URAL_PACK/FS22_URAL_Farmer_SJ/wheels/O-184_n.dds'
> 2023-04-18 12:31 Error: Can't load resource 'D:/GAMES/FS 22/_MODDING/URAL_PACK/FS22_URAL_Farmer_SJ/wheels/O-184_n.dds'.
> 2023-04-18 12:31 Error: Missing dds file 'D:/GAMES/FS 22/_MODDING/URAL_PACK/FS22_URAL_Farmer_SJ/wheels/O-184_s.dds'
> 2023-04-18 12:31 Error: Can't load resource 'D:/GAMES/FS 22/_MODDING/URAL_PACK/FS22_URAL_Farmer_SJ/wheels/O-184_s.dds'.
> ```
> 
> Did you try to buy the vehicle in that save game (that produced the log)?  And does the vehicle load correctly without any other mods active?

That error is just a missing wheel texture, nothing major. And yes, I already had the vehicle purchased, did the changes, reloaded the save several times and tried repurchasing the vehicle. The mod itself loads fine without anything else active.

**Comment by loki79uk** [comment]
What text exactly are you using for your configurations settings?

It looks like you have use `FS22_Ural_Pack_SJ/URAL_Manipulator2.i3d` instead of `FS22_Ural_Pack_SJ/i3d/URAL_Manipulator2.i3d`.  It has to be a valid path inside the mod folder.

**Comment by BurcoGames** [comment]
> What text exactly are you using for your configurations settings?
> 
> It looks like you have used `FS22_Ural_Pack_SJ/URAL_Manipulator2.i3d` instead of `FS22_Ural_Pack_SJ/i3d/URAL_Manipulator2.i3d`. It has to be a valid path inside the mod folder.

Here's the config from the modSettings file.
<vehicleConfiguration configFileName="FS22_Ural_Pack_SJ/URAL_Manipulator2.xml">  
            <loadingArea offset="0.000 2.194 -2.25" width="2.46" height="1.25" length="4.75" baleHeight="3.75"/>
					<options enableRearLoading="true" enableSideLoading="true"/>
				</vehicleConfiguration>

**Comment by BurcoGames** [comment]
> What text exactly are you using for your configurations settings?
> 
> It looks like you have used `FS22_Ural_Pack_SJ/URAL_Manipulator2.i3d` instead of `FS22_Ural_Pack_SJ/i3d/URAL_Manipulator2.i3d`. It has to be a valid path inside the mod folder.

Here is the config from the modSettings file.
`<vehicleConfiguration configFileName="FS22_Ural_Pack_SJ/URAL_Manipulator2.xml">  
            <loadingArea offset="0.000 2.194 -2.25" width="2.46" height="1.25" length="4.75" baleHeight="3.75"/>
					<options enableRearLoading="true" enableSideLoading="true"/>
				</vehicleConfiguration>`

**Comment by loki79uk** [comment]
Have you tried with the path I suggested?

**Comment by BurcoGames** [comment]
> FS22_Ural_Pack_SJ/i3d/URAL_Manipulator2.i3d

Trying now, will report in a few minutes.

**Comment by BurcoGames** [comment]
Replaced that configFileName line and it didn't fix it.

**Comment by loki79uk** [comment]
Can you send me the log file now?

**Comment by BurcoGames** [comment]
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/11288503/log.txt)

**Comment by loki79uk** [comment]
Now it is not loading anything.  Previously it was importing the vehicle settings here:
```
2023-04-20 11:33 IMPORT user vehicle configurations
2023-04-20 11:33 IMPORT user container configurations
```
Can you try a clean game with just the two mods that you are trying to debug?

**Comment by BurcoGames** [comment]
Trying now.

**Comment by BurcoGames** [comment]
Quick question - did you want the configFileName to be `FS22_Ural_Pack_SJ/i3d/URAL_Manipulator2.i3d`?

**Comment by loki79uk** [comment]
Sorry, it should be `URAL_Manipulator2.xml`, with the path of wherever the xml is?  I just corrected the path, but didn't notice that it was an i3d!

**Comment by loki79uk** [comment]
Okay, I don't know what is going on, but it loads okay for the "URAL_Farmer" vehicle using the same settings (I didn't bother changing them to fit):
```xml
	<vehicleConfiguration configFileName="FS22_Ural_Pack_SJ/URAL_Farmer.xml">
		<loadingArea offset="0.000 2.194 -2.25" width="2.46" height="1.25" length="4.75" baleHeight="3.75"/>
		<options enableRearLoading="true" enableSideLoading="true"/>
	</vehicleConfiguration>
	<vehicleConfiguration configFileName="FS22_Ural_Pack_SJ/URAL_Manipulator2.xml">
		<loadingArea offset="0.000 2.194 -2.25" width="2.46" height="1.25" length="4.75" baleHeight="3.75"/>
		<options enableRearLoading="true" enableSideLoading="true"/>
	</vehicleConfiguration>
```

![image](https://user-images.githubusercontent.com/76516343/233446076-ba51249e-8bf0-46bc-89d9-3fd4944d1883.png)

**Comment by BurcoGames** [comment]
That's... really odd.

**Comment by BurcoGames** [comment]
What's even more odd is the grain body doesn't have straps... isn't that how the script works is using the strap config?

**Comment by loki79uk** [comment]
It has to have a strap config, even if there are no actual straps.

**Comment by BurcoGames** [comment]
Hmm... yeah the grain body doesn't have the config for straps at all, but the flatbed does.

**Comment by loki79uk** [comment]
You are right!  That is really weird!?

This is stupposed to prevent it loading:
```lua
function UniversalAutoload.prerequisitesPresent(specializations)
	return SpecializationUtil.hasSpecialization(TensionBelts, specializations)
end
```
and for belt and braces I did this too:
```lua
	if SpecializationUtil.hasSpecialization(TensionBelts, vehicleType.specializations) then
		g_vehicleTypeManager:addSpecialization(vehicleName, UniversalAutoload.name .. '.universalAutoload')
		-- print("  UAL INSTALLED: "..vehicleName)
	end
```

**Comment by BurcoGames** [comment]
I'm over here running through my brain any sort of possible cause for this, but I can't figure it out LOL

**Comment by loki79uk** [comment]
It is weird because the Farmer one is loaded earlier, and then these two are loaded on the second round:
```
2023-04-20 19:08   UAL INSTALLED: FS22_Ural_Pack_SJ.Pallet_connector
2023-04-20 19:08   UAL INSTALLED: FS22_Ural_Pack_SJ.URAL
```

I tried changing the order and loading them all at the end, but it didn't make any difference.  The `URAL` one still shows up in the store pack for UAL, even when it is not active.

**Comment by BurcoGames** [comment]
> I still would like to see it without the texture errors.  It happens exactly around the time when UAL is supposed to configure itself (after the vehicle onLoad).  I wonder if the error breaks the appended function from being called, or maybe the delay from loading the texures just takes too long and the loading tasks time out? idk?

I fixed that texture error, it's in the code for the URAL_wheels i3d file, it's just a file path that needs to be changed.

**Comment by loki79uk** [comment]
I just fix it too, and makes no difference to UAL..  I'm going to try changing the name of the vehicle type.

**Comment by loki79uk** [comment]
So it tries to instal UAL, but doesn't populate the table.

for the farmer one I get a full table:
```
2023-04-20 19:53 --spec_FS22_UniversalAutoload.universalAutoload :: table: 0x0248929a6d28
2023-04-20 19:53 --    noLoadingIfFolded :: false
2023-04-20 19:53 --    noLoadingIfUnfolded :: false
2023-04-20 19:53 --    noLoadingIfCovered :: false
2023-04-20 19:53 --    autoLoadingObjects :: table: 0x024812eaa968
... etc ...
```

but for the other vehicle it is empty, apart from the action events table:
```
2023-04-20 19:57 --spec_FS22_UniversalAutoload.universalAutoload :: table: 0x022870f879d0
2023-04-20 19:57 --    actionEvents :: table: 0x022870f842a8
2023-04-20 19:57 --isActiveForLocalSound :: false
2023-04-20 19:57 --onPassengerPlayerStyleChanged :: function: 0x022879fb46d8
```

**Comment by loki79uk** [comment]
Okay, I can't explain it, but it works as expected if you rename the mod to `FS22_aUral_Pack_SJ`.  My best guess is some kind of race condition where some of the vehicles in the pack are loaded, and others haven't, but I really don't understand how that could be the case..

```xml
		<vehicleConfiguration configFileName="FS22_aUral_Pack_SJ/URAL_Farmer.xml">
			<loadingArea offset="0.000 2.194 -2.25" width="2.46" height="1.25" length="4.75" baleHeight="3.75"/>
			<options enableRearLoading="true" enableSideLoading="true"/>
		</vehicleConfiguration>
		<vehicleConfiguration configFileName="FS22_aUral_Pack_SJ/URAL_Manipulator.xml">
			<loadingArea offset="0.000 2.194 -2.25" width="2.46" height="1.25" length="4.75" baleHeight="3.75"/>
			<options enableRearLoading="true" enableSideLoading="true"/>
		</vehicleConfiguration>
		<vehicleConfiguration configFileName="FS22_aUral_Pack_SJ/URAL_Manipulator2.xml">
			<loadingArea offset="0.000 2.194 -2.25" width="2.46" height="1.25" length="4.75" baleHeight="3.75"/>
			<options enableRearLoading="true" enableSideLoading="true"/>
		</vehicleConfiguration>
```

![image](https://user-images.githubusercontent.com/76516343/233463252-51e331dd-1d5b-4c40-b836-5cd5c4ea0617.png)

**Comment by BurcoGames** [comment]
Learning something new every day, aren't we? XD

**Comment by loki79uk** [comment]
My brain is frazzled now, and I need to do some other stuff.  I'll see if I can figure it out another day, but I have tried all the things I can think of.  If you can use it renamed for now, then at least it works, but I hate not understanding something like this so hopefully will figure it out eventually!

**Comment by BurcoGames** [comment]
LOL I understand the feeling, I've worked with code for a number of years (apart from LUA, I can understand it but not write it) and it frazzles me from time to time. Renaming should work, as long as I double check that everything points to where it should. Thanks for the assistance!

**Comment by loki79uk** [comment]
Okay - after remebering to revert to the original name in my settings - I think I've fixed it!

**Comment by loki79uk** [comment]
Please try this version with the original mod name:
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.3.2.0

Don't forget to change the path back in your settings (like I did)

**Comment by BurcoGames** [comment]
Did all that and it works! Hallelujah! Looks like the last minute idea worked like it should haha

**Comment by loki79uk** [comment]
Yeah, I should add that fix to all my other vehicle mods as well now - it looks like it was running the add specialisation too early for mods that load slower.  I guess because this one is pretty big and begins with U as well, so started loading quite late compared to most.

**Comment by BurcoGames** [comment]
Well, it's a good thing we got it figured out. Again, thanks for the assistance!
