### ISSUE TITLE
Mahindra Retriever seed filled raw without pallet 

### ISSUE THREAD

**Issue by ZeRtA1991** [loki79uk/FS22_UniversalAutoload#175]
so I tried to load a seed pattelte on my **Mahindra Retriever** instead i got raw seeds loaded and have no option to unload them except as a pile of unusable seeds so if it's possible to implement seeder unloading mechanic would be great and thank you for the great work

**Comment by loki79uk** [comment]
What do you think about preventing loading for any containers with filltypes that can be loaded as bulk?

**Comment by loki79uk** [comment]
I've implemented a semi-fix / workaround for this in the latest release.
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.4.0.4
