### ISSUE TITLE
(QUESTION) Manual Autoload on DEDI?

### ISSUE THREAD

**Issue by Jayshua83** [loki79uk/FS22_UniversalAutoload#176]
I have noticed in SP when I test different UAL loadouts/configs that you can carry things (with Super Strength or Pallet Forks) up near the  Autoload platform and it will  load it automagically.

I haven't seen that feature work in Dedi? 

Is that a feature that just might not work on Dedi? 
Or is there a config option that the server might need activated?

Thanks! :)

**Comment by loki79uk** [comment]
It should work on dedi, but I'll admit that I have not checked for a long time.  If you set `manualLoadingOnly= true` then it should be applied to all trailers (but not log trailers).  Otherwise, only for those with `enableSideLoading` and/or `enableRearLoading`
