### ISSUE TITLE
Error: Running LUA method 'loadSharedI3DFileFinished'

### ISSUE THREAD

**Issue by OlegPrymas** [loki79uk/FS22_UniversalAutoload#180]
How to solve a problem with a critical error?  
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/11585189/log.txt)

**Comment by loki79uk** [comment]
Good question!

The line with the 'invalid pattern capture' error is:
`local temp = i3d_path:gsub(g_modsDirectory, "")`

If you can edit the main UAL file to inlcude these lines (around line 4759), maybe we will see what is causing the error:

```lua
function UniversalAutoload.getEnvironmentNameFromPath(i3d_path)

	if i3d_path == nil then
		return
	end

-- ADD THIS LINE
	print("i3d_path:  " .. tostring(i3d_path))
--END ADD

	local customEnvironment = nil
	if i3d_path:find(g_modsDirectory) then

-- ALSO ADD THIS LINE
		print("  found in " .. tostring(g_modsDirectory))
-- END ADD

		local temp = i3d_path:gsub(g_modsDirectory, "")
		customEnvironment, _ = temp:match( "^(.-)/(.+)$" )
	else
		for i = 1, #g_dlcsDirectories do
			local dlcsDirectory = g_dlcsDirectories[i].path
			if dlcsDirectory:find(":") and i3d_path:find(dlcsDirectory) then

-- AND ADD THIS LINE JUST IN CASE
				print("  found in " .. tostring(dlcsDirectory))
-- END ADD

				local temp = i3d_path:gsub(dlcsDirectory, "")
				customEnvironment, _ = "pdlc_"..temp:match( "^(.-)/(.+)$" )
			end
		end
	end
	return customEnvironment
end
```

**Comment by OlegPrymas** [comment]
Should there be empty lines between them?

**Comment by loki79uk** [comment]
Empty lines don't matter, and the comments don't matter either, but comments must begin with `--` so that they are ignored.

**Comment by OlegPrymas** [comment]
Коментарии не писал,только строки вставил.Ничего не поменялось в лог то что и было

**Comment by OlegPrymas** [comment]
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/11585464/log.txt)

**Comment by OlegPrymas** [comment]
вот что получилось

**Comment by loki79uk** [comment]
I think something went wrong with adding the lines - can you try this version please:
[FS22_UniversalAutoload.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/11585934/FS22_UniversalAutoload.zip)

**Comment by OlegPrymas** [comment]
Спасибо,попробую отпишусь!

**Comment by OlegPrymas** [comment]
[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/11590554/log.txt)

**Comment by OlegPrymas** [comment]
это карта от Dajnet, PVcanyoncrossing
Может дело в полетах в карте,в оригинальной игре нет ошибок

**Comment by OlegPrymas** [comment]
Попробуй у себя ее установить и запустить с твоим модом

**Comment by OlegPrymas** [comment]
Ты был прав.проблема была в этом ).Спасибо за помощь!
