### ISSUE TITLE
Ballenrichtung

### ISSUE THREAD

**Issue by acton59** [loki79uk/FS22_UniversalAutoload#181]
Hallo,

ich würde gerne die Richtung der Ballen ändern.
Was muss ich tun ?

aldo
![20230604100634_1](https://github.com/loki79uk/FS22_UniversalAutoload/assets/59387744/6ba2694b-0ed4-415a-98e6-8053987cbbc5)
![20230604101554_1](https://github.com/loki79uk/FS22_UniversalAutoload/assets/59387744/162ee7ba-3311-4db4-a21f-554b2899afea)

**Comment by loki79uk** [comment]
Hi, you can change the bales to 'neverRotate':
```xml
        <containerConfiguration containerType="BALE" name="squarebale120" sizeX="0.455" sizeY="0.355" sizeZ="1.20" neverRotate="true"/>
        <containerConfiguration containerType="BALE" name="squarebale180" sizeX="1.210" sizeY="0.910" sizeZ="1.80" neverRotate="true"/>
        <containerConfiguration containerType="BALE" name="squarebale220" sizeX="1.210" sizeY="0.910" sizeZ="2.20" neverRotate="true"/>
        <containerConfiguration containerType="BALE" name="squarebale240" sizeX="1.210" sizeY="0.910" sizeZ="2.40" neverRotate="true"/>
```

Just be careful that on some trailers you may then get a single row like this:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/dec8b544-6a0b-4b6e-b42e-fa7902ac829e)

To avoid that you will have to also make the trailer width wide enough for two bales (i.e. `2.43` or wider)

**Comment by acton59** [comment]
okay, Danke für die schnelle Antwort. ich werde es versuchen und berichten

aldo

**Comment by acton59** [comment]
Hallo,

vielen Dank, funktioniert super auch unter Stapel und Ebene

aldo
![2023
![20230604114954_1](https://github.com/loki79uk/FS22_UniversalAutoload/assets/59387744/151d4967-2093-474a-9dca-ebd1bbb799cc)
0604114930_1](https://github.com/loki79uk/FS22_UniversalAutoload/assets/59387744/bbd4783b-306b-46f5-9d23-6fd671057b4b)

**Comment by acton59** [comment]
und Ebene
![20230604114954_1](https://github.com/loki79uk/FS22_UniversalAutoload/assets/59387744/9e56d780-74f3-4f01-b61e-8b243313d03c)
