### ISSUE TITLE
Says "Loading Area is Full" on empty log trailer

### ISSUE THREAD

**Issue by iNejGG** [loki79uk/FS22_UniversalAutoload#184]
Using base game Fliegl timber runner and while trying to load an empty trailer, get the loading area full message.
![autoload](https://github.com/loki79uk/FS22_UniversalAutoload/assets/138386803/1a988542-7f38-4eb1-b025-eaee72391dc6)

**Comment by loki79uk** [comment]
Can you turn on the debugging display (shift-ctrl- F12) and check the shape of those branches.  It could be that they just don't fit.  Quite often these can have invisible branches and really big bounding boxes.

I should add a different message for this case, but it gets complicated for trailers with multiple loading zones.

**Comment by loki79uk** [comment]
Closing as I assume it is the bounding boxes as mentioned above, but please re-open if not that and you are still having trouble.
