### ISSUE TITLE
Hilfe beim hinzufügen weiterer Ballenwägen

### ISSUE THREAD

**Issue by FarmerMike87** [loki79uk/FS22_UniversalAutoload#186]
Hallo zusammen ich würde gerne diese Anhänger 
https://sharemods.com/hh4mbk3llrjv/FS22_OldMultiTipper.zip.html
https://sharemods.com/caqoyp2dlivy/FS22_Strautmann_ThreeWayTippers.zip.html
https://sharemods.com/kxsrwdzfutvh/FS22_Old_Tipper.zip.html
https://sharemods.com/a491qbc1vf0q/FS22_UniversalAutoloadModhubAddon.zip.html
 zum UAL hinzufügen, nur wenn ich die Hänger einfüge passiert gar nichts.
 
 Vllt kann mir ja jemand behilflich sein.
 
 Mit besten Dank 
 Mike

**Comment by loki79uk** [comment]
I'm not sure what you are asking here, are you trying to use the UAL ModHub Addon with those mods?

It is best to get the latest version from the source, and not use questionable download sites:
https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon

You can also create a ticket there to add new trailers to the Add-on mod.

**Comment by FarmerMike87** [comment]
ok... Ist in Ordnung.
