### ISSUE TITLE
Could you please add addon support hayAndForagePack?

### ISSUE THREAD

**Issue by DatiQ** [loki79uk/FS22_UniversalAutoload#188]
I want to load things on a new trailer from this addons)

**Comment by loki79uk** [comment]
Do you mean the Reform tipper unit?  That one is added in the latest release and already submitted to ModHub.
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.4.0.5

**Comment by DatiQ** [comment]
you are my hero!)))
