### ISSUE TITLE
Autoloading Wood with FS22_TLX_X52_Logger/x52_logger

### ISSUE THREAD

**Issue by GarrettHafen** [loki79uk/FS22_UniversalAutoload#191]
I looked over [this ](https://github.com/loki79uk/FS22_UniversalAutoload/issues/132 )thread and confirmed that the layer count is incrementing but after the first layer, it never finds space. I'm using EDC to spawn 12 m spruce woodLogs. The trailer only loads 2 woodLogs. I tried this with 53' Dropdeck Trailer Autoload Bales which does about the same thing. I don't have a log for that one but I assume its the same.  The woodLogs are a bit thick, but there should be plenty of space. It works fine with the vanilla TimberRunner trailer. Don't know if that matters. [Picture](https://github.com/GarrettHafen/FS22_UniversalAutoloadModhubAddon/blob/main/20230724141047_1.jpg)

[log.txt](https://github.com/GarrettHafen/FS22_UniversalAutoloadModhubAddon/blob/main/log.txt)

SupportedVehicles.xml
` <vehicleConfiguration configFileName="FS22_TLX_X52_Logger/x52_logger.xml" modHubId="248615">
            <loadingArea offset="0 1.40 -0.50" width="2.15" height="2.20" length="14.5"/>
			<options isLogTrailer="true"/>
        </vehicleConfiguration>`

**Comment by loki79uk** [comment]
It looks like the loading area may be too low down.  Try raising it up until there is no clipping of the trailer (to where the logs are sitting).  You could also make it slightly narrower as well just to rule out that it isn't clipping on the lower parts of the uprights.

![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/461dcfd3-e817-42ba-891f-a273b5b0a763)

**Comment by GarrettHafen** [comment]
You're awesome, thanks for the reply, you are correct, I adjusted the loading area and now it is working. I realize now that these are modded trailers and I put the issue on the wrong repo. Thanks for responding anyways!

**Comment by GarrettHafen** [comment]
You're awesome, thanks for the reply, you are correct, I adjusted the loading area and now it is working. I realize now that these are modded trailers and I put the issue on the wrong repo. Thanks for responding anyways!
