### ISSUE TITLE
Abladeposition

### ISSUE THREAD

**Issue by acton59** [loki79uk/FS22_UniversalAutoload#194]
Hallo,

könnte man die Abladeposition verschiebbar machen, oder für jedes Fahrzeug den Offset einstellen

mfg

**Comment by loki79uk** [comment]
> you could make the unloading position moveable, or set the offset for each vehicle

Yes, I did consider that.  I could add it if it is really becoming an issue, but for now I'd like to keep the number of options to a minimum.  Soon I will start work on a setting page, then it will be easier to manage each vehicle.

**Comment by acton59** [comment]
Hallo,

Vielleicht könnte man die Drehung der Ballen umschalten wie beim stapeln.

mfg

**Comment by loki79uk** [comment]
> Maybe you could switch the rotation of the bales like when stacking them.

Do you mean when unloading?  The options are alreay quite complicated, I think that unloading in the same arrangement as they are already loaded is the most intuitive way to unload.
