### ISSUE TITLE
Drescher abladen

### ISSUE THREAD

**Issue by acton59** [loki79uk/FS22_UniversalAutoload#195]
Hallo,

Drescher abladen geht leider nicht mit 2 Anhänger. Ich weiß das ist gedacht für Überlader. Wäre aber schön.

mfg

**Comment by TobiHH78** [comment]
Was hat denn Drescher abladen mit Universal Autoload zu tun?
Das gehört wohl eher zu Courseplay. Und AutoDrive kann das schon ewig.

**Comment by acton59** [comment]
Oh sorry, hab ich mich wohl vertan. Kann gelöscht werden

**Comment by loki79uk** [comment]
> Oh sorry, I must have made a mistake. Can be deleted

I was going to ask for clarification, but if you are happy I will close this one.
