### ISSUE TITLE
[Enhancement] Adding UAL to ITRunner / hooklift flatbed trailers

### ISSUE THREAD

**Issue by jpries** [loki79uk/FS22_UniversalAutoload#196]
I love using the hooklift trailers and am wondering if you can add autoload for any of these mods. There is an "AutoLoad IT-Runner Platform" mod which is great, but it only loads factory pallets.

**Comment by loki79uk** [comment]
Are any of them inluded in the Add-on?  There are so many I can't keep track:
https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/blob/main/supportedMods.md

**Comment by jpries** [comment]
Yes, sorry despite extensive googling I had not found that list until after I posted. There are two mods with support: ITRTwo, and Transport Platform 4000/H.
