### ISSUE TITLE
Trailers won't pick up mushrooms or flowers in No Man's Land.  Can support be added for those?

### ISSUE THREAD

**Issue by anothergene** [loki79uk/FS22_UniversalAutoload#197]

**Comment by loki79uk** [comment]
It is possible to add a configuration of any custom container yourself, or you can make a request to add it to the Add-on:  https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/issues

It is pretty easy to do it yourself though.  First open your mod settings file in `%userprofile%\Documents\My Games\FarmingSimulator2022\modSettings\UniversalAutoload.xml`

Then add something similar to this (from Hof Bergmann), change the path to the correct mod and item and adjust the size to fit:
```xml
<containerConfiguration name="FS22_HofBergmann:beerKeg" containerType="ALL" sizeX="0.625" sizeY="0.775" sizeZ="0.625"/>
```

You can check the actual size in the GIANTS Editor (GE), or you can use the console command `ualImportUserConfigurations` to apply any edits you make to the local settings file without restarting the game.

_NOTE: I'm currently working on a new feature to dynamically measure the size of any pallets, so once I add this feature then all pallets and objects should be possible to load without any manual configuration._

**Comment by anothergene** [comment]
I'm on Xbox mostly so I assume I can't edit anything.

**Comment by loki79uk** [comment]
> I'm on Xbox mostly so I assume I can't edit anything.

Yes, sorry nothing I can do about that.  You can't use UAL at all on console, since it is a script mod.
