### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by hakkemanu** [loki79uk/FS22_UniversalAutoload#198]
Hey guy, is there a possible solution for Manually Loading logs on my own trailer ? like semi autoload
i wish i can drive with my wheelloader and logs, to my trailer, and he will pick the logs and stack into the trailer, i hope u understand me ^^

**Comment by loki79uk** [comment]
It is certainly on my list of things to do!  I can't promise it will be ready soon though.. :(

**Comment by hakkemanu** [comment]
Okay this is nice, maybe you can look at timber runner autoload script by
Kenny, on this trailer u can activate autoload, and if you drive a log near
the trigger he will pick up and stack

Loki_79 ***@***.***> schrieb am Do. 10. Aug. 2023 um 01:21:

**Comment by hakkemanu** [comment]
I have installed your script perfectly, the only thing that I missed is,
when u activate autoload, it stays on, and u need manually set it off

Manoloplay21 ***@***.***> schrieb am Do. 10. Aug. 2023 um 02:48:

**Comment by loki79uk** [comment]
> I have installed your script perfectly, the only thing that I missed is, when u activate autoload, it stays on, and u need manually set it off 

I do plan to add a log collection mode, the same as the existing bale collection mode.

**Comment by hakkemanu** [comment]
Hey loki, i have another question, can u tell me why this script automatically snaps to a specific vehicle part? how can i change this? 
![20230811085700_1](https://github.com/loki79uk/FS22_UniversalAutoload/assets/77816951/a470f885-0540-41fb-82df-6e96ee307b73)
![20230811085712_1](https://github.com/loki79uk/FS22_UniversalAutoload/assets/77816951/d072060a-0c3f-4218-833b-d08ddf86e79b)

**Comment by loki79uk** [comment]
Sorry, I missed this one - you can set a different node as the offset root using `offsetRoot` in the options.  Use the name of the node from the xml/i3d file.  You can either set it for one specific loading area, or in options if you want it to apply to all.

**Comment by hakkemanu** [comment]
no problem :) , but where can i set this ? what do u mean in options?

**Comment by hakkemanu** [comment]
i have tried this: offsetRoot="mks8_main_component1" but not working

**Comment by hakkemanu** [comment]
thx its working
