### ISSUE TITLE
!!!! Not properly load last line !!!!

### ISSUE THREAD

**Issue by TheGeremy** [loki79uk/FS22_UniversalAutoload#199]
![ual_issue](https://github.com/loki79uk/FS22_UniversalAutoload/assets/22389945/a6f779b1-688b-4ac7-aee2-9720603a4d54)

when I change the line, it looks OK :)

![line_edit](https://github.com/loki79uk/FS22_UniversalAutoload/assets/22389945/72fab010-7424-4338-b7df-b5e81da749f7)

**Comment by loki79uk** [comment]
Thanks, I will change it in the next build.

Do you know why the rows are offset towards the rear?  It looks to me like they are probably clipping at the front.  I'd try moving the loading area back slightly, or just make it a bit shorter.

**Comment by TheGeremy** [comment]
Yes that is just the uneven ground :)

**Comment by loki79uk** [comment]
Does this still happen with the latest version?
