### ISSUE TITLE
Bug - Unable to refill the Lizard MKS 32

### ISSUE THREAD

**Issue by tonto1992** [loki79uk/FS22_UniversalAutoload#2]
The R key doesn't work to refill the Lizard MKS 32 liquid trailer (found in the Animals section)
It doesn't show up as an option in the helper screen, nor can you press R and have it start filling.

**Comment by loki79uk** [comment]
Is that still happening after the fix to issue #1?  I updated the zip file with the latest version so that I can keep the same url for the beta release: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta

**Comment by loki79uk** [comment]
The MKS 32 is filling for me with the update-001:   ![image](https://user-images.githubusercontent.com/76516343/154863407-7cbebb6e-2a1b-4f15-a15b-2d36cd7a0be1.png)

**Comment by tonto1992** [comment]
Aha!  It is working :)  I guess I had the unfortunate timing of downloading this literally a half hour prior to your update.  I have confirmed in my game as well with your update.  Thank you for the work! :)  
 
 You can close this if you'd like (I don't know how often you keep issues open before closing) but it does appear fixed!

**Comment by loki79uk** [comment]
No problem - it is always the way!  Thanks for letting me know.  I'll close this one, but don't hesitate to open another issue if you get any more problems at all. 👍
