### ISSUE TITLE
Bread pallets won't stack

### ISSUE THREAD

**Issue by PatuNicolet** [loki79uk/FS22_UniversalAutoload#20]
Increasing sizeY to "0.900" for the bakeryBoxPallet in the ContainerTypes.xml file fixes this issue.

**Comment by loki79uk** [comment]
I think you are running on an old version, as I have already done that in the most recent updates (should now be 0.920).  I know this is a fairly fast moving test cycle, so sorry for any overlap!  Another version incoming soon, so be warned! :D
