### ISSUE TITLE
Customised Vehicle Won't Unload

### ISSUE THREAD

**Issue by Krapmeister** [loki79uk/FS22_UniversalAutoload#201]
I've tried customising a vehicle by inserting the code from the readme into the <vehicle> tag and adjusted the loading unloading offests correctly.

The vehicle loads perferctly, howver only unloads part of the payload using the shift-i command.  

I'm not a coder so have no idea how to fix this
[FS22_Iveco190Custom - Universal Overload.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/12318432/FS22_Iveco190Custom.-.Universal.Overload.zip)
[FS22_Iveco190Custom - Original.zip](https://github.com/loki79uk/FS22_UniversalAutoload/files/12318434/FS22_Iveco190Custom.-.Original.zip)

**Comment by loki79uk** [comment]
Maybe the same issue as these:
https://github.com/loki79uk/FS22_UniversalAutoload/issues/57
https://github.com/loki79uk/FS22_UniversalAutoload/issues/141

**Comment by loki79uk** [comment]
Did you manage to solve this?

**Comment by Krapmeister** [comment]
Unfortunately it was beyond my ability 🙂

**Comment by loki79uk** [comment]
It looks like you had just set the area too high:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/a1003b69-eedc-4d02-8d23-749527ffc3d4)

There is also no need to change the original mod, just add the settings to the file: `%userprofile%\Documents\My Games\FarmingSimulator2022\modSettings\UniversalAutoload.xml`

try using:
```xml
	<vehicleConfiguration configFileName="FS22_Iveco190Custom/iveco190.xml">
			<loadingArea offset="0.000 1.389 -2.000" width="2.75" height="2.50" length="4.65"/>
	</vehicleConfiguration>
```
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/d3b09196-68f4-45f5-ac30-04125d91f33c)
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/6696ce8b-dd1c-4941-bf61-17c2af6e4e43)

**Comment by Krapmeister** [comment]
You're a legend, that's got it working perfectly.  It's a great small load
truck and so useful to have the Universal Autoload feature.

Thanks

Stephen
