### ISSUE TITLE
Boeckmann KK 3018/27 H configuration

### ISSUE THREAD

**Issue by Keltibero** [loki79uk/FS22_UniversalAutoload#203]
Hello, I am trying to load a few small boxes on the KK 3018/27 H trailer with Universal Autoload, but it only loads one row when more should fit.

The configuration of the dimensions of the boxes is:
width="0.739" length="0.501" height="0.235" 

![fsScreen_2023_08_11_08_22_45](https://github.com/loki79uk/FS22_UniversalAutoload/assets/141994288/815eab35-9312-47db-930f-0284d5cc0210)

**Comment by loki79uk** [comment]
it looks like they fit together width and length ways.  What happens if you increase the height?

**Comment by Keltibero** [comment]
He incrementado la altura de las cajas a 0.335, ahora carga todas las cajas, pero hace algo raro.. sobrepasa la altura de carga del remolque. ¿¿?? 
![fsScreen_2023_08_11_09_07_26](https://github.com/loki79uk/FS22_UniversalAutoload/assets/141994288/c2ddd813-facb-4467-b8d8-55461ce02659)

**Comment by Keltibero** [comment]
Another test; I have now increased all the dimensions of the boxes 0.001 m above the dimensions of the object.

width="0.74" length="0.502" height="0.236"

..and does something funny


![fsScreen_2023_08_11_09_16_01](https://github.com/loki79uk/FS22_UniversalAutoload/assets/141994288/1725b9b6-39e5-4529-aa70-ce38e57fca83)

And one more test, new dimensions (I keep the width and length, but I increase the height by 0.001):

width="0.739" length="0.501" height="0.236"

![fsScreen_2023_08_11_09_21_38](https://github.com/loki79uk/FS22_UniversalAutoload/assets/141994288/89de1065-9217-4d37-ac13-27de2bf71ff6)

**Comment by loki79uk** [comment]
Hi, yes it can be very tricky to get the pallets just right.  I'm glad you got it working.  I'm currently working on a script to automatically detect pallet dimensions so that this will hopefully not be an issue in the future!
