### ISSUE TITLE
Add to fs19

### ISSUE THREAD

**Issue by HenriqueLima2** [loki79uk/FS22_UniversalAutoload#209]
Hello, I don't know if I can request it here but I would like if you could add this mod to the fs19 modhub for consoles I would be very grateful I have fs19 but I can only play it through GeforceNow so I can't play it so if you put it I I would be very happy.

**Comment by loki79uk** [comment]
Hi, sorry but even if I converted UAL to an FS19 version, it is no longer possible to upload to the FS19 ModHub AND it is not possible to release script mods for console anyway.
