### ISSUE TITLE
Question about options

### ISSUE THREAD

**Issue by TheChoseOne900** [loki79uk/FS22_UniversalAutoload#211]
I don't know if its me or im missing something, but there's no any option to disable auto loader? Like for example i want loading using a forklift but i don't want the pallets or whatever  auto stack on the trailer.. There's no option to turn that off or a hot key to do so. You can see the image for the reference and how pain it is loading manual with your mod on, i like your mod and its really helpful..
![UAL](https://github.com/loki79uk/FS22_UniversalAutoload/assets/44074742/4a5d8635-b3b9-4ca4-8b74-afd2b69d11b3)

**Comment by loki79uk** [comment]
There is a global option: `manualLoadingOnly` which will prevent autoloading, but still allow the manual loading - I think this is the opposite of what you want?

If you only want to disable manual loading, then you must make sure that each vehicle has:
`enableRearLoading="false"`
`enableSideLoading="false"`

There is no option to completely disable autoloading for a specific trailer, but as a workaround you could disable specific trailers using a custom config with an empty or zero size loading area.

**Comment by TheChoseOne900** [comment]
> There is a global option: `manualLoadingOnly` which will prevent autoloading, but still allow the manual loading - I think this is the opposite of what you want?
> 
> If you only want to disable manual loading, then you must make sure that each vehicle has: `enableRearLoading="false"` `enableSideLoading="false"`
> 
> There is no option to completely disable autoloading for a specific trailer, but as a workaround you could disable specific trailers using a custom config with an empty or zero size loading area.

Yeah i know. but the `manualLoadingOnly` just prevents to load pallets by parking on the side, but if you take a forklift soon you go put the pallet on the trailer the pallet just autoloding so im unable to put the pallet where i want. The `enableRearLoading="false"` `enableSideLoading="false"` have the inconvenience, every time i want to use the autoload i need to exit the game change mod files and enter the game again.. You cant change the option instead `manualLoadingOnly` we have something like `automaticLoadingOnly`... Thanks for answer me... Just think about a future update, using forklift no autoload, using trailer parking on side the goods autoload.. Have a nice day mate! And thanks for the hard work on mods!!!!

**Comment by loki79uk** [comment]
So you would like the option to toggle it?  Would you prefer per-vehicle, or global?  If I did add something like that I would probably make a global setting, but could be per vehicle too with a bit more work.  This is the kind of thing that will be much better when I have an in game settings menu.  I added one for Lumberjack, but have not found the time to do it for UAL. I will eventually!

**Comment by TheChoseOne900** [comment]
> So you would like the option to toggle it? Would you prefer per-vehicle, or global? If I did add something like that I would probably make a global setting, but could be per vehicle too with a bit more work. This is the kind of thing that will be much better when I have an in game settings menu. I added one for Lumberjack, but have not found the time to do it for UAL. I will eventually!

You already have a key in game to enable and disable `auto-bale mode`... You can just add one to auto-stack pallets if you want load it manual (if its possible)...
The way i see it is like, if i use a forklift to load cargo its because i don't want the cargo auto stack, i want that in the location i want, not the predestination location as the mode forces you...
Lumberjack?! Man great mod by the way.. For example to activate `super strength` you need press ALT twice. Same logic to this one, but maybe more hard and more work.. 

You don't need to go in hard work mode on this change =) 

**PS.: Or yes you can make a global option to enable and disable it, and when i want or need to auto load go to option and enable it, maybe this is the easiest way to go and less time consuming..**

Just to clear out, my "problem" is the auto-stack when i loading cargo by hand or forklift not the auto-load himself

**Comment by loki79uk** [comment]
I added this just now, but the problem is that these manually positioned pallets are not recognised by UAL, and so then cannot be loaded OR unloaded.  The unloading is the main issue, as it means you would have to manually unload everything too.

So the manually positioned pallet will then block any other pallets being loaded in that area until it is manually removed (see the first IBC here):
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/47f5d3ca-dda1-40f7-abc7-bcc142eac37c)

I'll try a different approach to see if I can get it to still "load" the object, but not actually position it.

**Comment by loki79uk** [comment]
Okay, that was easier than I expected - now unloads everything in the same position as it was loaded:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/22122096-d289-47c9-9618-f9fca5e35324)

**Comment by TheChoseOne900** [comment]
> Please try the latest version: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.4.6.0
> 
> You need to add `disableManualLoading="true"` into your mod settings xml. e.g:
> 
> ```
> <?xml version="1.0" encoding="utf-8" standalone="no"?>
> <universalAutoload showDebug="false" highPriority="true" manualLoadingOnly="false" disableManualLoading="true" disableAutoStrap="false" pricePerLog="0" pricePerBale="0" pricePerPallet="0" minLogLength="2">
> ```

I just do a little and fast test and that's it mate you nailed it, work like a charm... Thanks a lot mate...
