### ISSUE TITLE
Wrong loading order of big bags

### ISSUE THREAD

**Issue by bojanh66** [loki79uk/FS22_UniversalAutoload#217]
Hey, i didnt play FS22 for quite some time, so i updated your mod, but when i am in game trying to load big bags, this is what happens, so could you fix this ?
![fsScreen_2024_01_16_19_05_16](https://github.com/loki79uk/FS22_UniversalAutoload/assets/32069662/c28ed5a6-06a2-4a90-b31f-84c2e8db39c0)

**Comment by loki79uk** [comment]
Press Shift-F12 to show the debugging display, and look at where the zones are defined.  Send a screenshot zoomed in to the front if you can.

**Comment by bojanh66** [comment]
Hmmm, now it works, who knows what happened first time.
![fsScreen_2024_01_16_20_18_00](https://github.com/loki79uk/FS22_UniversalAutoload/assets/32069662/12071572-1d38-472d-8a04-29639bc219d7)
![fsScreen_2024_01_16_20_18_30](https://github.com/loki79uk/FS22_UniversalAutoload/assets/32069662/b9752958-c6c3-4fd5-86b6-fb4a529acc19)

**Comment by loki79uk** [comment]
It is too far forward though, you need to move the loading zone back so it does not overlap the trailer at the front:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/3128a0cc-3dc5-4301-8f70-9c51ca65ec51)
