### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by iwasthere83** [loki79uk/FS22_UniversalAutoload#220]
I didn't see an area to post questions so I am sorry for posting here. Is it possible to change the way round bales are stacked? I posted an example of what I am talking about. Either insight on what code to change or I guess a feature request to change the way it stacks. 

![roundbales](https://github.com/loki79uk/FS22_UniversalAutoload/assets/45979447/6f989a2e-fb12-4ffb-8f3c-bd4a0c966517)

**Comment by loki79uk** [comment]
If you switch to layer stacking, then round bales will stack like this.  I didn't want to add an extra key binding just for this, so I made that one a special case for round bales.

**Comment by iwasthere83** [comment]
Where would I find the layer stacking at? In the GUI of FS or one of the XMLs/LUAs?

**Comment by loki79uk** [comment]
No problem. I forgot to say that you need to bind a key, but I guess you found it! 😀

**Comment by loki79uk** [comment]
> Thank you!

There is some commented out code that loads in different shapes, for trailers that may or may not have supports for loading bales this way.  Please feel free to contact me on Discord if you are intereted in improving the options for this kind of stacking.

https://github.com/loki79uk/FS22_UniversalAutoload/blob/c184255cba2e0d867d35410fb0304a3823bc6c30/UniversalAutoload.lua#L3466
