### ISSUE TITLE
Lindner Unitrack platform only working with bales

### ISSUE THREAD

**Issue by Kiddoomer** [loki79uk/FS22_UniversalAutoload#221]
Hello, I'm having what seems to be a problem with the Lindner Unitrack platform (the one from Giants), as I can't have it working with pallets, it only autoloads bales.

I tried bigbags and bigbag pallet too but to no result too, I tried also lowering the side panels. Only all kinds of bales work with the autoload function, and manually deposit pallet on top of the trailer platform doesn't react.

**Comment by loki79uk** [comment]
How have you got it configured?  Are you using the ModHub Add-On?
https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/blob/main/supportedMods.md

**Comment by Kiddoomer** [comment]
Hello, yes sorry I just noticed I went on the wrong github, but yes I have installed both base mod and the modhub addon. And I do see the universal autoload symbol in the shop windows when buying the platform for the Lindner truck.

**Comment by loki79uk** [comment]
It seems to work okay for me:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/cce09c5d-09b0-442e-8b2c-be36a43acae8)

Can you press ctrl-shift-F12 to see the debugging view?

**Comment by Kiddoomer** [comment]
I just did a test, as I noticed your screen is from the first map Elmcreek, I just tried on that map and it worked ! But I went back on the map Haut-Beyleron where I was having the issue initially, activated the exact same mods, bought the exact same vehicle, platform and pallet, and it didn't work again. Just to be sure I tried on the third map Erlengrat and the problem appeared there too.

**Comment by loki79uk** [comment]
Does it work with the "Full Only" restriction turned off?  Try using the console command "ualAddPallets"
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/130dc380-396c-4cc2-975e-652e3fee30fd)

**Comment by loki79uk** [comment]
I also see it has the "Refill tipper" option available, so I don't think it will load things that can deposit the same fill type into the trailer.

**Comment by Kiddoomer** [comment]
Thank you for your tip about the type of ressource, it seems to have done the trick : 
![Capture d’écran_2024-02-24_22-23-41](https://github.com/loki79uk/FS22_UniversalAutoload/assets/7735200/4761b183-6040-4153-82b6-dabde181e688)
I probably had made a missclick between the tree sapling and sugar cane pallets, but yes apparently every pallet that can be transformed into a filling for a container doesn't work with this one. So to me the case is closed as it's more the Lindner pack mod causing the issue and not the universal autoload.
