### ISSUE TITLE
Problem using mod in MP server

### ISSUE THREAD

**Issue by CristianoCatta** [loki79uk/FS22_UniversalAutoload#223]
Me and my friend are sharing a server with 4netplayers and until now we installed any mod without problem until trying UA:
 the funny thing is that I have no problem using it (the server auto upload the mod for me) but my friend, after clicking "details" button, in icons menu under UA is written "Not available" without the image even if we downloaded it and manually put in mods folder. We also tried with UA mod hub add on but problem still remain: I have no problem using/loading it, my friend cant...we cant figure out where the problem is.  Little info, in SP my friend has no problem using the mod, it works perfectly.

Sorry for my english and thank you in advance.

Cristian

**Comment by loki79uk** [comment]
Are you using the exact version downloaded from ModHub?
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=237080

**Comment by Maghetto76** [comment]
Hi Loki79Uk,
I'm the friend, yes we are using the version you mentioned, 1.5.1.0

**Comment by loki79uk** [comment]
I'm not sure what to suggest other than deleting completly and re-download from ModHub.  Maybe try clearing the DNS cache on the not-working pc?  It works for me:

![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/c671fbcf-e584-44e4-af57-43d669bf1501)

![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/52db0f32-c45f-49b0-8bdb-fe1868cd8c8c)

**Comment by Maghetto76** [comment]
I deleted the mods on the server and then reinstalled them and now it's working, thanks for your support.
