### ISSUE TITLE
the mod is not showing on mod select screen

### ISSUE THREAD

**Issue by kkss132435** [loki79uk/FS22_UniversalAutoload#225]
i do all steps correct but its not working 
here is the link of mod
link:https://drive.google.com/file/d/1ED9if_n5MvalPiAg92ERA68A6bv8sqRf/view?usp=drive_link
Orijinal link of the mod
Link:https://drive.google.com/file/d/12hiJUALGkLAd8aE-vI0dmh12FLbZ1ae0/view?usp=drivesdk

**Comment by loki79uk** [comment]
I have not tried yet myself, but I think it could be because you have a space in the path name.  Try using an underscore.

**Comment by kkss132435** [comment]
I

**Comment by kkss132435** [comment]
I tried but stil not working

**Comment by loki79uk** [comment]
You have zipped an extra folder inside the zip file.  All of the files need to be in the root of the zip folder.

**Comment by kkss132435** [comment]
Hey thanks for advisings its working now big thanks again

19 Nis 2024 Cum 00:14 tarihinde Loki_79 ***@***.***> şunu
yazdı:
