### ISSUE TITLE
Bulk products pallets can't be loaded

### ISSUE THREAD

**Issue by Illgib81** [loki79uk/FS22_UniversalAutoload#226]
I have a strange issue on a vehicle i've added autoload, and it's the first time happening.

I can load almost all pallets but the ones that have a tippable fill inside, like grapes, roots, canes and mineral feed, it won't appear the option to load in the f1 menu, anything else works as usual.

I added to other vehicles and it works as intended.
Am i missing something or it's a recent game update that messed up things?
Thanks.

Edit some typo.

**Comment by loki79uk** [comment]
This behaviour is intentional.  If the trailer has a bulk fill capability then UAL won't load them, because otherwise they just tip into the trailer and fill it up with bulk filltype, the same as if you place them there manually.

**Comment by Illgib81** [comment]
I "fixed" the grape one, i made a mos to laod grapes on all trailers and makes no loading grapes, but if i disable it it load the grapes pallet, still doesn't load the others, and in my case it load pallets even if i have something loaded in the tipper.

But as i said, it happen only for this vehicle, because others were i added the UA load all the pallets with no problem at all, even the one this one refuse.
I'm really at loss.

**Comment by Illgib81** [comment]
![fsScreen_2024_04_27_00_59_03](https://github.com/loki79uk/FS22_UniversalAutoload/assets/47069337/7724a7a7-542c-4b7f-8330-b9c6b9576724)
![fsScreen_2024_04_27_00_59_14](https://github.com/loki79uk/FS22_UniversalAutoload/assets/47069337/54e8a871-9fce-47b8-ab2d-f963b18517bd)
As you can see, both same exact options, but one doesn't register some pallets.

**Comment by Illgib81** [comment]
Addendum, in the screenshots i tried again a double configurations on the truck, tipper and bale loader, but it doesn't matter, it refuse to register some pallets.

**Comment by Illgib81** [comment]
Maybe i found the solution, and maybe it can be usefull for everyone else in the same situation, or can even be integrated in the script or modified somehow, if it's related.

To work properly the vehicle should have at least two configurations in case of a tipper, or else the loading volume will iterferee with the autoloader.
But no matter what it won't accept some pallets.

Thinking about i removed the fillvolume line completely instead of setting to 0, so the script won't crash against a filltypecategories, and now it load all pallets whitout problems, and i can use my grapes for all mod aswell.

![Untitled-1](https://github.com/loki79uk/FS22_UniversalAutoload/assets/47069337/7204c36e-bcbc-4366-bf50-b74ef0896ccb)

**Comment by Illgib81** [comment]
Sorry for highjacking the thread, but i'm actually stocked how the game or the script, or both, handle the filltypes.

Bulk it's probably the same filltype of those pallets, but there are other vehicles with the same configuration as mine that work instead, no matter the double bulk fillunit, and other don't, like the two vanilla small utility cars.

The previous solution wasn't pratical since i got a couple of warning about the missing fillunits, i've replaced with a filltypes=air to remove the logs entry.

But i can't get why some works and others, similar or same vehicles, don't.

**Comment by loki79uk** [comment]
As I said before, it is not a "crash" in the script, it is intentional.  If we don't do this then these pallets will discharge the fill type into the trailer and the pallets will disappear.

There is a function here to check if the pallet will discharge: https://github.com/loki79uk/FS22_UniversalAutoload/blob/db5a72245372e13ab61545fa7bda6e58b87b1dae/UniversalAutoload.lua#L2302-L2318
Then it prevents loading when that function is true: https://github.com/loki79uk/FS22_UniversalAutoload/blob/db5a72245372e13ab61545fa7bda6e58b87b1dae/UniversalAutoload.lua#L2948-L2950

**Comment by Illgib81** [comment]
I said crash in commas like a car crashing against a wall, not in a programming way.
Similar vehicles sets like mine, with separated flat bed and loading box, works, others don't instead, i checked all the vehicles i have similar the one i'm modding, comparing the xmls and the i3d, but i can't understand what makes some works and others don't.

Like Iveco trucks, the Minor or the Lizard farm Trailer, all have bale load and grain wagon configurations, all filltypes sets to 0 bulk and can load all pallets, mine have the options separated aswell but don't, i resolved changing the filltype for the loading configuration from bulk to air, but it's not a real solution, as i would like to understand "the why" doesn't work if sets like the one working.

Maybe it's not even an UA issue, but game or vehicle related.

**Comment by loki79uk** [comment]
The bale load configuration has to be separate from the bale configuration.  Try copying the settings exactly from a working one.

**Comment by Illgib81** [comment]
Thta's what i did, studing from several similar vehicles, but still i had to place an "air" fillvolume to make it work.

<?xml version="1.0" encoding="utf-8" standalone="no"?>
<vehicle type="barkas">
    <storeData>
		<name>
			<en>Barkas flatbed</en>
		</name>
        <specs>
            <power>45</power>
            <maxSpeed>69</maxSpeed>
        </specs>
        <functions>
            <function>$l10n_function_truck</function>
        </functions>
        <image>Store/store.dds</image>
        <price>2105</price>
        <lifetime>600</lifetime>
        <rotation>0</rotation>
        <brand>Lizard</brand>
        <category>cars</category>
    </storeData>

    <base>
	    <typeDesc>$l10n_typeDesc_car</typeDesc>
        <filename>barkas.i3d</filename>
        <size width="3.5" length="5.5"/>
        <components>
            <component centerOfMass="0 0.8 1" solverIterationCount="10" mass="1900" />
        </components>
        <schemaOverlay attacherJointPosition="0 0" name="CAR" />
		<sounds filename="Sounds/Favorit_zvuky.xml" />
    </base>	

    <wheels>
        <wheelConfigurations>
            <wheelConfiguration name="Standart" price="0">
                <wheels autoRotateBackSpeed="2.5">
                    <wheel isLeft="false" hasTireTracks="true" hasParticles="true">
                        <physics rotSpeed="1"  radius="0.41" width="0.5" restLoad="0.6" repr="0>0|0" forcePointRatio="0.45" initialCompression="50" suspTravel="0.15" spring="10" damper="10"/>
                    </wheel>
                    <wheel  isLeft="true" hasTireTracks="true" hasParticles="true">
                        <physics rotSpeed="1"  radius="0.41" width="0.5" restLoad="0.6" repr="0>0|1" forcePointRatio="0.45" initialCompression="50" suspTravel="0.15" spring="10" damper="10"/>
                    </wheel>
                    <wheel  isLeft="false" hasTireTracks="true" hasParticles="true">
                        <physics rotSpeed="0"  radius="0.41" width="0.5" restLoad="0.56" repr="0>0|2" forcePointRatio="0.45" initialCompression="50" suspTravel="0.15" spring="10" damper="10"/>
                    </wheel>
                    <wheel  isLeft="true" hasTireTracks="true" hasParticles="true">
                        <physics rotSpeed="0" radius="0.41" width="0.5" restLoad="0.56" repr="0>0|3" forcePointRatio="0.45" initialCompression="50" suspTravel="0.15" spring="10" damper="10"/>
                    </wheel>
                </wheels>
            </wheelConfiguration>
        </wheelConfigurations>
        <ackermannSteeringConfigurations>
            <ackermannSteering rotSpeed="40" rotMax="35" rotCenterWheel1="3" rotCenterWheel2="4"/>
        </ackermannSteeringConfigurations>
    </wheels>  
	
	<lights>
		<sharedLight linkNode="0>10" filename="$data/shared/assets/lights/lizard/rearLight04_left.xml" />
        <sharedLight linkNode="0>9" filename="$data/shared/assets/lights/lizard/rearLight04_right.xml" />
	    <states>
            <state lightTypes="1" />
			<state lightTypes="2" />
        </states>
		
		<realLights>
            <low>
                <light node="0>7|2" lightTypes="1"/>
                <light node="0>7|0" lightTypes="2"/>
				<light node="0>7|1" lightTypes="2"/>
                <light node="0>5" lightTypes="1 2"/>
				<light node="0>13|15" lightTypes="1 2"/>
				<turnLightLeft node="0>8|1"/>
                <turnLightRight node="0>8|0"/>
                <brakeLight node="0>6"/>
            </low>
            <high>
                <light node="0>7|2" lightTypes="1"/>
                <light node="0>7|0" lightTypes="2"/>
				<light node="0>7|1" lightTypes="2"/>
                <light node="0>5" lightTypes="1 2"/>
				<light node="0>13|15" lightTypes="1 2"/>
				<turnLightLeft node="0>8|1"/>
                <turnLightRight node="0>8|0"/>
                <brakeLight node="0>6"/>
            </high>
        </realLights>
		
        <defaultLights>
            <defaultLight shaderNode="0>13|0|37|0|0|1" lightTypes="1 2"/>
			<defaultLight shaderNode="0>13|0|37|0|0|2" lightTypes="1 2"/>
        </defaultLights>
		
        <turnLights>
		    <turnLightRight shaderNode="0>13|0|37|3|1|0|0"/>
            <turnLightLeft shaderNode="0>13|0|37|3|0|0|0"/>
        </turnLights>
		
		<beaconLights>
            <beaconLight node="0>14" filename="$data/shared/assets/beaconLights/lizard/beaconLight01.xml"/>
        </beaconLights>

        <sounds>
            <toggleLights linkNode="0>" template="SWITCH_01"/>
            <turnLight linkNode="0>" template="SWITCH_TURNLIGHT"/>
        </sounds>
    </lights>
	
	<design2Configurations>
        <design2Configuration name="$l10n_no_beacon" price="0">
            <objectChange node="0>14" visibilityActive="false"/>
        </design2Configuration>
        <design2Configuration name="$l10n_beacon1" price="100">
            <objectChange node="0>14" visibilityActive="true"/>
        </design2Configuration>
    </design2Configurations>
	
    <configurationSets>
        <configurationSet name="6000">
            <configuration name="fillVolume"   index="1"/>
            <configuration name="fillUnit"     index="1"/>
		</configurationSet>
        <configurationSet name="Loading platform">
            <configuration name="fillVolume"   index="1"/>
            <configuration name="fillUnit"     index="2"/>
			<configuration name="tensionBelts" index="1"/>
        </configurationSet>
    </configurationSets>

    <enterable isTabbable="true">
        <exitPoint node="0>0|9"/>
        <enterReferenceNode node="0>"/>
		<cameras count="2">
            <camera node="0>0|4|0" rotatable="true" rotateNode="0>0|4" limit="true" useWorldXZRotation="true" rotMinX="-1.4" rotMaxX="1" transMin="4" transMax="40" translation="0 0 5.5" rotation="-17.5 180 0">
            </camera>
            <camera node="0>0|5" rotatable="true" limit="true" rotMinX="-1.1" rotMaxX="0.4" transMin="0" transMax="0" useMirror="true" isInside="true" positionSmoothingParameter="0"  />
        	<camera node="0>15" rotatable="true" limit="true" rotMinX="-1.1" rotMaxX="0.4" transMin="0" transMax="0" useMirror="true" isInside="true" positionSmoothingParameter="0"  />	
		</cameras>

		<characterNode node="0>13|0|31|0" cameraMinDistance="0.1" spineRotation="-90 0 90" >
            <target ikChain="rightFoot" targetNode="0>13|0|31|1" />
            <target ikChain="leftFoot"  targetNode="0>13|0|31|2" />
            <target ikChain="rightArm"  targetNode="0>13|0|29|0|0|0" poseId="wideFingers"/>
            <target ikChain="leftArm"   targetNode="0>13|0|29|0|0|1" poseId="wideFingers"/>
        </characterNode>
		
		<passengerSeats>
			<passengerSeat node="0>18|0" exitPoint="0>18|0|6" outdoorCameraIndex="1">
				<camera node="0>18|0|0" rotatable="true" limit="true" rotMinX="-1.1" rotMaxX="0.4" transMin="0" transMax="0" useMirror="true" isInside="true" useOutdoorSounds="true" positionSmoothingParameter="0" />
				<characterNode node="0>18|0|1" cameraMinDistance="0.5" spineRotation="-90 0 90">
					<target ikChain="rightFoot" targetNode="0>18|0|3" />
					<target ikChain="leftFoot"  targetNode="0>18|0|2" />
					<target ikChain="rightArm"  targetNode="0>18|0|5" poseId="narrowFingers"/>
					<target ikChain="leftArm"   targetNode="0>18|0|4" poseId="flatFingers"/>
				</characterNode>
			</passengerSeat>
		</passengerSeats>
    </enterable>

    <motorized>
		<consumerConfigurations>
            <consumerConfiguration>
                <consumer fillUnitIndex="1" usage="30" fillType="diesel" /> 
            </consumerConfiguration>
        </consumerConfigurations>
		<motorConfigurations>	
		 <motorConfiguration name="Barkas original" hp="45" price="0">
                <motor torqueScale="0.71" minRpm="900" maxRpm="2200" brakeForce="1.2" maxForwardSpeed="80" maxBackwardSpeed="15" lowBrakeForceScale="0.2" lowBrakeForceSpeedLimit="1">
                    <torque normRpm="0.1" torque="0.35"/>
                    <torque normRpm="0.2" torque="0.65"/>
                    <torque normRpm="0.3" torque="0.85"/>
                    <torque normRpm="0.85" torque="1"/>
                    <torque normRpm="1" torque="0.65"/>
                </motor>
				<transmission autoGearChangeTime="0.5" gearChangeTime="0.4" axleRatio="12" startGearThreshold="0.35" name="$l10n_info_transmission_manual">
                    <directionChange useGear="true" useGroup="false" changeTime="0.5"/>
                    <forwardGear gearRatio="2.55" name="1" />
                    <forwardGear gearRatio="2.00" name="2" />
                    <forwardGear gearRatio="1.45" name="3" />
                    <forwardGear gearRatio="1.00" name="4" />
                    <backwardGear gearRatio="3.20" name="R"/>
                </transmission>            
				</motorConfiguration>
		 </motorConfigurations>		

		<differentialConfigurations>
            <differentialConfiguration>
                <differentials>
                    <differential torqueRatio="0.5" maxSpeedRatio="1.2" wheelIndex1="1" wheelIndex2="2"/>
                    <differential torqueRatio="0.5" maxSpeedRatio="1.2" wheelIndex1="3" wheelIndex2="4"/>
                    <differential torqueRatio="0.5" maxSpeedRatio="1.2" differentialIndex1="1" differentialIndex2="2"/>
                </differentials>
            </differentialConfiguration>
        </differentialConfigurations>

		<exhaustEffects>
            <exhaustEffect node="0>0|14" filename="$data/effects/exhaust/exhaust.i3d" minRpmColor="0.8 0.8 0.8 0.8" maxRpmColor="0.1 0.1 0.1 0.1" minRpmScale="0.02" maxRpmScale="0.3" />
        </exhaustEffects>
		<dashboards>
			<dashboard displayType="ANIMATION" valueType="motorTemperature" animName="tempDisplay" groups="MOTOR_ACTIVE"/>  
            <dashboard displayType="ANIMATION" valueType="speed" intensity="0.2" animName="speedDisplay"   groups="MOTOR_ACTIVE"/>
            <dashboard displayType="ANIMATION" valueType="fuel" intensity="0.2" animName="fuelDisplay"   groups="MOTOR_ACTIVE"/>
		</dashboards>
    </motorized>

    <drivable>
	    <sounds>
            <waterSplash template="WATER_SPLASH_01" />
        </sounds>
        <steeringWheel node="0>13|0|29|0|0" indoorRotation="540" outdoorRotation="60"/>
    </drivable>

	<attacherJoints>
        <attacherJoint node="0>0|10" jointType="trailer" lowerRotLimit="10 70 50" upperRotationOffset="0" allowsJointLimitMovement="false" canTurnOnImplement="false" comboTime="1">
            <schema position="1 0" rotation="0" invertX="false"/>
            <attachSound template="ATTACH_01" linkNode="0>" />
        </attacherJoint>
        <attacherJoint node="0>0|10" jointType="trailerLow" lowerRotLimit="10 70 50" upperRotationOffset="0" allowsJointLimitMovement="false" canTurnOnImplement="false" comboTime="1">
            <schema position="1 0" rotation="0" invertX="false"/>
            <attachSound template="ATTACH_01" linkNode="0>" />
        </attacherJoint>
    </attacherJoints>
	
	<cylindered>
	    <movingTools>
			<movingTool node="0>0|26|1" playSound="true"/>
            <movingTool node="0>0|26|2" playSound="true"/>
            <movingTool node="0>0|26|3" playSound="true"/>
		<movingTool node="0>13|0|25" playSound="true" >
                <controls axis="AXIS_CRANE_ARM" invertAxis="true" mouseSpeedFactor="0.6" iconName="FRONTLOADER_ARM_ROTATE" />
                <animation animName="jobbajto" animSpeed="1" />
        </movingTool>
		<movingTool node="0>13|0|26" playSound="true" >
                <controls axis="AXIS_CRANE_ARM4" invertAxis="true" mouseSpeedFactor="0.6" iconName="FRONTLOADER_ARM_ROTATE" />
                <animation animName="balajto" animSpeed="1" />
        </movingTool>

		<sounds>
            <hydraulic template="PICKUP_TRUNK" linkNode="0>"/>
        </sounds> 
		 </movingTools>
    </cylindered>

    <animations>
		<animation name="fuelDisplay">
            <part node="0>13|0|14|8|2" startTime="0" endTime="1" startRot="0 -105 0" endRot="0 0 0"/>
        </animation>
        <animation name="speedDisplay">
            <part node="0>13|0|14|8|0" startTime="0" endTime="1" startRot="0 0 0" endRot="0 -136 0"/>
        </animation>
		<animation name="tempDisplay">
            <part node="0>13|0|14|8|1"  startTime="0" endTime="1" startRot="0 81 0" endRot="0 -6 0" />
        </animation>
		<animation name="panelright">
            <part node="0>0|26|1" startTime="0" endTime="1" startRot="0 0 0" endRot="0 0 180"/>
			<part node="0>0|26|2" startTime="0" endTime="1" startRot="0 0 0" endRot="0 0 -180"/>
			<part node="0>0|26|3" startTime="0" endTime="1" startRot="0 0 0" endRot="-177 0 0"/>
        </animation>		
		<animation name="jobbajto">
            <part node="0>13|0|25" startTime="0" endTime="1" startRot="0 0 0" endRot="0 60 0" />
        </animation>
        <animation name="balajto">
            <part node="0>13|0|26" startTime="0" endTime="1" startRot="0 0 0" endRot="0 -60 0" />
        </animation>
    </animations>
	
	<baseMaterial>
        <material name="test" baseNode="0>13|3">
            <shaderParameter name="colorMat0" value="W50_ORANGE"/>
        </material>
		<material name="test2" baseNode="0>13|16">
            <shaderParameter name="colorMat0" value="W50_ORANGE"/>
        </material>
        <material name="ajto1" baseNode="0>13|0|25|7">
            <shaderParameter name="colorMat0" value="W50_ORANGE"/>
        </material>
        <material name="ajto2" baseNode="0>13|0|26|7">
            <shaderParameter name="colorMat0" value="W50_ORANGE"/>
        </material>
        <material name="lok" baseNode="0>13|8">
            <shaderParameter name="colorMat1" value="W50_ORANGE"/>
        </material>
    </baseMaterial>
	
    <baseMaterialConfigurations price="50" useDefaultColors="true" defaultColorIndex="4">
		<baseMaterialConfiguration  name="$l10n_color_lightblue" color="W50_LIGHTBLUE"/>
        <baseMaterialConfiguration  name="$l10n_ui_colorRed" color="W50_RED"/>
        <baseMaterialConfiguration  name="$l10n_color_darkgreen" color="W50_DARKGREEN"/>
        <baseMaterialConfiguration  name="$l10n_color_helvetia" color="W50_HELVETIA"/>
        <baseMaterialConfiguration  name="$l10n_ui_colorGrey" color="W50_GREY"/>
        <baseMaterialConfiguration  name="$l10n_color_lightbrown" color="W50_LIGHTBROWN"/>
        <baseMaterialConfiguration  name="$l10n_color_lightgreen" color="W50_LIGHTGREEN"/>
        <baseMaterialConfiguration  name="$l10n_color_burgundy" color="W50_BURGUNDY"/>
        <baseMaterialConfiguration  name="$l10n_color_yellowgreen" color="W50_YELLOWGREEN"/>
        <baseMaterialConfiguration  name="$l10n_ui_colorWhite" color="W50_WHITE"/>
        <baseMaterialConfiguration  name="$l10n_ui_colorOrange" color="W50_ORANGE"/>
        <baseMaterialConfiguration  name="$l10n_color_lightgrey" color="W50_LIGHTGREY"/>
        <baseMaterialConfiguration  name="$l10n_color_greenbrown" color="W50_GREENBROWN"/>
        <baseMaterialConfiguration  name="$l10n_ui_colorBlue" color="W50_BLUE"/>
        <baseMaterialConfiguration  name="$l10n_color_nva" color="NVA_GREEN"/>
        <material name="test" shaderParameter="colorMat0" />
		<material name="test2" shaderParameter="colorMat0" />
        <material name="ajto1" shaderParameter="colorMat0" />
        <material name="ajto2" shaderParameter="colorMat0" />
    </baseMaterialConfigurations>
	
	<designMaterialConfigurations price="50" useDefaultColors="true" defaultColorIndex="4">
		<designMaterialConfiguration name="$l10n_color_beige" color="W50_BEIGE"/>
		<designMaterialConfiguration name="$l10n_color_lightblue" color="W50_LIGHTBLUE"/>
		<designMaterialConfiguration name="$l10n_ui_colorRed" color="W50_RED"/>
		<designMaterialConfiguration name="$l10n_color_darkgreen" color="W50_DARKGREEN"/>
		<designMaterialConfiguration name="$l10n_color_helvetia" color="W50_HELVETIA"/>
		<designMaterialConfiguration name="$l10n_ui_colorGrey" color="W50_GREY"/>
		<designMaterialConfiguration name="$l10n_color_lightbrown" color="W50_LIGHTBROWN"/>
		<designMaterialConfiguration name="$l10n_color_lightgreen" color="W50_LIGHTGREEN"/>
		<designMaterialConfiguration name="$l10n_color_burgundy" color="W50_BURGUNDY"/>
		<designMaterialConfiguration name="$l10n_color_yellowgreen" color="W50_YELLOWGREEN"/>
	    <designMaterialConfiguration name="$l10n_ui_colorWhite" color="W50_WHITE"/>
        <designMaterialConfiguration name="$l10n_ui_colorOrange" color="W50_ORANGE"/>
		<designMaterialConfiguration name="$l10n_color_lightgrey" color="W50_LIGHTGREY"/>
		<designMaterialConfiguration name="$l10n_color_greenbrown" color="W50_GREENBROWN"/>
        <designMaterialConfiguration name="$l10n_ui_colorBlue" color="W50_BLUE"/>
		<designMaterialConfiguration name="$l10n_color_nva" color="NVA_GREEN"/>
        <material name="lok" shaderParameter="colorMat1" />	
    </designMaterialConfigurations>
	
	<dashboard>
        <groups>
            <group name="MOTOR_STARTING" isMotorStarting="true"/>
            <group name="MOTOR_ACTIVE"   isMotorStarting="true" isMotorRunning="true"/>
        </groups>
    </dashboard>
	
    <suspensions>	
        <suspension useCharacterTorso="true" weight="90" minRotation="0 -5 -5" maxRotation="0 5 5" suspensionParametersY="7 1" suspensionParametersZ="7 1" />
	</suspensions>

	<fillUnit>
        <fillUnitConfigurations>
            <fillUnitConfiguration>
                <fillUnits>
					<fillUnit unitTextOverride="$l10n_unit_literShort" showOnHud="false" showInShop="false" fillTypes="diesel" capacity="42" />
					<fillUnit capacity="6000" fillTypeCategories="BULK" unitTextOverride="$l10n_unit_literShort">
						<exactFillRootNode node="0>20|1"/>
					</fillUnit>
		        </fillUnits>
            </fillUnitConfiguration>
			
			<fillUnitConfiguration>
                <fillUnits>
					<fillUnit unitTextOverride="$l10n_unit_literShort" showOnHud="false" showInShop="false" fillTypes="diesel" capacity="42" />
					<fillUnit capacity="42" fillTypes="air" unitTextOverride="$l10n_unit_literShort" showOnHud="false" showInShop="false"/>
		        </fillUnits>
					<objectChange node="0>0|26|1" visibilityActive="false" />
					<objectChange node="0>0|26|1|0" compoundChildActive="false" compoundChildInactive="true" />
					<objectChange node="0>0|26|2" visibilityActive="false" />
					<objectChange node="0>0|26|2|0" compoundChildActive="false" compoundChildInactive="true" />
					<objectChange node="0>0|26|3" visibilityActive="false" />
					<objectChange node="0>0|26|3|0" compoundChildActive="false" compoundChildInactive="true" />
            </fillUnitConfiguration>
        </fillUnitConfigurations>
    </fillUnit>

	<fillVolume>
		<fillVolumeConfigurations>
			<fillVolumeConfiguration>
				<volumes>
					<volume node="0>20|0" fillUnitIndex="2" maxDelta="0.30" maxAllowedHeapAngle="25"  />
				</volumes>
			</fillVolumeConfiguration>
		</fillVolumeConfigurations>
		<unloadInfos>
            <unloadInfo>
                <node node="0>20|2" width="1.5" length="1.0"/>
            </unloadInfo>
		</unloadInfos>
	</fillVolume>
	
	<dischargeable>
        <dischargeableConfigurations>
            <dischargeableConfiguration>
				<dischargeNode node="0>20|3" emptySpeed="500" fillUnitIndex="2" unloadInfoIndex="1" allowAIDischarge="true" canDischargeToGround="false" canDischargeToObject="true" canStartDischargeAutomatically="false">
                    <info width="1.5" length="1.5" />
                </dischargeNode>
            </dischargeableConfiguration>
        </dischargeableConfigurations>			
    </dischargeable>
	
	<foliageBending>
		<bendingNode minX="-1.1" maxX="1.1" minZ="-2.283" maxZ="2.443" yOffset="0.3" />
	</foliageBending>

    <honk>
        <sound file="Sounds/horn.wav" innerRadius="35">
            <volume outdoor="1"/>
        </sound>
    </honk>

    <tensionBelts>
        <tensionBeltsConfigurations>
            <tensionBeltsConfiguration>
                <tensionBelts linkNode="0>0|36" jointNode="0>" width="0.075" maxEdgeLength="0.1" geometryBias="0.01" ratchetPosition="0.2" defaultOffset="0.1" defaultOffsetSide="0.1" defaultHeight="4" >
                    <tensionBelt startNode="0>0|36|0" endNode="0>0|36|0|0" offsetLeft="0.2" />
                    <tensionBelt startNode="0>0|36|1" endNode="0>0|36|1|0" />
					<tensionBelt startNode="0>0|36|2" endNode="0>0|36|2|0" />
					<tensionBelt startNode="0>0|36|3" endNode="0>0|36|3|0" />
					<tensionBelt startNode="0>0|36|4" endNode="0>0|36|4|0" />
                    <tensionBelt startNode="0>0|36|5" endNode="0>0|36|5|0" offsetRight="0.2" />
                </tensionBelts>
            </tensionBeltsConfiguration>
        </tensionBeltsConfigurations>
    </tensionBelts>	

    <foliageBending>
        <bendingNode minX="-1.15" maxX="1.15" minZ="-3" maxZ="3" yOffset="0.5" />
    </foliageBending>

	<ai>
        <collisionTrigger node="0>3"/>
    </ai>
	
    <livestockTrailer>
		<animal type="chicken" node="0>19|0" numSlots="25" />
		<animal type="sheep" node="0>19|2" numSlots="4" />
		<animal type="pig" node="0>19|1" numSlots="4" />
		<animal type="cow" node="0>19|3" numSlots="2" />
    </livestockTrailer>
	
	<wearable wearDuration="480" workMultiplier="5" fieldMultiplier="2" />
    <washable dirtDuration="130" washDuration="1" workMultiplier="4"/>
	
	<universalAutoLoad>
		<vehicleConfigurations>
			<vehicleConfiguration selectedConfigs="2">
				<loadingArea offset="0.000 0.97 0.261" width="2.5" height="2" length="3.5"/>
			</vehicleConfiguration>
		</vehicleConfigurations>
	</universalAutoLoad>

</vehicle>

But it was probably a problem with the vehicle itself, maybe was already ported from a previous version as i had problems with the collisions never disabling even if directly told them to.

**Comment by loki79uk** [comment]
I'm closing this as I think it is resolved, but please re-open or message me if you are still having trouble.
