### ISSUE TITLE
Use debug command to get area coordinates

### ISSUE THREAD

**Issue by Tensuko** [loki79uk/FS22_UniversalAutoload#227]
Hi loki, I did read your description and it says:

ualCreateBoundingBox            - Create a bounding box around all loaded pallets (kind of pointless)

If you could print requierd informations to add autoload to a trailer or vehicle, player can place pallets in every corner of the area and that command creates a box arround it. Then you add those values into the information.
Maybe thats a helpfull tool that way?

**Comment by loki79uk** [comment]
Hi, yes I did originally plan to use it in that way, as well as a different method to check for remaining space.  I am stuggging to find time for any new features at the moment.

**Comment by loki79uk** [comment]
Closing as not planned.  I'm actually now working on an algorithm to automatically identify the loading area on any vehicle.  I don't know if it will be possible for all vehicles, but watch this space..

**Comment by Tensuko** [comment]
That sounds interesting.
Something like biggest fitting box in between colisions or something.

**Comment by loki79uk** [comment]
Yes, a combination of ray casts and searching inside a box for collisions.  It is fairly easy to do simple trailers, but not many are simple! :D

**Comment by Tensuko** [comment]
Do you have Discord?

**Comment by loki79uk** [comment]
> Do you have Discord?

Yes, loki_79 (originally Loki_79#2864)
