### ISSUE TITLE
AutoLoad Wood selectable lenght

### ISSUE THREAD

**Issue by Tensuko** [loki79uk/FS22_UniversalAutoload#228]
If you could select the lenght of the wood, would help with sorting out those "short ends" after cutting the trees.
I think it would be enough to have a simple selection in meters (like the harvesters) and load everything that is slightly bigger or slightly smaller then the selected lenght.
e.g. selected 12m, load 11m - 13m logs.

**Comment by loki79uk** [comment]
You can already do this by setting `minLogLength` in your mod settings file.

as a global setting for all vehicles: 
https://github.com/loki79uk/FS22_UniversalAutoload/blob/db5a72245372e13ab61545fa7bda6e58b87b1dae/UniversalAutoload.lua#L65

or for an individual trailer:
https://github.com/loki79uk/FS22_UniversalAutoload/blob/db5a72245372e13ab61545fa7bda6e58b87b1dae/UniversalAutoload.lua#L117

It is not adjustable on the fly though.  I do plan to make a GUI settings editor, there are just too many other things on my plate at the moment!

**Comment by Tensuko** [comment]
Okay thats nice. Thanks for the Info!
