### ISSUE TITLE
Cannot make this work with Flatbed truck.

### ISSUE THREAD

**Issue by ScootersWorkbench** [loki79uk/FS22_UniversalAutoload#23]
I've added specializations for "dynamicMountAttacher" & "tensionBelts",  that didn't work.   I added the specialization for "dynamicMountAttacherTrailer" & "tensionBelts" and that also did not work.   There were no errors, but the Autoload Menu would not display when in the truck and the pallets would not autoload either.   Is it possible to put this on a "baseDrivable" vehicle?

Thanks!
Scooter

**Comment by ddewar** [comment]
Current version of this mod only works for vehicles of type trailer right now. 

https://github.com/loki79uk/FS22_UniversalAutoload/blob/main/UniversalAutoloadInstaller.lua#L13

**Comment by ScootersWorkbench** [comment]
:(  thanks for the prompt response.  Will this be put in the backlog for a future update?

**Comment by loki79uk** [comment]
I have got plans to add to vehicles (pickups, etc), but I want to get all the main bugs with trailers identified and fixed before I risk introducing any more! :D  If you want to get ahead of me, then you can edit that line linked above to include the vehicle type that you are trying to add.

**Comment by loki79uk** [comment]
Which truck are you trying to install this on?  Is it one of your own, or are you editing another mod?  I only ask because I'm adding this now, so I could add as a supported vehicle if it helps you.

**Comment by loki79uk** [comment]
See if it works now with this version: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-019

**Comment by loki79uk** [comment]
Closing for housekeeping.  Please reopen or start a new issue if you have any problems installing it now.

**Comment by ScootersWorkbench** [comment]
It's flatbed truck,  not anything ingame.
