### ISSUE TITLE
QoL improvement, loading area change for some vehicles

### ISSUE THREAD

**Issue by harokyang** [loki79uk/FS22_UniversalAutoload#230]
I want to complain about some default vehicle loading area setup

1. In xml, the Bremer Transport Wagen is set with width="2.30" height="2.10" length="4.75" baleHeight="2.5"
    It can only hold square bale 220 at 1x3x2 stack, or square bale 240 at 1x1x2 (placed in sideway)
    It looks very ridiculous with such an open space wagen holding only 2 bale 240
    The space should be quite enough to fit square bale in 4 rows. So it will be either 8 bales in 2 stacks or 12 in 3 stacks
    Or maybe just make the loading area a little bit wider to hold 2 bales sideway and fit 2 rows
2. The Krone Profi Liner is high enough to hold square bales in 3 stacks, but the loading area data is width="2.40" height="2.50" length="13.2"
    It is limited to hold only 2 stacks of square bale and no baleHeight to override it
3. The Kagroliner PWO 24 is long enough to hold 2 cotton squre bales, but the data width="2.42" height="2.20" length="9.75" baleHeight="2.8" is just only a tiny short for 2 x 4.88 length cotton bale
4. The FarmTech DPW 1800 is similar to PWO 24, and even more open space, but the data length is only "9.3", make no sense at all

In conclusion, I suggest changing those vehicle data to
```
	<vehicleConfiguration configFileName="data/vehicles/bremerMaschinenbau/transportwagen/transportwagen.xml">
		<loadingArea offset="0 0.515 -0.265" width="2.42" height="2.20" length="4.88" baleHeight="2.8"/>
		<options isBaleTrailer="false"/>
	</vehicleConfiguration>
	<vehicleConfiguration configFileName="data/vehicles/krone/profiLiner/profiLiner.xml">
		<loadingArea offset="0 1.185 -0.1" width="2.40" height="2.50" length="13.2" baleHeight="2.8"/>
		<options isCurtainTrailer="true" enableRearLoading="true" enableSideLoading="true"/>
	</vehicleConfiguration>
	<vehicleConfiguration configFileName="data/vehicles/farmtech/dpw1800/dpw1800.xml">
		<loadingArea offset="0 1.130 -0.82" width="2.42" height="2.20" length="9.76" baleHeight="2.8"/>
		<options isBaleTrailer="true"/>
	</vehicleConfiguration>
	<vehicleConfiguration configFileName="data/vehicles/kroeger/pwo24/pwo24.xml" selectedConfigs="1">
		<loadingArea offset="0 1.275 -0.20" width="2.42" height="2.20" length="9.76" baleHeight="2.8"/>
		<options isBaleTrailer="true"/>
	</vehicleConfiguration>
	<vehicleConfiguration configFileName="data/vehicles/kroeger/pwo24/pwo24.xml" selectedConfigs="2">
		<loadingArea offset="0 1.275 -0.20" width="2.42" height="2.20" length="9.76" baleHeight="2.8"/>
		<options isBaleTrailer="true" noLoadingIfFolded="true"/>
	</vehicleConfiguration>
```

So the Bremer wagen can hold square bales x12 instead of x6, especially 240 square bales increased from 2 to 12 now, and can hold x1 cotton square bale
The Krone ProfiLiner can hold square bales x30 instead of x20
The FarmTech DPW 1800 can hold square bales 240 x24 instead of x21 (sideway loaded), and can hold x2 square cotton bales instead of x1
The Kroeger PWO 24 can hold x2 square cotton bales instead of x1

**Comment by loki79uk** [comment]
Thanks, I'll try them out, but I can't optimise settings only for bales, I also have to also test with other pallet types to make sure that:
- there are no collisions with any parts of the trailer during loading
- heavy pallets such as oil or metals do not cause the centre of gravity to be too high (trailers then tip on corners)
- animated doors do not hit any loaded items (such as on the KRONE curtain trailer)
- pallets are not outside the footprint of the trailer, especially when the straps pass through the objects

Of course you can put your suggested settings directly into your own mod settings file and then it will work like that for you (I guess you tried this?).  Everyone is free to configure any vehicle however they choose, and the local mod settings has the highest priority.

**Comment by harokyang** [comment]
I got your point
What is the default euro pallet sizeX and sizeZ? I can't find the data in xml
Seems set a width of 2.5 of loading area will just able to hold 2 pallets side by side in their short edge and increase the capacity of open flat trailer a lot

**Comment by loki79uk** [comment]
I don't think they can go bigger than they are already, but the whole point of doing the mod this way is that you can change it yourself to be however you like.

As it is currently, all loading areas are as close to the edge of the actual loading platforms as I could get them.  I don't consider the steel frame as part of the loading area, and usually the frame is raised slightly compared to the actual base, so pallets will not align perfectly:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/e03ab8b5-1d33-474b-bc6f-ed10c4a539d6)
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/dfb0c3fe-456d-423c-b69f-1672f5321d0e)
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/76516343/db212347-24ca-41b3-afad-4ee8846d4b79)

**Comment by loki79uk** [comment]
> I got your point What is the default euro pallet sizeX and sizeZ? I can't find the data in xml Seems set a width of 2.5 of loading area will just able to hold 2 pallets side by side in their short edge and increase the capacity of open flat trailer a lot
Default sizes are defined here:
https://github.com/loki79uk/FS22_UniversalAutoload/blob/6ae613a24a920ab9eade685f6f114eaf538218bc/UniversalAutoloadInstaller.lua#L79-L85
and extra custom sizes are here:
https://github.com/loki79uk/FS22_UniversalAutoload/blob/main/config/ContainerTypes.xml

**Comment by loki79uk** [comment]
Closing as unplanned.  It is too late in the day to change base game vehicle configurations.  Also, all configurations are designed with some realism in mind.  If you want to stack the maximum of one item, it is always possible to adjust your own custom settings.
