### ISSUE TITLE
Add dry boards (Holmakra map)

### ISSUE THREAD

**Issue by Kahhb** [loki79uk/FS22_UniversalAutoload#234]
Hi,

I can't autoload properly this boards to Krone trailer.

Tyvm
![Screenshot_2024-06-19-08-34-15-219_com android chrome](https://github.com/loki79uk/FS22_UniversalAutoload/assets/173236870/68a047e8-444a-4d1f-a1d8-aa915dd5c320)

**Comment by loki79uk** [comment]
Are you using the mod hub add-on? https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/blob/main/supportedMods.md  It says that Holmåkra 22 is supported, but I can't check until I'm home later this evening.

**Comment by Kahhb** [comment]
Installed and running!, Solved! Tyvm!

**Comment by Kahhb** [comment]
I have noticed that Dry boards 1 cant stack 4 times. They stack at 3.
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/173236870/719feb48-d455-4b9e-abb5-d5c1b4b5d005)

Dry board 2 stack only 2 times:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/173236870/2449433c-b8c5-4a61-86fc-d977ebf56bf3)

And Dry boards 3 stack 2 times:
![image](https://github.com/loki79uk/FS22_UniversalAutoload/assets/173236870/95084225-0861-4dd4-8590-3b5fb23aa54b)

I think they stack 1 more time.

Can you solve it?

Tyvm for your work and time!

**Comment by loki79uk** [comment]
Try on a different trailer, it looks like they should fit, but could be too close to the top of the curtain trailer roof.  Press ctrl-shift-F12 to see the exact sizes.

**Comment by Kahhb** [comment]
I will try to change the height, tyvm!

**Comment by loki79uk** [comment]
> I will try to change the height, tyvm!

Did you make any progress with this?

**Comment by loki79uk** [comment]
Closing this as complete, since the original problem is fixed, and the other one is just a matter of configuration.

**Comment by ddewar** [comment]
Hi jumping in on this way late, because life's been too busy. The issue with this pallet not stacking correctly is the pallet itself is misconfigured in the mod. I ended up correcting them locally to play this map with a friend. Hope that clears up any confusion.

**Comment by loki79uk** [comment]
> Hi jumping in on this way late, because life's been too busy. The issue with this pallet not stacking correctly is the pallet itself is misconfigured in the mod. I ended up correcting them locally to play this map with a friend. Hope that clears up any confusion.

That makes sense, do they have the origin in a weird place?

**Comment by ddewar** [comment]
> > Hi jumping in on this way late, because life's been too busy. The issue with this pallet not stacking correctly is the pallet itself is misconfigured in the mod. I ended up correcting them locally to play this map with a friend. Hope that clears up any confusion.
> 
> That makes sense, do they have the origin in a weird place?

Been awhile, but I believe it was off centered? It was pretty obvious once I looked at it in debug.

**Comment by Kahhb** [comment]
Hello! I tried to change txt file but nothing changed.

Tyvm for your help!

**Comment by loki79uk** [comment]
> Hello! I tried to change txt file but nothing changed.
> 
> Tyvm for your help!

It seems like it is an issue with those pallets.  I do have a plan for UAL v2 to actually measure the sizes and then this kind of thing should never happen.
