### ISSUE TITLE
[Bug?] Can not unload manually loaded pallets without disableManualLoading

### ISSUE THREAD

**Issue by ak131554** [loki79uk/FS22_UniversalAutoload#237]
Release 1.5.2.1

If I manually load Pallets to a Trailer with disabled Side loading and Rear loading (e.g. Salek ANS-1900) and disabled manualLoadingOnly than I can't unload them using Shift+I.. But, if I set disableManualLoading to true, I can unload them fine.

This seems to be a bug for me, because I don't understand why it should be impossible to use Unload also in this case with disableManualLoading false when it works with true.

**Comment by loki79uk** [comment]
I guess this is a result of adding a lot of different options that were not originally planned for.  "disableManualLoading" was a special mode requested by someone who wanted to load things without any autoload, but still have the ability to unload.

I agree that we should be able to unload any items that are loaded by hand, so I will look into adding this.  I think it used to work like this, but I must have broken it at some point when adding all the different modes..

_NOTE: It is also confusing even to me that I used "manual loading" to mean autoload lite (i.e. the autoload grabs pallets from the forklift and stacks them automatically) which is different to standard autoload, but we also need a term for actual manual loading with no autoload at all.. :S  Again, this is a consequence of making things up as I go along!!_
