### ISSUE TITLE
Missing Straw Harvest Pack DLC compatibility

### ISSUE THREAD

**Issue by xxx514** [loki79uk/FS22_UniversalAutoload#239]
Hello,

Any idea what should i write and where to allow pellet pallets and other ones from this DLC to be compatible with Your mod? Currently when standing near pellet pallet with base game flatbed or one from mods I cannot autoload them using key combination of your mod.

Thanks for spared time.

**Comment by loki79uk** [comment]
Have you got the latest version from here?  It should be working for straw harvest since this commit: https://github.com/loki79uk/FS22_UniversalAutoload/commit/d593fbf79d2d1eb2260f372f7669afc616e65589

I need to update ModHub, but currently away on holiday.

**Comment by xxx514** [comment]
Okay, my fault, i really apologise - i should check versions more carefully. Im still at 1.5.1. Thanks a lot for pointing it out. Happy holidays ;)
