### ISSUE TITLE
Autoload ProBox Bulk Seed pallets?

### ISSUE THREAD

**Issue by LiTaoRan8710** [loki79uk/FS22_UniversalAutoload#240]
has anyone came across a auto load trailer that can pick up ProBox Bulk Seed Container？

**Comment by loki79uk** [comment]
Hi, you can load them if you add the following to the appropriate sections in your settings file:
C:\Users\Loki\Documents\My Games\FarmingSimulator2022\modSettings\UniversalAutoload.xml
```xml
    <containerConfiguration name="FS22_SeedProBox:ProBox" containerType="EURO_PALLET" sizeX="1.20" sizeY="1.66" sizeZ="1.47"/>
```
```xml
    <objectType name="FS22_SeedProBox:proBox"/>	
```
![image](https://github.com/user-attachments/assets/bcda90b3-d09a-4e49-a776-510674ca3873)

**Comment by LiTaoRan8710** [comment]
thank you so much
