### ISSUE TITLE
Mixer Wagon

### ISSUE THREAD

**Issue by EH-31** [loki79uk/FS22_UniversalAutoload#241]
Hey, love your mod, saved me so much time and many nerves and works like a charm. I also like the addition of the autoload for mixer wagons and straw blowers. I get the logic that bales stop loading the mixer wagon once a component has reached 100% in the fill meter. Is there a way to work around that? I'd like to feed my cattle with hay only and don't just want to drop the bales in the barn.

**Comment by loki79uk** [comment]
Hi - I'm glad that you like the new feature, but yes that is a use case that I didn't think about! (doh!)

I can think of a few options:
- add a new toggleable option (but that would need another keybinding)
- add a special loading key combination that overrides the limit (could even use the bale collection mode keys `CTRL-SHIFT-R` ?)
- after stopping the first time we could start loading again to exceed the target (a bit awkward as one bale is already in there)
- if a single filltype is selected in the loading filter, then it would not limit the amounts (maybe conflicts with people who want to select certain types from an area of mixed bales, but still plan to make TMR)

Let me know if you have any preference amongst those, and I'll see what else I can come up with too.

**Comment by loki79uk** [comment]
> The update to add the mixer wagons has basically broken them. If you try to tip a bale or roll into the wagon it looks like it runs into this 100% limit and stops loading. First bale is automatically 100% at any level == unable to make any TMR with bales or rolls.

How are you adding them?  With a forklift?  I can either load with UAL or manually place them using super strength, and it mixes to the correct ratio and then stops:
![image](https://github.com/user-attachments/assets/4041d4b8-9f56-444d-b412-2fbc174e58c5)

**Comment by RTHauke** [comment]
I am trying to add them with a forklift and it doesn't work.  Well it does like 4 or 5 liters each time try.  Using UAL, it just puts the roll in the mixer wagon and it sits there.
![20241019224656_1](https://github.com/user-attachments/assets/eca39a0c-1986-4f5d-b527-a0ca14901ed6)
![20241019224823_1](https://github.com/user-attachments/assets/01a00343-fc80-4c9b-b0c1-aa1d66466c0b)

**Comment by loki79uk** [comment]
> I am trying to add them with a forklift and it doesn't work. Well it does like 4 or 5 liters each time try. Using UAL, it just puts the roll in the mixer wagon and it sits there.

I see the issue now - it should work for you if you add another filltype (silage or straw), BUT I will make a fix for it and update here later today.

**Comment by loki79uk** [comment]
@RTHauke - this one should work now:
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/1.6.0.1

@EH-31 - This doesn't resolve your issue though, so I will still add some method to override the limit for a single filltype.

**Comment by RTHauke** [comment]
Wow, I was not expecting that fast of a response!  1.6.0.1 fixed not being able to tip a roll in.  Now there are a couple other things going on:

- It starts adding from the roll to the mixer without tipping.  As soon as the roll is within the typical tipping range it starts adding from it.
- You can't stop adding from a roll, even if you back away from the mixer a few meters (well outside the tip range) it's still keeps adding to the mixer until the roll is completely added.  This happens with both the first and second ingredient.  It won't stop adding once it starts.
- Trying to top off the mixer from a straw roll stops at about 17%, it then goes back to that behavior of only adding a few liters at a time.  This is weird considering the behavior above.

FYI, I add roughly 500l of mineral feed before adding the straw.   If that matters.

**Comment by loki79uk** [comment]
>     * It starts adding from the roll to the mixer without tipping.  As soon as the roll is within the typical tipping range it starts adding from it.
I think I can prevent any limiting when the forkift is being used, that might solve all the issues.

>     * You can't stop adding from a roll, even if you back away from the mixer a few meters (well outside the tip range) it's still keeps adding to the mixer until the roll is completely added.  This happens with both the first and second ingredient.  It won't stop adding once it starts.
This is a problem with loading too, I need to identify when the bale has moved out of the trigger, but the game turns collisions off once the bale is "captured" by the mixer wagon, so the normal method of detecting collisions doesn't work.  I think the solution above will fix this for the fork lift though.

>     * Trying to top off the mixer from a straw roll stops at about 17%, it then goes back to that behavior of only adding a few liters at a time, even though the mixer is not full. This is weird considering the behavior above.
This is intended.  The idea is not to add any more straw than would prevent making an ideal mixture.  If we go above 17% then the straw component will be out of the idea range (red) after adding the other TMR ingredients.

> FYI, I add roughly 500l of mineral feed from a bucket scoop before adding the straw. If that matters.

Mineral feed should be ignored, but I'll check that too.

**Comment by loki79uk** [comment]
Okay, I think this has fixed the forklift/wheel loader issue, but I will look at preventing mixing when a bale moves out of range.
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/1.6.0.2

**Comment by RTHauke** [comment]
1.6.0.2 seems to have fixed all the issues I was seeing.  Even the issue with the bale continuing to tip when out of range.

**Comment by loki79uk** [comment]
> 1.6.0.2 seems to have fixed all the issues I was seeing.  Even the issue with the bale continuing to tip when out of range.

Awesome! Thank you for testing.

The out of range issue is still possible, but not when mounted on the forklift.  Please let me know if you find any other issues!

**Comment by loki79uk** [comment]
@EH-31 Do you think that the current state is good enough for your issue?  You can put a few hay bales in and constantly unload, but it wont go above about 50%

**Comment by EH-31** [comment]
@loki79uk hey! appreciate your fast answer and the work you have put in, truly amazing! I haven't checked GitHub for some time so only seeing it now. Yeah that's definitely good enough, thank you for your commitment and quickly fixing issues!

**Comment by loki79uk** [comment]
> @loki79uk hey! appreciate your fast answer and the work you have put in, truly amazing! I haven't checked GitHub for some time so only seeing it now. Yeah that's definitely good enough, thank you for your commitment and quickly fixing issues!

Glad that you agree.  I'm pretty happy with this as a compromise between getting perfect ratios and making it more usable with only single fill types.  It also lets you use e.g. more hay and less silage to still get a valid TMR mix.

I'll close this one now, but please report any other issues, even if they are just minor!
