### ISSUE TITLE
Game Freeze/Stuck at the first use of Autoload

### ISSUE THREAD

**Issue by Tharnadar** [loki79uk/FS22_UniversalAutoload#26]
I would like to help as much as I can to identify the issue and resolve it, please give me any instruction on how to recover any logs you can help.

When I load a game and the first thing I do is to jump on a machine with a trailer (even if I attach it in a later time) and I press "R" to load the trailer, the game stucks, I cannot rotate the camera anymore, I can enter the menu but if I quit the menu the game is even more stucked than before and I just have to kill the game client.

![image](https://user-images.githubusercontent.com/942104/156601805-4ea71ae7-5ab0-437a-8131-e1d2d27088a4.png) You can notice the RPM is missing and the F1 menu is totally wrong, I cannot move the tractor, rotate the camera, switch tractor, or enter again in the menu.

**Comment by Tharnadar** [comment]
Actually after I created the issue, I updated the mod to the version 11 and now it works properly as before. Much appreciated keep working.

**Comment by loki79uk** [comment]
That is good news!  I thought the R-key was a giveaway of an old version.  One of the reasons I changed to shift-R is to avoid conflicts with the base game key for pretty much everything! lol
