### ISSUE TITLE
Is there any way to allow Wool Pallets to stack 2 high?

### ISSUE THREAD

**Issue by tango99** [loki79uk/FS22_UniversalAutoload#27]
Is there any way to allow the wool pallets to stack on top of each other when being autoloaded?

**Comment by loki79uk** [comment]
There needs to be enough height in the trailer, so for two wool pallets the trailer height needs to be 2.4m or greater.   I'm fine tuning the areas/heights for all of the default trailers this evening, so I'll try to make two wool pallets fit on as many as I can.

**Comment by tango99** [comment]
I thought it may be to do with this, but the wool pallets has a height of 1.2, and the profiliner trailer has a height of 2.5, so shouldn't two wool pallets be able to fit in there already?

**Comment by loki79uk** [comment]
Ahh, in that case it is probably that the 1.2 is not tall enough for the real dimension of the pallet, so there will always be a collision when trying to stack.  Try increasing that until it loads.  I'll try tomorrow as well.

**Comment by loki79uk** [comment]
1.25 works okay.  I'll add that to the next release.
![image](https://user-images.githubusercontent.com/76516343/156883254-94678b39-04d4-471b-a207-622481a8ccdd.png)

**Comment by loki79uk** [comment]
Should be fixed now in: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-012
