### ISSUE TITLE
Loading bales that are on bale trailer

### ISSUE THREAD

**Issue by NOLA-CML** [loki79uk/FS22_UniversalAutoload#28]
![20220305001800_1](https://user-images.githubusercontent.com/10129300/156871184-b3d38a9a-1c95-410b-b0c2-f95fb788416a.jpg)

Not really a bug, but when loading bales that are on a bale trailer, the autoload trailer gets attached to the bales.

**Comment by loki79uk** [comment]
So is that after you try to load them, but they stay in the autostacker?

**Comment by NOLA-CML** [comment]
So, we were racing towards the last name, when I tried to load it, I attached to the trailer instead. Where he went I went. Then when he unloaded the picture happened. 

I think a warning would suffice in modhub. Don't try to autoload bale's that are on the bake trailer.
