### ISSUE TITLE
Cant get version 22 to work with multiplayer

### ISSUE THREAD

**Issue by MrTiepie** [loki79uk/FS22_UniversalAutoload#33]
Hi!

Somehow loading (at least with the ProfiLiner because that's all that we tested) won't work with the latest version.
When initially approaching or sitting in a vehicle the prompt of L-Shift - R will show. When pressed we see: Stop loading als keypress. But nothing happens. And when keypressing L-Shift-R again to stop loading, the prompt does not even show anymore.

We haven't tried any other trailers though.

We even tried getting it working by removing the zip from the mod folder on our dedi server and private mod folders restarting the server and running it again but to no avail.

Any idea what might be causing this?

**Comment by loki79uk** [comment]
I'll try to reproduce this later this evening.  Does it work again if you revert to 020?  (I think 021 and 022 are pretty similar)

**Comment by MrTiepie** [comment]
Will give that a try later on and get back to you about that. Thanks!

**Comment by MrTiepie** [comment]
Version 020 seems to work fine. Here I can unload and load just fine. Straps work. Haven't tested the sleep thing but that was fixed in an earlier version so that should be fine I guess.

**Comment by loki79uk** [comment]
I made a stupid mistake updating some of the functions but not the MP events.  New version incoming!

**Comment by loki79uk** [comment]
Hopefully all fixed again:  https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.0.0-beta-update-023

**Comment by MrTiepie** [comment]
Will check it out!

**Comment by MrTiepie** [comment]
Seems to work. If there are any issues I will let you know. Thank you!
