### ISSUE TITLE
Custom bales not loading since v1.0.0.0-beta-update-018

### ISSUE THREAD

**Issue by FanFSEver** [loki79uk/FS22_UniversalAutoload#36]
Firstly thank you for this Autoload mod. I have always wished for a versatile type that can load different types of products and sizes. I appreciate the thoughts, planning and coding that have gone into creating the latest version.

I prefer to use the Hesston bales. Pre v1.0.0.0-beta-update-018 I was able to add the lines for the Hesston bales from the Hesston 4900 baler (from Eire Agri) to the container.xml file and the Autoload worked seamlessly. BTW, much easier to add it to the mod and mod trailers. Since this version the Autoload does not recognise the bales anymore.

I have added the following three lines below the lines for the ingame square bales: 

```
<objectType name="squarebaleHesston180" sizeX="1.210" sizeY="1.310" sizeZ="1.80"/>
<objectType name="squarebaleHesston220" sizeX="1.210" sizeY="1.310" sizeZ="2.20"/>
<objectType name="squarebaleHesston240" sizeX="1.210" sizeY="1.310" sizeZ="2.40"/>
```

The xml file for the Hesston bales contains the size line as follow:
`<size isRoundbale="false" width="1.2" height="1.3" length="2.4"/>`

The bales' file names are:
squarebaleHesston240.i3d
squarebaleHesston240.xml

When you drive next to the bales it just does not recognise them. Used a number of standard ingame trailers.

As a test I also placed an ingame bale next to the Hesston bale. The Autoload function recognise the ingame bale and load it but does not recognise the Hesston bale.

I do not have any errors in the log file.
I have also placed only two mods in the mods directory, namely the Hesston_4900 and UniversalAutoload mods.
Also tried to change the Loading filter type.
Tested up to v1.0.0.0-beta-update-023. Only realised the problem when I tried to load bales with the latest version.

**Comment by loki79uk** [comment]
I'm at work so can't look until later, but sounds plausible because my commit comment from v018 was:
_"Should now properly load pallets and bigbags from mods.  Will not load bales as these have a different xml structure."_

I think this is a case of 'fix one problem but create another', and then I never got around to looking at the second issue.  I'll update here when I figure it out.

**Comment by FanFSEver** [comment]
Thank you for the prompt reply. Misunderstood the sentence, my apologies.

Just want to thank you again for the elegant product you have created. Looking forward patiently to a solution from you since you always seems to find a solution.

**Comment by loki79uk** [comment]
No need to apologise at all - thanks for reminding me!

For now I think it should work for you if you use the following lines:
```	
<objectType name="FS22_Hesston4900:squarebaleHesston180" sizeX="1.210" sizeY="1.310" sizeZ="1.80"/>
<objectType name="FS22_Hesston4900:squarebaleHesston220" sizeX="1.210" sizeY="1.310" sizeZ="2.20"/>
<objectType name="FS22_Hesston4900:squarebaleHesston240" sizeX="1.210" sizeY="1.310" sizeZ="2.40"/>
```
Note the new format `name="<ModName>:<i3dName>"`
Sorry I should have documented that!

I also tried to import via the bale xml schema and I think it should be working now but I need to test before I can release it.  Which version are you using?  I tried with FS22_Hesston4900.zip v1.0.0.0 and the baler was not loading in the shop (`Warning: Could not add pack item. Pack does not exist.`), and I could not spawn those bales with PowerTools either.

**Comment by FanFSEver** [comment]
Adding the ModName fixed the problem. Working like a charm at the moment. Hesston bales load as it did previously.

I have downloaded the latest version of the baler, 2022-03-12, recently but did not notice the baler is not available. Haven't used the baler for a while but did have the bales. I still had a previous version of the mod which I will be using until Eire Agri fix the problem. The bales are still available but not the baler with the latest version. PowerTools has never been able to spawn the bales.

Thank you again very much for this mod. I am really enjoying it, esp since I play FS22 more as a management style simulator than an actual vehicle simulator. Not good at all with loading bales and pallets manually.

Universal Autoload is now my most favourite and must have mod together with Courseplay and Autodrive.

**Comment by FanFSEver** [comment]
Just a final update with regards to the Hesston 4900 mod. It seems that with the latest upgrade the Twine Addon mod is now a requirement. When I added the Twine Addon mod everything worked fine. Did a test run with all three lengths, straw only, and it worked fine. Unfortunately not time to do all the types.

Thanks again.

**Comment by loki79uk** [comment]
I found out about the Twine Addon requirement after I posted.  I should be able to test now, thanks for the update though.

I'm glad you got it working with the ModName.  I had to add that because there are some mods that use the same name as base game i3d files, but with different dimensions, so I think it is better to have a unique name for each mod.

**Comment by FanFSEver** [comment]
I think the unique name for each mod will work better, esp since there will be a lot new mods with unique objects coming in the future.

Re the Hesston mod - I noticed that the biggest bale's i3d is different than the sizes in the xml file. After I changed the i3d model it loaded and stacked perfectly everytime with the 023 version.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by loki79uk** [comment]
Yeah, it is pretty common for the sizes to either be miles out, or just not quite right for stacking.  It is especially a problem with most of the standard base game pallets.  I think GIANTS must use it as a "comfortable volume for spawning without any collisions", certainly way bigger than the actual pallets.

**Comment by FanFSEver** [comment]
I agree with your assesment regarding the reasoning for the smaller size of Giants i3d models. And it does make sense. However the problem with the Hesston 2.4 bale is that two of the xml sizes are smaller than the i3d. Realised that when it autoloaded with gaps. I reduced the i3d size and then it stacked perfectly. Wish maybe that Giants could give out standardised size guidelines for pallets and bales right at the start of launching a new FS version.

Huge respect for your ability to create an autoloader that figure out all the different aspects and still is able to do what it can do so effectively.

Can't thank you enough. Really made the game so much more enjoyable for challenged loaders like myself.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by loki79uk** [comment]
Is this still working with the latest release?  I've done a few changes to loading that should not have affected anything, but just wanted to check.  Please let me know, or just close the issue so I will know. :)

**Comment by FanFSEver** [comment]
Congrats on finally being approved for Modhub. I noticed a new version on Github. Will download and test over the weekend. Will report back as soon as I had time.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by FanFSEver** [comment]
Did a test with the the Hesston mod released on 2022-03-12. Bales load. However, I had to reduce the size of the i3d of the 2.4m bales to get the most effective loading. The problem seems that the i3d model is bigger than the specified size in the xml file.

I will be closing this issue as solved. Rated the mod on Modhub with a 5-star. Only mod I have rated so far. Thank very much again.
