### ISSUE TITLE
Query on adding support to new mod

### ISSUE THREAD

**Issue by judg393** [loki79uk/FS22_UniversalAutoload#38]
Hi 

I'm sure this is just me not adding something correctly I've tried to add UAL to a copy of the TLX Phoenix flat bed by following the instructions and it now picks up the UAL instructions in the help menu but tells me it's full when I try and load. 

I'm presuming ive not set the offset but correctly because I didn't really understand where they came from i tried using the translate co ordinates in there and tried with the default offset information in the instructions it still says it's full. 

What've I done wrong?

**Comment by loki79uk** [comment]
There are no default offsets, those are just examples.  You will always need to enter the correct dimensions and offsets for the trailer, and the easiest way to get them is by measurement in the GIANTS Editor.  You could also do it by a 'trial and improvement' type of guessing the values, but it will take quite a few iterations to get right.

Press Shift-F12 when in the vehicle controlling the trailer in game and you should see the load area outlined on the trailer bed like this:

![fsScreen_2022_03_21_22_01_52](https://user-images.githubusercontent.com/76516343/161037324-6ac9658c-ba41-4c60-8a5c-1d92fa48c765.png)

I guess that your offset is too low, so the script is detecting that the trailer bed is obstructing the loading area.

**Comment by judg393** [comment]
I did the measurements as suggested in instructions(by the way very good indeed thank you) made a cube and left clicked on bed which I presume was the area you want to load up (ie have pallets appear). 

I put scale figures as per the below  in but I couldn't find  a figure called Offset in GE? 

I'm very new to GE so where do I get the offset figures from? 

<loadingArea offset="offsetX offsetY offsetZ" width="scaleX" height="scaleY" length="scaleZ"/>

**Comment by judg393** [comment]
Ah ok I'll try the translate. It is likely my modding skills not your incredible mod. :) I expect I'll just need to fiddle to get it working 

Cheers for being  so responsive :)

**Comment by judg393** [comment]
Thank you for the tip I have got it working on certain Configurations only (should work on more but thats down to me again i'm sure) 

can't figure out the different cobfigures on the phoenix so i'll make do with what i have

**Comment by loki79uk** [comment]
You can close it, or I can too, but better if you do it.  The configurations should be in the same order as they appear in the xml I think - not always the same as the order they cycle through in the shop, since it doesn't have to start with config 1.  You can try adding them individually and see what the console/log file message says when loading each config in the shop.

**Comment by judg393** [comment]
I'll close now  sorry I missed your reply
