### ISSUE TITLE
Config set up for new Maitre Pack done, next steps are ?

### ISSUE THREAD

**Issue by Kyuui013** [loki79uk/FS22_UniversalAutoload#39]
Hello!
So using your excellent guide I was able to make a useable set of measurements for the 3 trailers in the pack. I'm new to the whole mod scene in FS so not sure what I should do from here. Give you the code, send the code to the mod maker, take a long walk in the desert?  

Any advice is great, thanks and thanks for the mod and guide, Both are outstanding,

**Comment by loki79uk** [comment]
Hi - glad to hear that you got it working!

I'm still thinking about the best route forward, but most likely I will add full support for ddwears addon mod, then hopefully we can work together as a community with pull requests to keep that updated with settings for all the modhub vehicles:
https://github.com/loki79uk/FS22_UniversalAutoload/pull/24
https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon

I've been a bit busy with work and IRL stuff for a few weeks, and also waiting to see what happens with the submission of Autoload to ModHub, but it is still pretty high up on my do do list!

**Comment by judg393** [comment]
Hey congrats on the ModHub release buddy it's lovely to have this feature in MH! 

Quick question did you ever think about see if AUtodrive devs would be interested in adding compatibility. I have no idea how simple (or not as I suspect) that is!

**Comment by loki79uk** [comment]
Thanks, I only just saw it was approved, lol.  As much as I love AD, I think my autoload is a bit too user focused to be a simple load/unload that would work with automation.  It was mostly designed to bridge the gap between manual loading/unloading when you want to, and then autoload when you can't be bothered.

**Comment by judg393** [comment]
Fair enough I can live with that!
