### ISSUE TITLE
Issue with new FS 22 Update

### ISSUE THREAD

**Issue by Jackknife90** [loki79uk/FS22_UniversalAutoload#41]
it was working perfectly fine yesterday, today i dont get the ingame "command list" to autoload, the key binds options are availible to change in the options.

just wondering if ive done something or FS has broke something

**Comment by loki79uk** [comment]
It is an issue with the 1.4 update today affecting quite a few specialisation script mods.  GIANTS have said they are aware of the issue and will push out a hotfix as soon as possible.

![image](https://user-images.githubusercontent.com/76516343/164008899-f3aae79d-219f-418d-8166-f4d5ca9d503f.png)
https://discord.com/channels/299449702599098368/416574224912613379/965937574298419201

**Comment by GtX-Andy** [comment]
Hey, 

Not sure what Giants will be fixing as I have not personally experienced any issues with my global specs.

There is an easy fix to resolve your issue by making some localisation changes to your installer lua.
I could do a branch pull if you prefer but here is the code.

```lua
g_specializationManager:addSpecialization('universalAutoload', 'UniversalAutoload', Utils.getFilename('UniversalAutoload.lua', g_currentModDirectory), nil)

for vehicleName, vehicleType in pairs(g_vehicleTypeManager.types) do
    -- Anything with tension belts could potentially require autoload
    if SpecializationUtil.hasSpecialization(TensionBelts, vehicleType.specializations) then
        g_vehicleTypeManager:addSpecialization(vehicleName, modName .. '.universalAutoload')
    end
end
```

This should solve the problem for you. ;-)

Hope that helps, 
GtX

**Comment by Jackknife90** [comment]
i saw Lokis advice earlier and just rolled back the FS update in steam until they hot fix it. thanks though

**Comment by GtX-Andy** [comment]
No issue was a message for loki mainly to solve the issue as there is no reason to be on an old game version for one or two scripts, but players choice :-)

**Comment by loki79uk** [comment]
> This should solve the problem for you. ;-)
> 
> Hope that helps, GtX

Amazing - can't thank you enough! :D

I spotted the `nil` in some other mods, but alone that made no difference.  The prefix makes sense, but I wish GIANTS would document this stuff somewhere..  Or maybe they did and I just don't know where to look?

I've pushed a new version that loads now, but I will not have any time to test it properly until this evening.
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.1.0-beta

**Comment by BontoTroll** [comment]
hi loki! thank you for your work, its very useful, i love it, but unfortunately it doesn't work for me with 1.4, same as with 1.0.0

**Comment by loki79uk** [comment]
> hi loki! thank you for your work, its very useful, i love it, but unfortunately it doesn't work for me with 1.4, same as with 1.0.0

That is weird, it is working for me.  Are you sure you deleted the old one and downloaded the release zip, not the git repo zip?

**Comment by GtX-Andy** [comment]
> Amazing - can't thank you enough! :D

You are more then welcome, you are doing great work here so happy to help.
Yes the documentation has decreased rapidly over the last few years with each release to almost nothing sadly.

Giants clearly made a change for `PF` as it is an internal mod and on console.

The 4th parameter is actually 'customEnvironment' for the `addSpecialization` and `addType` functions. This was added in 19 I think but I have just continued to use the old method.

I believe adding the `customEnvironment / modName` in the 4th parameters would actually also sort the localisation but I have not tested it.

I just manually make the change out of habit as all Classes and Specs as you are aware run in their own environment.

```lua
local specName = modName .. ".mySpec"
local  className = modName .. ".MyClass"
```
Well again glad it worked and lets hope the 'Hot Fix' does not cause more issues 🤣

**Comment by BontoTroll** [comment]
> > hi loki! thank you for your work, its very useful, i love it, but unfortunately it doesn't work for me with 1.4, same as with 1.0.0
> 
> That is weird, it is working for me. Are you sure you deleted the old one and downloaded the release zip, not the git repo zip?

Yes, i am sure, in the game i see the correct version number (1.0.0.1), the last version worked fine. What can i do?

**Comment by loki79uk** [comment]
> Yes, i am sure, in the game i see the correct version number (1.0.0.1), the last version worked fine. What can i do?

The version should be 1.0.1.0, but assuming that is a typo then I'm not sure what else to try?  Maybe see if anyone else has the same problem, and see what the patch brings today.  Are you using the Add-On mod, I have not tested that with 1.4 yet.

**Comment by BontoTroll** [comment]
> > Yes, i am sure, in the game i see the correct version number (1.0.0.1), the last version worked fine. What can i do?
> 
> The version should be 1.0.1.0, but assuming that is a typo then I'm not sure what else to try? Maybe see if anyone else has the same problem, and see what the patch brings today. Are you using the Add-On mod, I have not tested that with 1.4 yet.

yes, the correct is 1.0.1.0, sorry, i dont use Add-On mod, i try to place it again

**Comment by loki79uk** [comment]
I'm going to close this now because I think the original bug is resolved, but for @BontoTroll - if you are still having problems, please open a new issue or message me on Discord Loki_79#2864
