### ISSUE TITLE
unload load options not working in vehicle ? 

### ISSUE THREAD

**Issue by judg393** [loki79uk/FS22_UniversalAutoload#44]
hello me again! 

just wanted to flag that since update 1.4.0 and 1.4.1 using the latest version of UAL (1.0.1.2 i think  not great on version numbers buts it your latest release)  i no longer seem to be able to switch the material or containor type when trying to unload from vehicle (at least the options don't appear in the  help window so even if it is working i can't see whats selected  

it works fine from outside the vehicle. screenshots show my UAL phoenix (thanks again for makign the add to other mods so easy!) but ive tested with base game demco trailer too and can't change any option inside cab any more.   i've just thought is this intentional?

![20220422065140_1](https://user-images.githubusercontent.com/55981682/164886131-fccab749-6d59-4443-8ef3-8eae0e2e4116.jpg)
![20220422065125_1](https://user-images.githubusercontent.com/55981682/164886132-aa7ac47f-a4f6-4c49-9057-dad55c3e2a55.jpg)

**Comment by loki79uk** [comment]
There is some kind of keybinding bug with the new patch that seems to affect all mods, so could be that?  Try restting your key bindings from the menu.

I know it is not much help, but it is working for me:
![image](https://user-images.githubusercontent.com/76516343/164886364-e5e7ce18-8eb3-49a9-a966-e0c6f542c4d3.png)
![image](https://user-images.githubusercontent.com/76516343/164886378-8aca9042-5561-4f00-bb39-0856ffa54c6c.png)

**Comment by judg393** [comment]
OMD i was still typing to give you images :)
10/10 for support  

hmm i think it may also be a nmod conflict works fine with only ual selected I'll have to test

**Comment by loki79uk** [comment]
Let me know if you can find the problem/conflict - I'm out all day today with the kids, but will be back around this evening.

**Comment by judg393** [comment]
will do may take me a while lol

**Comment by judg393** [comment]
I think its Autodrive @loki79uk :( im using the 2.0.5 version of AD I'll see if i can get someone lse to test

**Comment by judg393** [comment]
Further testing leaves me wondering if with CP PF and AD I've just got a full help menu which is not something you can do anything about I don't believe

**Comment by loki79uk** [comment]
I'll investigate this as well.

**Comment by judg393** [comment]
I found a setting to turn off AD in the help menu and got material switch back so I'm fairly confident that this is the problem if there is anything you can do great but if not no sweat.
