### ISSUE TITLE
FS22_UniversalAutoload: Stopped working 

### ISSUE THREAD

**Issue by Ouedzets** [loki79uk/FS22_UniversalAutoload#46]
Hi There,
I'm a new user to FS22 and this is a great mod!
However after installing it and using it for a few rounds, it stoped working.
I speciffically istalled the recommended trailer Brantner DD 24073/2 XXL but to no avail. 
I also tried to uninstall it and to reinstall severall times from the modhub. 
Then I found your link on your site and tried this also.
With no success at this stage.
All the other mods installed so far work fine.
Thanks for your help!
BR

**Comment by loki79uk** [comment]
Have you tried resetting your key bindings?  This seems to be a common problem with any mods that have keybindings since v1.4.1.0

**Comment by Ouedzets** [comment]
Hi there! 
Well this fixed it! Thanks a lot! 
Much appreciated!
