### ISSUE TITLE
Call stack error on dedi server

### ISSUE THREAD

**Issue by jreedy76** [loki79uk/FS22_UniversalAutoload#47]
Error: Invalid customEnvironment given for SpecializationManager.addSpecialization. Should be a string or nil.
2022-04-25 05:52 LUA call stack:
  dataS/scripts/mods.lua (396) : printCallstack
  =C:/Users/jreed/Documents/My Games/FarmingSimulator2022/mods/FS22_UniversalAutoload/UniversalAutoloadInstaller.lua (10) : addSpecialization
  =[C] (4294967295)
  dataS/scripts/mods.lua (347) : source
  dataS/scripts/mods.lua (839) : source
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/mods.lua (836) : iterate
  dataS/scripts/gui/MPLoadingScreen.lua (754) : loadMod
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1152) : update

**Comment by loki79uk** [comment]
Is this happening with the latest version? https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.1.2-beta

I would expect that message with the current ModHub version of UAL (1.0.0.0) on dedi and in single player.  That is just the message that GIANTS added with the fix in v1.4.1.0.

**Comment by jreedy76** [comment]
the modhub version
