### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by judg393** [loki79uk/FS22_UniversalAutoload#48]
Hi buddy I'm sorry I seem to be posting a lot here 

I've had an issue with cp creating a lua error and failing the save process. The CP guys are saying the lua error originates with UAL 

"2022-04-26 07:34 Error: Running LUA method 'update'.
D:/FS22/Hobos/FS22_UniversalAutoload/UniversalAutoload.lua:1512: attempt to index global 'spec' (a nil value)" 

This is what they discovered in my log 

Thought you may want to know in case it is a issue needing looking at I am using latest UAL version I believe (1.04)  I can link log ect if you wish

**Comment by loki79uk** [comment]
Hi thanks for testing - work has been busy and trying to keep on top of everything here too!  I thought I had found all of those, will fix it now!

**Comment by loki79uk** [comment]
Should be fixed in this one:  https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.2.0

**Comment by judg393** [comment]
I'll test it out now :) cheers I'll reopen if i fnd anything wrong (not that i expect too!)

Don't burn out remember to enjoy IRL too especailly down time with the kids which i recall you saying you had!

**Comment by loki79uk** [comment]
It is all good thanks.  I was just in a rush this morning to get it all submitted to ModHub for testing before I started work.  I'm off camping at the weekend, with some canoeing down the river wye too!  Thanks again!
