### ISSUE TITLE
Trailers unstrapping other trailers tension belts

### ISSUE THREAD

**Issue by ddewar** [loki79uk/FS22_UniversalAutoload#5]
Not sure if this is a known issue, a bug, or a problem with how I implemented the autoload, but currently when I have 2 trailers with universal autoload, loading one will remove the tension belts on the other. If needed I can dig up a log or video showing the issue. I can do some more testing and see if it happens with all trailers when I get some time, and I will add more details to this issue.

**Comment by loki79uk** [comment]
If they are near each other and you load items onto a trailer from another one, then the straps should be left off on the one you unloaded from.  If they are apart and it is still happening, then it is a bug.

Some extra details, or steps to reproduce would be great if you have time.

**Comment by ddewar** [comment]
Attached is a short video showing what I encountered. Notice at the start the trailer in the back is strapped down. After I load the trailer in the foreground the other trailer unstraps.

https://user-images.githubusercontent.com/15822357/155276052-99bcd5b1-6d7c-4cb1-8137-91721b1ed85d.mp4

Some notes of things I've tried:
- Distance is not a factor, I tested at each end of the map.
- It is only trailers with this specialization, other strapped pallets do not unstrap.
- Unloading does not unstrap the other trailer. Only loading.
- All trailers with the specialization do unstrap. Any number or any type, not just the same trailer like in the video above.
- Different pallets does not change the result.

No errors are coming up in the log or console. Only mods for tests are this mod and powertools.

Please let me know if there's anything else I can test to help!

**Comment by loki79uk** [comment]
Thank you for all the details, that is really helpful!  I'm away until the weekend, but I'll look at it when I get back.  It is strange that I've not seen the same on my test saves though, as I certainly have multiple trailers with the straps done up.  Thanks again, I'll update this issue when I've solved it.

**Comment by ddewar** [comment]
Just for confirmation in a quick test, yes, it looks to be working as expected. Thanks!

**Comment by loki79uk** [comment]
Great - I'll close this for housekeeping, but please open again or create a new one if you have any more issues.  Obviously can't test anything with tension belts in MP games for now, but they should still be working as expected in SP.
