### ISSUE TITLE
1.2.0.1 F1 menu not showing options

### ISSUE THREAD

**Issue by Aphroo7** [loki79uk/FS22_UniversalAutoload#52]
Game version
![image](https://user-images.githubusercontent.com/94638361/167295257-2b24eef0-3585-4956-a3f6-3859d76be275.png)

Mod version tested from github and modhub.

![Screenshot_3](https://user-images.githubusercontent.com/94638361/167294876-ac5306c6-3bee-429f-a543-203483317b09.png)

![image](https://user-images.githubusercontent.com/94638361/167294977-76695126-9c5c-40ac-98bf-d5020d438024.png)

Any compatible trailer not showing load/unload options. No errors in log while working with trailer.

Error logs when save game.

![image](https://user-images.githubusercontent.com/94638361/167295194-9da0b9aa-6a51-4f07-b4e7-050cd4606391.png)

**Comment by Aphroo7** [comment]
![image](https://user-images.githubusercontent.com/94638361/167295409-ef13262b-48b8-4ee2-ab09-0b76acfd7d64.png)

Found closed issue, and keybind reset worked, works smooth but missing spanish translation.

Still giving error when save.

**Comment by loki79uk** [comment]
Please could you test if this fixes the log error when saving: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.2.2

**Comment by Aphroo7** [comment]
![image](https://user-images.githubusercontent.com/94638361/167296052-2dc25b28-033e-4e5f-ab32-282885534fe0.png)

Logs clear when save, perfect.

About missing translation, is there any way i can make my own or share it for future mod versions?

**Comment by loki79uk** [comment]
You could make a pull request with the languages added to the moddesc, or if it is easier for you then edit manually and attach the file here or send it to me on Discord Loki_79#2864.  I usually only do English, French and German text for most of my mods, but this one has been very popular and lots of people have helped me with the translations!  I should really spend some time on it and split the translations out into separate files as it is getting quite cumbersome now!

**Comment by Aphroo7** [comment]
Your job is incredible, you made an awsome job.

I'm already working on moddesc in spanish, let me add you on Discord.

**Comment by Aphroo7** [comment]
1.4.1.0 version require keybinding reset when F1 help menu can't show tooltips, this happends with other mods, not an issue from Universal Autoload.
