### ISSUE TITLE
Bale Types and Whereto Add?

### ISSUE THREAD

**Issue by Jayshua83** [loki79uk/FS22_UniversalAutoload#55]
Hello! 🙂

I am trying to figure out a couple of things in your Universal Autoload Mod. Was hoping to get some info?

I tried understanding your Readme/ModDesc about new Container/Bale Types but I am afraid I don't follow where to add them or when special cases apply.

My situation is that I am on a mod map Elk Mountain Wyoming, and he has added a few textures to the bales and has the i3ds for the bales all in the map folder. However the names for the bales and the i3ds and everything else hasn't changed, he only has them for the textures of Alfalfa. HOWEVER none of the bales work with UAL. 

How do I go about adding them to UAL when the bale i3ds are the same as base game but they are loaded at the map level to add additional filltypes/textures to the xmls?

Can I add them into the ContainerTypes.xml ? And if so what info would I need to reference them? Hope this all makes some sense! 😐

Thanks for any help/info you can impart!

**Comment by loki79uk** [comment]
Confirmed resolved via Discord.
