### ISSUE TITLE
Support for stock trailer Salek ANS-1900

### ISSUE THREAD

**Issue by ph-hoffmann** [loki79uk/FS22_UniversalAutoload#56]
Could you add support for this stock trailer? It seems to be missing somehow.

Thanks in advance.

**Comment by loki79uk** [comment]
I'm adding it now - Salek was added in 1.4 and with fixing all the bugs that patch caused I didn't notice that it had a bale trailer!

**Comment by ph-hoffmann** [comment]
Nice. And thank you for the incredible fast reply. Seems there are some more stock trailers (might be new too) missing.
- Böckmann KK 3018/27 H
- Krone Profiliner

**Comment by loki79uk** [comment]
No problem - I've got a day off work today.  The Krone should already work - that is the main one that I use, but you need to have the curtain open for autoloading to be enabled.  The Böckmann is on my list of stuff to do, but first I need to add a setting to only allow loading when the door is open (similar to the curtain one, but doors are handled differently).  It is on my todo list, but since it is such a small trailer other stuff has taken priority.

**Comment by loki79uk** [comment]
Actually, I'd forgotten that I've already done the "loading when door open" part since it is the same as a trailer being folded/unfolded.  So the only issue left is to decide how to avoid this internal vent that blocks pallets from stacking: 

![image](https://user-images.githubusercontent.com/76516343/170681859-ff25882e-95a1-4be2-9dfa-aa68e2fdf1fc.png)

**Comment by loki79uk** [comment]
I've also added option to open/close the door on foot, that was the other thing I needed to do:

![image](https://user-images.githubusercontent.com/76516343/170686239-56ac21a0-84ef-41f2-ac2c-40b99e512f4d.png)

**Comment by ph-hoffmann** [comment]
That is awesome. It bothers me quite a lot to get some vehicle connected all the time just to open / close the doors on a trailer.
As for the internal AC vent: Would it suffice to begin loading directly behind the door and make the loading area just big enough to get two or three pallets in while leaving room for the vent?

**Comment by ph-hoffmann** [comment]
One thought about that load while enclosed problem. Can you handle trailers etc. that open / close doors incrementally via the mouse controls with the code already in place or is that a different trigger?

**Comment by loki79uk** [comment]
I've set the height lower for now to get the maximum floor area, but I could try moving it forwards and going for max height as well.

The door thing is only an issue with enclosed trailers, but it is all triggered by animations, so I think I'd probably need to add a new method to handle mouse controlled animations.

**Comment by ph-hoffmann** [comment]
If you need a testcase for the mouse animation stuff, you can use [this mod](https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=226465&title=fs2022) I guess. Haven't found that many trailers that you can actually open sadly.

**Comment by loki79uk** [comment]
It seems better for most containers to bring the load forwards as then you can stack, but I'm sure there will be cases where uisng the lower load height is better: 
![image](https://user-images.githubusercontent.com/76516343/170698947-ef134ec6-356a-4ee0-a8c6-2eded8b9f697.png)

I have fixed the open/close door text as well.

**Comment by loki79uk** [comment]
Both of those are added to:  https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.4.0

I'll look at the mouse animation, but for now just don't use `noLoadingIfFolded`/`noLoadingIfUnfolded` and it will still load, just a bit unrealistic and you won't be able to see anything with the door closed!

**Comment by loki79uk** [comment]
I also just realised that you can still unload with the door open, so I'll fix that now.. :D

**Comment by ph-hoffmann** [comment]
Just tested it, all working nicely. I only found a small config error for the Böckmann (I guess?). Shouldn't the (only available) "Unloading side" be "rear"?

No rush though. It's a rather small thing. ;)

**Comment by ph-hoffmann** [comment]
Sorry to spam you, the support for the SALEK ANS-1900 seems to not work at all.

**Comment by loki79uk** [comment]
> Just tested it, all working nicely. I only found a small config error for the Böckmann (I guess?). Shouldn't the (only available) "Unloading side" be "rear"?

Adding a rear unloading zone is a bigger job that I need to do, but there are a few vehicles that need it, so I will get around to it eventually!

> And another small one. You can unload the Böckmann when it has it's doors closed (but not load).

Did you try 1.0.5.0?  I noticed that and released another version just now.

> And GIANT seems to have missed adding straps to that trailer ... -.-

Good point - I guess you just need to make sure you close the door! lol

**Comment by loki79uk** [comment]
> Sorry to spam you, the support for the SALEK ANS-1900 seems to not work at all.

Have you got it in the bale configuration?

![image](https://user-images.githubusercontent.com/76516343/170718586-da3cb4ea-9042-4b7a-a460-d3a389204408.png)

**Comment by ph-hoffmann** [comment]
Should have thought of that :D
Working in bale config.
