### ISSUE TITLE
Unable to unload

### ISSUE THREAD

**Issue by ph-hoffmann** [loki79uk/FS22_UniversalAutoload#57]
I just tested adding vehicle configurations myself (your guide was quite helpful). All working now. However, I find myself to be unable to unload the vehicle some times. Enabling debug visualization shows, that the mod seems to be unable to find a place to put the pallets.

![20220528234110_1](https://user-images.githubusercontent.com/57097265/170854646-e0b346c6-3a66-4dd8-b4a2-81793145f4b6.jpg)

Trying to unload inside the barn seems to work most of the time. Unloading with other vehicles works without problems.

The vehicle mod: https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=235660&title=fs2022
The config (awaiting merge): https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/commit/0b3194af34cd81ae42f22ab34af7363447efcc5e

**Comment by ph-hoffmann** [comment]
Same config, Unloading on the road works,

![20220529081927_1](https://user-images.githubusercontent.com/57097265/170855035-d9ad8117-f225-4d2d-a6b8-e4c8a7a9222b.jpg)

**Comment by ph-hoffmann** [comment]
There seems to be an incompatibility with this mod too as I am unable to change the unloading side via "U"

**Comment by ph-hoffmann** [comment]
Same with
https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=232583&title=fs2022
https://github.com/ph-hoffmann/FS22_UniversalAutoloadModhubAddon/tree/FS22_Lizard_Rumbler

**Comment by loki79uk** [comment]
The F100 has a load trigger that could potentially be causing the issue, although the collision flag settings look correct - could be 'Compound' tick box - I don't know what that does.
![image](https://user-images.githubusercontent.com/76516343/171025547-f0a49bf4-f416-4778-b329-ec3100fc13b6.png)

I don't have time to look into now, but the trigger for the fuel tank in the Rumbler van could also have incorrect collision flags set.  Try editing the mod to remove those triggers and see if that fixes it, then if that works, put them back in and try adjusting the collision settings.

The unloading collision mask for UAL is:
`local collisionMask = CollisionFlag.STATIC_WORLD + CollisionFlag.DYNAMIC_OBJECT + CollisionFlag.VEHICLE + CollisionFlag.PLAYER`

**Comment by loki79uk** [comment]
The Rumbler van is very likely to be because of this:

**Comment by loki79uk** [comment]
Closing this as it seems to be caused in each case by an incorrect collision mask set on the individual mods - nothing I can do about it in UAL.
