### ISSUE TITLE
Non-standard bales not loading properly.

### ISSUE THREAD

**Issue by GMNGjoy** [loki79uk/FS22_UniversalAutoload#61]
Version: Latest  (v1.0.7.0)
Baler mod: https://www.kingmods.net/en/fs22/mods/john-deere-560m-baler
Trailer mod: https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=230225&title=fs2022

Trailer Autoload Config
```
        <vehicleConfiguration configFileName="FS22_20ftGooseneck/lizardgooseneck.xml">  
            <loadingArea offset="0.000 1.100 -1.100" width="3.00" height="4.50" length="8.8"/>
            <options enableRearLoading="false" enableSideLoading="false" showDebug="true" />
        </vehicleConfiguration>
```

Bales are configured to be a _longer / taller_ version of the standard roundbale180, using this as the size property:
```<size isRoundbale="true" width="1.6" diameter="1.80"/>```

![fsScreen_2022_06_13_11_08_56](https://user-images.githubusercontent.com/107238894/173417235-cd6c926b-3df2-4e5e-a416-83337b32196d.png)

With the same trailer, UAL loads 12 roundbale 180's. Looking at debug - it appears that UAL is parsing these custom bales as rectangular not round, even though they are set as roundbales in their bale config (see screenshot for examples comparing base game roundbale180's and the custom ones). In addition, even though UAL is seeing that there is space to stack said bales - it is not doing so.

![fsScreen_2022_06_13_10_57_46](https://user-images.githubusercontent.com/107238894/173416061-dfd6a47c-282c-46d5-982b-05ed742f83c6.png)

![fsScreen_2022_06_13_10_53_13](https://user-images.githubusercontent.com/107238894/173416088-e4f62465-16ae-49f1-974e-8b0d0135f57e.png)

 I understand that this is a custom bale - and if there is something that needs adjusting with the bale itself i'm happy to help test any suggested changes. Looking close at the boxes that UAL is adding in debug mode - it appears that the bale model itself is slightly bigger than the "spec" is making it seem - would the model then need to be scaled?

**Comment by loki79uk** [comment]
This should fix the orientation/square bale issue:
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.0.7.5

If you are still having issues with the sizes, let me know on here or via Discord: Loki_79#2864
