### ISSUE TITLE
Issue with enhanced vehicle mod

### ISSUE THREAD

**Issue by 112TEC-Chris** [loki79uk/FS22_UniversalAutoload#65]
Hi
when using this Mod, some features like Handbrake and differential on/off from enhanced vehicle are not working for all vehicles. the same problem was after patch 1.4.1 and after the next update of this mod the problem was gone. But now it is there again. (Version 1.1.0.0) As far as i know, it worked til version 1.0.7.5

**Comment by loki79uk** [comment]
From your description, I suspect it could be related to this commit in 1.0.7.3: https://github.com/loki79uk/FS22_UniversalAutoload/commit/cc38156a78d3e7e0a64bec498bc878fcc210b73c

HOWEVER, the reverted change was only introduced in 1.0.6.0, so the time does not line up with the 1.4.1 release in April.

Can you reproduce it with only those two mods (UAL and EV)?  It would be great if you are available to discuss on Discord: Loki_79#2864

**Comment by 112TEC-Chris** [comment]
Sorry i was wrong. This time another Mod was the problem. Iwill close this issue
