### ISSUE TITLE
Pallet arrangements on version 1.1.0.0

### ISSUE THREAD

**Issue by Khratoz666** [loki79uk/FS22_UniversalAutoload#66]
First of all. Thanks for this great mod. I've noticed that with this new weight distribution feature, all the pallet that is loaded especially in a krone liner trailer, pallets gets spaced out a little bit far and there is large gap between each pallet now.  I like the other feature like bigger area for loading etc. Tried to revert back to older version but the issue still there. Thanks

**Comment by loki79uk** [comment]
Is this for all pallets?  It loads in the same pattern as always for me.  Have you used any mods with different sized pallets?  Or have you set any pallet sizes in the local settings file?

**Comment by Khratoz666** [comment]
Sorry for your trouble. I'm still figuring out what the cause of this. Tried with older save and your latest update seems working just fine.

**Comment by Khratoz666** [comment]
You were right. This liftable pallet mod was the culprit. Remove that mod and adjusting my save game to all of the pallet back to the original and now everything is perfectly line up again. Thanks for this great mod and sorry for the trouble.

**Comment by loki79uk** [comment]
If you still want to use the liftable pallets mod, then you will just need to add an entry for the dimensions in your local settings file:  %userprofile%\Documents\My Games\FarmingSimulator2022\modSettings\UniversalAutoload.xml

I have not looked exactly how it works, but I guess you will need to copy all the settings from the main mod like:
`<containerConfiguration containerType="EURO_PALLET" name="FS22_LiftablePallets:lettuceBoxPallet"/>`
`<containerConfiguration containerType="EURO_PALLET" name="FS22_LiftablePallets:tomatoesBoxPallet"/>`
...
`<containerConfiguration containerType="EURO_PALLET" name="FS22_LiftablePallets:oliveOilPallet" sizeY="0.450"/>`
etc...
