### ISSUE TITLE
Loaded zones are always considered loaded

### ISSUE THREAD

**Issue by coder2000** [loki79uk/FS22_UniversalAutoload#68]
After loading a pallet or bale, if they fall off nothing else is loaded in their place as if the area is still marked as loaded.

**Comment by loki79uk** [comment]
Hi, I think this is how it has always been?  There is no way for UAL to know that you have removed a pallet without constantly checking that each pallet is still there.

The loading algorithm assumes that everything is where it was originally loaded unless you use the unload all button.  With manual unloading, it will try one pass to fill in gaps, but the old loading pattern is not stored, so it may not fit.  Unload and reload should always work for the best packing.

**Comment by coder2000** [comment]
Yeah, I understand why it would be difficult to account for when an object falls off the trailer.
