### ISSUE TITLE
Cant switch pallet type in the Krone trailer

### ISSUE THREAD

**Issue by Praetorian726** [loki79uk/FS22_UniversalAutoload#69]
With the krone trailer, the default keybind for changing autoload type, ie euro pallets, big bags ect, is Z. The keybind for the curtain is also Z. This prevents the changing of pallet types as it will only open or close the curtain. I have disabled all other mods and still have this issue. Even when the "open curtain tooltip is not shown pressing the Z key still opens the curtain.
![Screenshot (29)](https://user-images.githubusercontent.com/108956795/178067446-3b2d0bd8-5139-44d7-a3f4-cbe34c6ddc97.png)

**Comment by loki79uk** [comment]
Hi, you have got the wrong autoloading mod I'm afraid.  Mine uses T for changing pallet type (in SP) and you have to rebind it for MP: 
![image](https://user-images.githubusercontent.com/76516343/178068774-5c7daf0b-13ab-4adc-8d06-3075904a0b20.png)

**Comment by Praetorian726** [comment]
I have Pallet Autoload Specialization which one should I be using

**Comment by loki79uk** [comment]
You can use whichever one you prefer.  Or you can even use both together if you like.

Pallet Autoload Specialisation has to be added to each mod, but that means it can be better tailored to each trailer.

This one (Universal Autoload) is installed by default on all of the suitable base game trailers, and can be customised using a local settings file for any trailer with tension belts.  There is also an add-on mod available that provides support for a large number of mod hub trailers.
