### ISSUE TITLE
Lua call stack

### ISSUE THREAD

**Issue by SchorschiBW** [loki79uk/FS22_UniversalAutoload#70]
I get the following error when activating the latest version (version 1.2.0.0) of Universal Autoload from Github:

2022-07-18 16:02 LUA call stack:
  dataS/scripts/specialization/SpecializationUtil.lua (43) : printCallstack
  =E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_UniversalAutoload/UniversalAutoload.lua (117) : registerFunction
  dataS/scripts/specialization/TypeManager.lua (260) : registerFunctions
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1160) : update
2022-07-18 16:02 Error: Running LUA method 'update'.

and

dataS/scripts/specialization/SpecializationUtil.lua(46) : Error: Function 'getIsFolding' already registered as function in type 'FS22_AutoloadTruckPackDf.PalletAutoLoaderTrailer*'!
2022-07-18 16:02 LUA call stack:
  dataS/scripts/specialization/SpecializationUtil.lua (43) : printCallstack
  =E:/Dokumente/My Games/FarmingSimulator2022/mods/FS22_UniversalAutoload/UniversalAutoload.lua (117) : registerFunction
  dataS/scripts/specialization/TypeManager.lua (260) : registerFunctions
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1160) : update
2022-07-18 16:02 Error: Running LUA method 'update'.

* also carFillable, mixerWagon, woodTruck... etc.

With the version from the Giants Modhub (version 1.1.0.0) it was in line 96 of UniversalAutoload.lua

As a result, a large number of entries from appear in the console and in the log

2022-07-18 16:02 Error: No more interval timers

If I deactivate the mod, the error is gone

My log:

[log.txt](https://github.com/loki79uk/FS22_UniversalAutoload/files/9132611/log.txt)

**Comment by loki79uk** [comment]
Which version of `aPalletAutoloader` by Achimobvil are you using?  I tested with1.8.1.0 of aPalletAutoloader (latest ModHub) and 1.0.0.1 of FS22_AutoloadTruckPackDf and not getting the callstack issue - both autoloads are working.  Could be that an older (or newer) version of aPalletAutoloader uses the same function name as me (getIsFolding)?

**Comment by SchorschiBW** [comment]
Not really. I renamed the Modhub version to FS22_UniversalAutoload.old, so Farming Simulator only complains that it can't do anything with this file.

The problem also exists if only the FS22_UniversalAutoload.zip is in the mod folder.

If the mod is deleted, then everything works, no Lua errors, no entries "Error: No more interval timers"

**Comment by SchorschiBW** [comment]
ooops. I forgot this file. I will try it again

**Comment by loki79uk** [comment]
> It works

Glad you got it sorted!
