### ISSUE TITLE
Compatibility for "Autodrive" and "Course player".

### ISSUE THREAD

**Issue by Myiamoto86** [loki79uk/FS22_UniversalAutoload#71]
Loki, good night.

I had already noticed that there is no compatibility or I didn't see / understand how to do it, but is there any way to make your mod compatible with the problem title??? If there is already a solution, please explain to me how to proceed later.

If there really is no compatibility, I can try to help.

I don't have much knowledge in lua programming, but if you allow, I'll study the case to evolve with this subject. I hope I can help with the case. Of course, if you allow it.

Hugs.

**Comment by loki79uk** [comment]
I'm actually working on a bale collection mode now.  It will be the main feature added to version 1.3 (i.e. the next main release after the current one).  I will update this bug to let you know when there is a beta version to test with this feature.

**Comment by Myiamoto86** [comment]
Good afternoon Loki,
Good news.... I'm looking forward to seeing how it turns out.

**Comment by loki79uk** [comment]
> Good afternoon Loki, Good news.... I'm looking forward to seeing how it turns out.

It looks like this will be a lot more work than I was expecting, so I will still work on it but plan to get some other features completed first.  Now that there is a manual bale collection mode, I think the priority is to add log loading.  I will look at CoursePlay and AutoDrive again after that.

**Comment by judg393** [comment]
Loki i agree autoload log would be outstanding addition to UAL. :D will be eagerly awaiting this

**Comment by loki79uk** [comment]
UAL is now compatible with Course Play for bale collection, as of the latest release: https://github.com/loki79uk/FS22_UniversalAutoload/releases

Log loading is kind of working, but they stack like pallets and tend to roll all over the place, so I either need to make a new loading pattern, or a log collection mode similar to the bale collection mode.

**Comment by loki79uk** [comment]
I am going to close this now that Course Play integration seems to be working.  If there are any related issues, please create a new bug.

It is unclear to me how integration with AutoDrive would work.  The UAL unloading command is not really designed to be performed automatically, it needs a human to determine the unload location, and you could only use a single location once or twice before it becomes full and unloading will fail.  Better to just drive over a sell point and let the pallets sell automatically.  If you can come up with a good use case, then I'm open to ideas.
