### ISSUE TITLE
LUA errors when starting a new clean install

### ISSUE THREAD

**Issue by FanFSEver** [loki79uk/FS22_UniversalAutoload#74]
Loki

Just came across this problem when testing UA for the new features.

When a new game is started and there is not a modSetting file a number of problems were experienced. These errors disappear as soon as game is saved and restarted.
Does not appear at all when updating in a current savegame.

The zones of UA is shown as if it is in a debug mode.

![Zones](https://user-images.githubusercontent.com/102517848/180609531-f147af63-1946-461c-8529-f3c09cd56380.jpg)

Every time time objects(pallets, bags, bales) are loaded only one is loaded(Shift+R) and then the "_Loading area is full._" message appears. But if you load (Shift+R) again it loads the next object but with the same error message. 

In the log the following message is written:

```
*** Bremer Transportwagen TP 500 S ***
*** getCanImplementBeUsedForAI ***
Error: Running LUA method 'update'.
D:/Users/FanFSEver/My Games/FarmingSimulator2022/mods/FS22_UniversalAutoload/UniversalAutoload.lua:2350: attempt to compare number with nil

===============================
FIND LOADING PLACE FOR bigBag
RESET LOADING PATTERN
ADDING NEW PLACE FOR: bigBag [1.050, 1.666, 0.866]
-------------------------------
width: 2.2999999523163
length: 4.75
 N1: 2 ,  M1: 5
 N2: 2 ,  M2: 4
shouldRotate: false
LoadingAreaIndex: 1
currentLoadWidth: 0.866
currentLoadLength: 1.05
currentActualWidth: 1.732
currentActualLength: 0
-------------------------------
USING LOAD PLACE - height: 1.666
Error: Running LUA method 'update'.
D:/Users/FanFSEver/My Games/FarmingSimulator2022/mods/FS22_UniversalAutoload/UniversalAutoload.lua:2350: attempt to compare number with nil
```
Some of the problems may present in different ways. 
Checked it with most of the standard trailers and pickups. Happened with every vehicle I tried.

With Bale Autoload enabled all bales entering the loading zone is loaded however, the same error message appears for every bale. Here is an example when 3 bales are loaded.
```
===============================
FIND LOADING PLACE FOR squarebale240
RESET LOADING PATTERN
ADDING NEW PLACE FOR: squarebale240 [1.210, 0.910, 2.400]
-------------------------------
width: 2.2999999523163
length: 4.75
 N1: 1 ,  M1: 1
 N2: 0 ,  M2: 3
shouldRotate: true
LoadingAreaIndex: 1
currentLoadWidth: 2.4000000953674
currentLoadLength: 1.210000038147
currentActualWidth: 0
currentActualLength: 0
-------------------------------
DID NOT FIT HERE...
ADDING NEW PLACE FOR: squarebale240 [1.210, 0.910, 2.400]
-------------------------------
width: 2.2999999523163
length: 4.75
 N1: 1 ,  M1: 1
 N2: 0 ,  M2: 3
shouldRotate: true
LoadingAreaIndex: 1
currentLoadWidth: 2.4000000953674
currentLoadLength: 2.4200000762939
currentActualWidth: 0
currentActualLength: 1.210000038147
-------------------------------
DID NOT FIT HERE...
ADDING NEW PLACE FOR: squarebale240 [1.210, 0.910, 2.400]
-------------------------------
width: 2.2999999523163
length: 4.75
 N1: 1 ,  M1: 1
 N2: 0 ,  M2: 3
shouldRotate: true
LoadingAreaIndex: 1
currentLoadWidth: 2.4000000953674
currentLoadLength: 4.8400001525879
currentActualWidth: 0
currentActualLength: 3.6300001144409
-------------------------------
DID NOT FIT HERE...
FULL - NO MORE ROOM
===============================
```

Windows 11 Pro
Using Farming Simulator 22 ver 1.6.0.0 (steam version)
No DLC's or any other mod loaded. UA only mod in mod folder.

It would be a pity if a new user experience this when trying to use this excellent mod.

FanFSEver

**Comment by loki79uk** [comment]
Thanks for catching this, there is always something I forget to test!  In this case `pricePerPallet` is never initialised without the settings file.  Fixed it now, new release incoming.

**Comment by FanFSEver** [comment]
Will test as soon as available

**Comment by loki79uk** [comment]
This one should work now: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.0.0-candidate-004

**Comment by FanFSEver** [comment]
Have tested with a lowloader, the Krone, boxed and bale trailer as well as pickup truck. All working seamlessly. 

Excellent work. Will close this one now.
