### ISSUE TITLE
Bale loading position

### ISSUE THREAD

**Issue by FanFSEver** [loki79uk/FS22_UniversalAutoload#75]
I mostly play with 2.4m length bales and have noticed that recently UA defaults to loading bales sideways. 

Is it possible to add a setting to a mod to rather use the lengthwise loading pattern, (as in real life) and as UA did earlier? The longer trailers loads more bales in the lengthwise format - there is usually a bit of trailer bed open at the end when loading sideways. 

Here is a poorly manual loaded Farmtech DPW1800 bale trailer which will allow 3 more bales total (if all were loaded). On the ground is the max as loaded by UA
![maxBalesLoad](https://user-images.githubusercontent.com/102517848/180613921-818d87a5-7343-459a-8c2a-79bfd1725f64.jpg)

**Comment by loki79uk** [comment]
UAL should always pack in the most efficient orientation, but I changed it to load lengthways when there was no difference, mainly to make unknown packing more efficient.  I.e, if you loaded a single bale lengthways, then it blocks more available area than loading a single bale width ways.
However, you should be able to force lengthways packing on all trailers by adding the `neverRotate = "true"` to the 2.4m bales in your local settings.

**Comment by loki79uk** [comment]
Never rotate works, but I don't get four stacks with the DPW1800. (although I may tweak the size now to see if I can)
![image](https://user-images.githubusercontent.com/76516343/180618162-ecd61c19-71f3-4fa7-ba94-9fd1b012213f.png)

![image](https://user-images.githubusercontent.com/76516343/180618142-1e67b037-7f2c-43c1-82ea-3d5ae3c3c2e5.png)

**Comment by loki79uk** [comment]
Best I can do for the flat trailer, but it doesn't quite work for the round bale setup.
![image](https://user-images.githubusercontent.com/76516343/180619560-6baea46e-3cbf-49bf-87e1-e91a24bb3cae.png)
![image](https://user-images.githubusercontent.com/76516343/180619554-867a4df2-cd2e-4c09-aff9-324af43be68c.png)

**Comment by loki79uk** [comment]
BUT there is some clipping against the frame of the trailer when loading pallets, so I don't think I will change it in the standard configuration.
Here is the text for you to copy:
```
        <vehicleConfiguration configFileName="data/vehicles/farmtech/dpw1800/dpw1800.xml">
            <loadingArea offset="0 1.130 -0.82" width="2.42" height="2.20" length="9.65" baleHeight="2.8"/>
            <options isBaleTrailer="true"/>
        </vehicleConfiguration>
```
![image](https://user-images.githubusercontent.com/76516343/180619643-023ad7f7-4836-4b86-8f0f-6c3bca1794c2.png)

**Comment by FanFSEver** [comment]
Loki

Thanks for the feedback and the extra solution. Thought there had to be specific reasoning behind it and that there will be an alternative as always. Love the ability of this mod to make individual changes to suit a specific play style.

Thank you for going the extra mile with the code. Was planning to do something like that for the trailers I usually use. Nice to have an example now.

I like to play kinda realistically except the manual stacking is just out of my league. UA is a life saver. So I will usually collect bales with a stacker using Courseplay on the field, Drop it of next to the field and collect with a Super-B to transport to the storage facility for sale when prices are best. Waiting for Autodrive to create an unload without a baletrigger. It currently requires the baleTrigger to unload bales.

Will close as soon as I have applied the recommendation to my game.
