### ISSUE TITLE
How good is Universal Autoload?

### ISSUE THREAD

**Issue by FanFSEver** [loki79uk/FS22_UniversalAutoload#77]
They say a picture is worth a thousand words

![Pic1000Words](https://user-images.githubusercontent.com/102517848/180624191-c4ecdc41-05dd-4c06-bb3e-395b35d3f7b9.jpg)

For those that prefer words. Check the Corteva big bag pallet behind the sprayer's wheel. The pallet is partially filled and was loaded after the vehicles were on the trailer. The trailer is a privately edited trailer and the Universal Autoload settings are controlled with the settings in the universalautoload.xml file in modSettings directory. No autoload settings in the mod itself.

I cannot emphasize the respect I have for the modder. Absolutely outstanding.

**Comment by loki79uk** [comment]
I'm kind of sad to close this issue, but I'm glad everyone is enjoying it!  Here is to another year of FS22! :D
