### ISSUE TITLE
missing "string_key" in l10n_cs.xml

### ISSUE THREAD

**Issue by TZZhan** [loki79uk/FS22_UniversalAutoload#79]
Hi Loki,
I play fs22 in simplified Chinese. I found some translation problems. In the screenshot you can see that all the strings about the mod are not displayed properly. I think there is no i18n file in Simplified Chinese. Could you please improve this part? Thanks a lot.
![screenshot](https://user-images.githubusercontent.com/8191963/181407728-0ac56116-fc14-44c6-91ad-9450dcf88d96.jpg)

**Comment by loki79uk** [comment]
Hi, I certainly plan to get around to adding the missing languages.  If you can help with the translations, please let me know!

**Comment by TZZhan** [comment]
Thanks for you quick reply. Great! I would be happy if I could help you.
I don't know much about MOD development, I think the international development should be one language file for each language, like Chinese for l10n_cs.xml, English for l10n_en.xml. If so, please give me the English and Chinese files, I can translate English to Chinese. My email is "tz46456@163.com".

**Comment by loki79uk** [comment]
Sorry, I keep meaning to split the translations into separate l10n files, but for now everything is listed in the moddesc: https://github.com/loki79uk/FS22_UniversalAutoload/blob/main/modDesc.xml

In the <l10n> section, each phrase has a translation for each different language.

**Comment by TZZhan** [comment]
Hi loki,
I made a preliminary translation. Please check the pr. Please let me know if you have any questions, thanks.

**Comment by loki79uk** [comment]
Hi, thank you for the translation.  It looks good to me.  I am away on holiday until next weekend, so I will merge the pull request when I get back.

**Comment by loki79uk** [comment]
Please re-open if there are any issues, but your PR should be included now in the latest release.  Thank you for the contribution!
