### ISSUE TITLE
Lua error (possibly with step deck trailers)

### ISSUE THREAD

**Issue by danieljudge** [loki79uk/FS22_UniversalAutoload#80]
I'm getting the below error when using the `LODE KING Renown Drop Deck` I also saw it with a few other vehicles/trailers but I was accurately reproducing it with the LODE KING. 

Error:
```
2022-08-03 15:10 Error: Running LUA method 'update'.
C:/Users/xxxxx/Documents/My Games/FarmingSimulator2022/mods/FS22_UniversalAutoload/UniversalAutoload.lua:2448: attempt to index a nil value
```

To reproduce:
1. Buy a truck and that trailer
2. Spawn a fair few pallets and things of different sizes
3. Load up a single type of pallet, then drive around the other pallets looking to load up another type
4. Game should go all funny and that error should be spamming the console

I did add the following change and tested it and things seem to be working fine now, with vanilla and mod vehicles/trailers.

From line 2446 (original):
```
if #spec.loadArea > 1 then
	local i = spec.objectToLoadingAreaIndex[object]
	local _, offsetY, _ = localToLocal(spec.loadArea[i].rootNode, spec.loadVolume.rootNode, 0, 0, 0)
	y = y - offsetY
end
```

To:
```
if #spec.loadArea > 1 then
	local i = spec.objectToLoadingAreaIndex[object]
	
	if i then 
		local _, offsetY, _ = localToLocal(spec.loadArea[i].rootNode, spec.loadVolume.rootNode, 0, 0, 0)
		y = y - offsetY
	end
end
```

**Comment by loki79uk** [comment]
Thanks for letting me know, and for the detailed bug report!  I'm at work now, but will get it fixed and resubmitted this evening.

**Comment by loki79uk** [comment]
Are you able to chat on Discord?  Loki_79#2864

I can see exactly how this error could happen from looking at the code, but I have not been able to reproduce it yet.  I can apply a fix and resubmit to GIANTS, but would be good to confirm that it has fixed the bug before I submit it.

**Comment by loki79uk** [comment]
Hotfix is live in latest ModHub release (v1.2.1.0).  Confirmed as fixed by danielJudge via Discord.
