### ISSUE TITLE
Did the selectedConfigs param get disabled?

### ISSUE THREAD

**Issue by ScootersWorkbench** [loki79uk/FS22_UniversalAutoload#87]
Hey Loki,
I have a truck with a loading area defined.   I want to add a toolbox option in and change the UAL area.   When I had the selectedConfigs Param,  UAL no longer loads for any configurations.   I have used the <vehicleTypes> to have the options to add the toolbox.  So I have multiple vehicle configurations.   If I take out the selectedConfigs param,  then UAL works but then only one UAL area is defined. 
Thanks, 
Scooter

**Comment by loki79uk** [comment]
Hi, I am working on this already - I think there are some vechiles where there are different designs, but for whatever reason those do not translate into "configurationSets".   Can you confim if the only selectable option in the shop for that truck is "Design"?

**Comment by ScootersWorkbench** [comment]
It's a pickup truck,  vehicleType= car

I have the following configurations:

designConfigurations
design2
design3
design4
design5
vehicleTypeConfigurations  (was design6 but thought maybe it was looking for vehicleType, so I changed it)  Always sets vehicleType to "car"
attacherJointConfigurations


plus base & designMaterial Color Configs.

**Comment by loki79uk** [comment]
I've made a pre-release that should hopefully fix this issue:
https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.1.4

Please try it and let me know how it goes!

**Comment by ScootersWorkbench** [comment]
Well,  some success.   The selectedConfigs param is working again.   However,  it doesn't seem to be changing the loading area.  It is possible that I'm not coding correctly or I've not set the correct "Configuration" it is looking for.

**Comment by loki79uk** [comment]
'useConfigName' parameter added in: https://github.com/loki79uk/FS22_UniversalAutoload/commit/96ad22ea2372f4db6a719879688118293810093f

If specified, the name given will be used to define the configuration that is indexed by `selectedConfigs`.  If not supplied, then the standard configuration set method will be used.

**Comment by loki79uk** [comment]
I think this is solved.  Closing for now, please reopen if there are any issues!
