### ISSUE TITLE
Manually Loading Partially Full Pallets

### ISSUE THREAD

**Issue by dmoddie** [loki79uk/FS22_UniversalAutoload#94]
Hi,
is there a reason why "TOGGLE_FILTER" is disabled when "manualLoadingOnly" is enabled?

I'd like to use the manual loading mode but still be able to decide whether to load only full or any pallets. So I've moved it behind the "if not UniversalAutoload.manualLoadingOnly then [...] end" part and it's working fine so far.

Are there any problems I haven't encountered yet? If not, may we see that change implemented in a future version?

Awesome mod btw :)

**Comment by loki79uk** [comment]
Hi - if I'm honest I didn't really think it though properly.  The main reason was that if you are driving around I thought you would not want to see a loading filter option when you cannot load.  The material and container types are still used for unloading.

Two initial ideas - I could enable that option only when on foot, OR I could make sure that it is set to accept all pallets (partial or full).  After all, with the manual loading only option, you have complete control over which pallets to load anyway.

Please, let me know what you think!

**Comment by loki79uk** [comment]
Should be implemented now in: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.1.8

**Comment by dmoddie** [comment]
Works great. Thank you very much.
