### ISSUE TITLE
Bales arrangement

### ISSUE THREAD

**Issue by outstranger** [loki79uk/FS22_UniversalAutoload#95]
Hi Loki,

Fantastic work on this UAL mod.
Just wondering... I have the long ponse bale wagon and added your UAL code.
In order to optimise the surface I have created 3 differents loading areas front with 24 pos., midle with 3 pos. (the one with the issue) and rear with 6 pos.. Is there any tric to flip the middle position like in the picture (hey its hand loaded... ;-) )?

Best regards.

![Farming Simulator 22 Screenshot 2022 09 10 - 22 28 36 88](https://user-images.githubusercontent.com/50044560/189500951-94bcea75-83e0-4017-aa12-f08a4a90c933.png)

**Comment by loki79uk** [comment]
The only way to define orientation for a particular loading area would be to tweak the dimensions to be a multiple of the length.  So, e.g. for a 240 bale we have:
`<containerConfiguration containerType="BALE" name="squarebale240" sizeX="1.210" sizeY="0.910" sizeZ="2.40"/>`

If you make the zone exactly 2.40m wide, then there would not be room for two times 1.21m, so you should get a single bale in the width ways orientation.  You still need the other dimension to be at least 1.21m.

Of course, this trick/hack will only work for that specific bale size, and having multiple zones like that will probably not be very efficient for packing any other bales or pallets that have different dimensions.

**Comment by outstranger** [comment]
Thanks for your reply.
Managed to fit everything nicely with thos code:

<loadingArea offset="0.000 1.39 1.050" width="2.8" height="2.200" length="8.82" baleHeight="2.80"/>
<options enableSideLoading="true" isBaleTrailer="true"/>
<loadingArea offset="0.000 1.39 -3.35" width="2.8" height="2.200" length="2.44" baleHeight="2.80"/>
<options enableSideLoading="true" isBaleTrailer="true"/>
<loadingArea offset="0.000 1.39 -4.57" width="2.8" height="2.200" length="4.44" baleHeight="2.80"/>
<options enableSideLoading="true" isBaleTrailer="true"/>

Have a nice sunday.

**Comment by willrh2** [comment]
hi there I am trying to do a similar thing with a bale trailer and have successfully added two loading areas but the second part won't load do you know what I am doing wrong?
![Uploading Screenshot 2023-08-07 at 22.52.55.png…]()

**Comment by loki79uk** [comment]
> hi there I am trying to do a similar thing with a bale trailer and have successfully added two loading areas but the second part won't load do you know what I am doing wrong?

It is hard to say.  For some reason your screenshot just links back to this thread.  Can you post the configuration that you are using, and ideally a screenshot of the debugging display.  Most probably there is some overlap, in which case you either need to move the areas apart, or try setting the `zonesOverlap="true"` flag.

**Comment by willrh2** [comment]
<img width="1440" alt="Screenshot 2023-08-07 at 22 52 28" src="https://github.com/loki79uk/FS22_UniversalAutoload/assets/76132412/0c8286b6-c32a-4f06-b704-c6964304c3cc">

**Comment by willrh2** [comment]
<img width="1440" alt="Screenshot 2023-08-08 at 20 49 56" src="https://github.com/loki79uk/FS22_UniversalAutoload/assets/76132412/880b2391-6859-4152-82ad-02a5b3abb7b3">


<universalAutoLoad>
            <vehicleConfigurations>
                <vehicleConfiguration>
                    <loadingArea offset="0.000 1.700 1.200" width="2.6" height="4.0" length="12.05"/>
                    <loadingArea offset="0.000 1.700 -5.50" width="2.6" height="4.0" length="1.3"/>
                     <options disableHeightLimit="true" isBaleTrailer="true" zonesOverlap="true"/>
                </vehicleConfiguration>
            </vehicleConfigurations>
    </universalAutoLoad>
