### ISSUE TITLE
Cannot load euro pallet `boardsStackPallet`s more than a single layer without becoming "full"

### ISSUE THREAD

**Issue by krrg** [loki79uk/FS22_UniversalAutoload#96]
This one has proven to be quite a puzzle for me: I seem unable to load a pallet of planks (name="boardsStackPallet") more than a single layer without becoming full. I've had no issues with other pallet types, but something about these pallets is just refusing to stack more than a single layer.

I've tried using both the KRONE Profi Liner as well as the Demco Steel Drop Deck, and both trailers have this issue -- they'll happily load a single layer of boards pallets, then suddenly become full. I've also tried manually adding a `containerConfiguration` in my `modSettings/UniversalAutoload.xml` and have played around with adjusting the size and adding a `neverStack="false"`, but...nothing. They just won't stack. I don't have this issue with other types of pallets; for example, I can load three layers of honey pallets easily in the KRONE.

Any thoughts on what might be going on here? At this point I'm simply at a complete loss.

Edit: After further inspection, it looks like the maximum load height is in part based on the computed density of the object being loaded - perhaps the planks are simply considered to be too dense to safely go more than a single layer?

![CannotStackPlanks](https://user-images.githubusercontent.com/8496492/190342469-9b9016ee-841b-4af9-95b0-99335899715c.png)

**Comment by loki79uk** [comment]
> Edit: After further inspection, it looks like the maximum load height is in part based on the computed density of the object being loaded - perhaps the planks are simply considered to be too dense to safely go more than a single layer?

I was going to suggest this, but it could also be the pallet definition is not set high enough.

According to the [spreadsheet](https://github.com/loki79uk/FS22_UniversalAutoload/blob/main/AutoloadHeightCalculator.xlsx), they should stack two high on anything over 2m, so should be two pallets high on both the KRONE and Demco.

I'll have look today.

**Comment by loki79uk** [comment]
Okay I added a quick debugging output and the spreadsheet is wrong, so either GIANTS changed the pallet mass with one of the patches, or I got it wrong before.
`DENSITY (mass/volume): 1.6/0.707625 = 2.261085`
`LIMITED MAX HEIGHT from 2.5 to 1.0324295125949`
So it is 'expected' behaviour, but I wonder why the mass is higher now.  I'm sure I would have spotted this when I did the original pallet definitions.  I'd better check everything else now, and then review the height stacking limit.

**Comment by krrg** [comment]
It does run in my mind that GIANTS has changed the pallet mass a couple times, so I'm not surprised that something went awry. In the meantime, I created a workaround that allows users to optionally bypass the density function and just specify a custom "safe" limit that they are comfortable stacking things to (as long as it can fit in the vehicle) https://github.com/loki79uk/FS22_UniversalAutoload/pull/97

**Comment by loki79uk** [comment]
I have just tested all of the base game pallets, and the only two that have changed density are:

canolaOilPallet = 1.591  (previously 1.945)
boardsStackPallet = 2.261  (previously 1.497)

Canola oil makes no sense because both olive oil and sunflower oil are still 2.008
I wonder if they have made wood heavier or something?

**Comment by loki79uk** [comment]
I think the best solution for now is to limit the maximum corrected density to 1.5, so:
`local density = math.min(mass/volume, 1.5)`

For the base game pallets, this only affects the boards stack and the three oil pallets.  The numbers shown below are the number of pallets stacked in a 2.5m tall loading area (KRONE).  BUT I anticipate stability issues with really heavy stuff like gold pallets (assuming that the defined mass is realistic for gold).

![image](https://user-images.githubusercontent.com/76516343/190849472-b6d97ade-26a6-44a5-bd1c-247cd7cdf4fc.png)

**Comment by krrg** [comment]
That is very odd that only canola and boards changed.

Maybe I just live dangerously 😁 but I've always stacked the the boards pallets 3 high in the Krone, and I've never had any problems with tipping. Then again, I don't tend to take corners at high speed.

**Comment by loki79uk** [comment]
I've added the 1.5 limit in the latest release, which hopefully should be good enough for now.  I will add an option that removes the limit for specific vehicles.

**Comment by loki79uk** [comment]
New `disableHeightLimit` option added in: https://github.com/loki79uk/FS22_UniversalAutoload/releases/tag/v1.2.2.5

**Comment by loki79uk** [comment]
I think this is solved.  Closing for now, please reopen if there are any issues!
